<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/administration" class="nav-link <?= (isset($page) && $page == "index") ? 'active' : ''; ?>"><?= \Core\Language::get('home'); ?></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/administration/administrators/<?= $admin->getId(); ?>/edit" class="nav-link"><?= \Core\Language::get('my_account'); ?></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/administration/logout" class="nav-link"><?= \Core\Language::get('logout'); ?></a>
        </li>
        <li class="nav-item dropdown">
            <?php if (!empty($_COOKIE['language']) && $_COOKIE['language'] == "fr_FR") { ?>
                <a href="#" class="nav-link dropdown-toggle" id="droplangdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="flag-icon flag-icon-fr"> </span> Français</a>
            <?php } else { ?>
                <a href="#" class="nav-link dropdown-toggle" id="droplangdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="flag-icon flag-icon-us"> </span> English</a>
            <?php } ?>
            <div class="dropdown-menu" aria-labelledby="droplangdown">
                <?php if (!empty($_COOKIE['language']) && $_COOKIE['language'] == "fr_FR") { ?>
                    <a class="dropdown-item" href="/lang/pref/en"><span class="flag-icon flag-icon-us"> </span> English</a>
                <?php } else { ?>
                    <a class="dropdown-item" href="/lang/pref/fr"><span class="flag-icon flag-icon-fr"> </span> Français</a>
                <?php } ?>
            </div>
        </li>
    </ul>
</nav>

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="/administration" class="brand-link">
        <img src="/dist/img/drivncook.png" alt="Driv'n'Cook Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Driv'n'Cook</span>
    </a>

    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="/administration/administrators/<?= $admin->getId(); ?>/edit" class="d-block"><?= $admin->getFirstname() . ' ' . $admin->getLastname(); ?></a>
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="/administration" class="nav-link <?= (isset($page) && $page == "index") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-home"></i>
                        <p>
                            <?= \Core\Language::get('home'); ?>
                        </p>
                    </a>
                </li>

                <li class="nav-header"><?= \Core\Language::get('sidebar_franchise'); ?></li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['franchises', 'add_franchises'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['franchises', 'add_franchises'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            <?= \Core\Language::get('franchises'); ?>
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/administration/franchises" class="nav-link <?= (isset($page) && $page == "franchises") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('see_franchises'); ?>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/administration/franchises/add" class="nav-link <?= (isset($page) && $page == "add_franchises") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('add_franchise'); ?>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['trucks', 'trucks_add'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['trucks', 'trucks_add'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-truck"></i>
                        <p>
                            <?= \Core\Language::get('trucks'); ?>
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/administration/trucks" class="nav-link <?= (isset($page) && $page == "trucks") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('see_trucks'); ?>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/administration/trucks/add" class="nav-link <?= (isset($page) && $page == "trucks_add") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('add_truck'); ?>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>


                <li class="nav-header">DRIV'N'COOK</li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['administrators', 'administrators_add'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['administrators', 'administrators_add'])) ? 'active' : ''; ?>">
                        <i class="fas fa-user-shield"></i>
                        <p>
                            <?= \Core\Language::get('administrators'); ?>
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/administration/administrators" class="nav-link <?= (isset($page) && $page == "administrators") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('see_administrators'); ?>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/administration/administrators/add" class="nav-link <?= (isset($page) && $page == "administrators_add") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('add_administrator'); ?>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['customer', 'add_customer'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['customer', 'add_customer'])) ? 'active' : ''; ?>">
                        <i class="fas fa-users"></i>
                        <p>
                            <?= \Core\Language::get('customer'); ?>
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/administration/customer" class="nav-link <?= (isset($page) && $page == "customer") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('see_customers'); ?>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/administration/customer/add" class="nav-link <?= (isset($page) && $page == "add_customer") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('add_customer'); ?>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['warehouses', 'add_warehouses', 'add_stocks_category', 'stocks_category'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['warehouses', 'add_warehouses', 'add_stocks_category', 'stocks_category'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-warehouse"></i>
                        <p>
                            <?= \Core\Language::get('warehouses'); ?>
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/administration/warehouses" class="nav-link <?= (isset($page) && $page == "warehouses") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('see_warehouses'); ?>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/administration/warehouses/add" class="nav-link <?= (isset($page) && $page == "add_warehouses") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('add_warehouse'); ?>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['add_stocks_category', 'stocks_category'])) ? 'menu-open' : ''; ?>">
                            <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['add_stocks_category', 'stocks_category'])) ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('categories'); ?>
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="/administration/stocks/category" class="nav-link  <?= (isset($page) && $page == "stocks_category") ? 'active' : ''; ?>">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>
                                            <?= \Core\Language::get('the_categories'); ?>
                                        </p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/administration/stocks/category/add" class="nav-link <?= (isset($page) && $page == "add_stocks_category") ? 'active' : ''; ?>">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p><?= \Core\Language::get('create_category'); ?></p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['invoices_received', 'invoices_issued', 'invoices'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['invoices_received', 'invoices_issued', 'invoices'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-file-contract"></i>
                        <p>
                            <?= \Core\Language::get('facturation'); ?>
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/administration/invoices/received" class="nav-link <?= (isset($page) && $page == "invoices_received") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('invoices_received'); ?>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/administration/invoices/issued" class="nav-link <?= (isset($page) && $page == "invoices_issued") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('invoices_issued'); ?>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/administration/invoices/add" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('add_invoice'); ?>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="/administration/event" class="nav-link">
                        <i class="nav-icon fas fa-calendar-week"></i>
                        <p>
                            <?= \Core\Language::get('event'); ?>
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/" class="nav-link">
                        <i class="nav-icon fa fa-chart-area"></i>
                        <p>
                            <?= \Core\Language::get('stats'); ?>
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>