<?php

/**
 * Traduction file for english language
 **/


return [

    "error" => "Error",
    '404_page_not_found' => '404 page not found',
    'an_error_occured' => 'An error as occured',
    'page_not_found' => 'Page not foud',
    'an_internal_error_occured_back_soon' => 'An internal error as occured , back soon',


    'drivncook_home' => 'Accueil Driv\'N\'Cook',
    'home' => 'Home',
    'back' => 'Back',
    "back_to_truck" => "Back to truck",
    "back_to_warehouse" => "Back to warehouse",
    "back_to_warehouses" => "Back to warehouses",

    'login' => 'Connexion',
    'login_to_my_admin_account' => 'Connexion à mon compte administrateur',
    'logout' => 'Logout',
    'login_to_my_franchise_account' => 'Login to my franchise account',

    'email' => 'Email',
    'password' => 'Password',
    'confirm_password' => 'Confirm password',
    'firstname' => 'Firstname',
    'lastname' => 'Lastname',
    'society_name' => 'Society name',
    'siret' => 'Siret',
    'manager' => "Manager",
    "status" => "Statuts",
    'phone_number' => 'Phone number',
    'address' => 'Adress',
    'city' => 'City',
    'postal_code' => 'Postal code',
    'state' => 'State',
    'country' => 'Country',

    "franchise_space" => "franchise space",

    'account_not_found' => 'Compte introuvable',
    'assign_to_truck' => 'Assign to truck',
    "assign_truck_immat_to_user" => "Assign truck immediately to user",
    'select_truck' => 'Select truck',
    'available_since' => "Available since",
    "available" => "Available",

    'administration' => 'Administration',
    "sidebar_administration" => "ADMINISTRATION",
    'my_account' => 'My account',
    "edit_my_account" => "Edit my account",
    'my_truck' => "My truck",

    'sidebar_service' => 'SERVICES',
    "sidebar_supply" => "Supply",
    "promotions" => "Promotions",
    "my_promotions" => "My promotions",
    "add_promotion" => "add promotion",
    "sidebar_settings" => "SETTINGS",
    "online_payments" => "Only payments",
    "promotion" => "Promotion",
    "menu" => "Menu",
    "menus" => "Menus",
    "my_menus" => "My menus",
    "add_menu" => "Add menu",
    "assign_to" => "Assign to",
    "assign" => "Assign",
    "deassign" => "Deassign",
    "assign_truck_to_user" => "Assign truck to user",

    'sidebar_franchise' => 'FRANCHISES',
    'franchises' => 'Franchises',
    'see_franchises' => 'See franchises',
    'add_franchise' => 'Add franchise',
    'edit_franchise' => 'Edit franchise',
    'select_franchise' => 'Select franchise',
    'drivncook_franchises' => 'Franchises Driv\'n\'Cook',

    'trucks_drivncook' => 'Driv\'n\'Cook trucks',
    'trucks' => 'Trucks',
    'truck' => 'Truck',
    'see_trucks' => 'See trucks',
    'add_truck' => 'Add truck',

    'immatriculation' => 'Immatriculation',
    'assign_truck_to_franchise' => 'Assign truck to franchise',

    'administrators' => 'Administrators',
    'see_administrators' => 'See administrator',
    'add_administrator' => 'Add administrator',
    'edit_administrator' => 'Edit administrateor',
    'drivncook_administrators' => 'Driv\'n\'Cook administrators',

    'warehouses' => 'Warehouses',
    'warehouses_drivncook' => "Driv'N'Cook warehouses",
    'warehouse' => 'Warehouse',
    'see_warehouses' => 'See warehouses',
    'add_warehouse' => 'Add warehouse',
    "edit_warehouse_name" => "Edit warehouse name <b>%s</b>",
    'warehouse_location' => 'Warehouse localisation',

    "edit_product_name" => "Edit product name <b>%s</b>",

    'location' => "Location",

    "warehouse_name" => "Warehouse name %s",

    'stocks' => 'Stocks',
    "total_of_products" => "Total products",
    "total_of_quantity_products" => "Total quantity of products",

    "view_stock_of_warehouse_name" => "View stock of warehouse name <b>%s</b>",

    'categories' => 'Categories',
    "category" => "Category",
    'the_categories' => 'The categories',
    'create_category' => 'Create category',

    'category_name' => 'Category name',
    'link_to_parent_category' => 'Link to parent category',
    'select_category' => 'Select category',

    "edit_parent_category" => "Edit parent category",
    "edit_category" => "Edit category",

    "category_name_must_uniq_label" => "Category name must uniq label",

    "parents_categories" => "Parents categories",

    'facturation' => 'Facturation',
    "my_invoices_received" => "My invoices received",
    'invoices_received' => 'Invoices received',
    'invoices_issued' => 'Invoices issued',
    'add_invoice' => 'Add invoice',
    'internal_invoice' => "Internal invoice",
    'external_invoice' => "External invoice",
    "settled" => "Settled",

    "received_invoices_from_drivncook" => "Received invoices from Driv'n'Cook",
    "issued_invoices_from_drivncook" => "Issued invoices from Driv'n'Cook",

    "transmitter" => "Transmitter",

    'stats' => 'Stats',

    'turnover_in' => 'Turnover in %s',

    "products_categories" => "products categories",
    "products_categories_drivncook" => "Driv'n'Cook products categories",

    "product_name" => "Product name",

    "quantity_to_supply" => "Supply quantity",
    "in_euros" => "(in €)",
    "in_percentage" => "(in %%)",

    "provider_name" => "Provider name",
    "provider_address" => "provider address",
    "provider_postal_code" => "Provider postal code",
    "provider_city" => "Provider city",

    'edit' => 'Edit',
    'add' => 'Add',
    'delete' => 'Delete',
    'see' => 'See',
    'save' => 'Save',
    'action' => 'Action',
    'created_at' => 'Created at',
    'received_at' => "Received at",
    "adjust" => "ADjust",
    'actual' => 'Actual',
    'block' => "Block",
    "supply" => "Supply",
    "yes" => "Yes",
    "unblock" => "Unlock",
    "no" => "No",
    "product" => "Product",
    "quantity" => "Quantity",
    "price_unit" => "Price unit",
    "price_resale" => "Price resale",
    "tva" => "TVA",
    "subtotal" => "Sous-Subtotal",
    "total_ht" => "Total HT",
    "total_ttc" => "Total TTC",
    "longitude" => "Longitude",
    "latitude" => "Latitude",
    "step1" => "Step 1",
    "step2" => "Step 2",
    "step3" => "Step Etape 3",
    "next_step" => "Next step",
    "remains" => "remains",
    "back_to_step1" => "Return to step 1",

    "print" => "Print",
    "import_an_external_invoice" => "Import an external invoice",

    "available_products" => "Available prtoducts",
    "selected_products" => "Selected products",
    "products" => "Products",
    "no_products" => "No products",
    "total_product_filter" => "Total product filter : {0}",

    "supply_warehouse_of_name" => "Supply warehouse of <b>%s</b>",
    "select_products_to_supply_or_add_it" => " Select products to supply or add on it.",
    "product_are_not_onlist_add_it" => "THis product are not on list ? Add it",

    "link_an_external_invoice_in_internal_invoice" => "Link an external invoice in internal invoice.",
    "download" => "Download",
    "download_external_invoice" => "Download external invocie",
    "delete_external_invoice" => "Delete external invoice",
    "delete_external_invoice_confirm" => "Are you sure to delete this external invoice ?",
    "date" => "Date",
    "import" => "Import",
    "validate" => "Validate",
    "close" => "Close",

    "adjust_invoice" => "Adjust invoice",
    "back_to_invoice" => "Back to invoice",
    "payed_the_amount" => "Payed the amount",
    "rest_to_adjust" => "Rest to adjust",
    "adjust_invoice_id" => "Adjust invoice DVN-%s",

    "public_key" => "Public key",
    "private_key" => "Private key",

    "invoice" => "Invoice",
    "invoice_payed" => "Invoice payed",

    "place" => "Place",

    "payed" => "Payed",
    "not_payed" => "Not payed",

    "replenishment" => "Replenishment",

    'account_active' => "Account active",
    "account_blocked" => "Account blocked",
    "warning" => "Warning",
    "active" => "Active",
    "inactif" => "Inactif",

    "waiting" => "Waiting",
    "processing" => "On process",
    "finished" => "Finished",

    "details" => "Details",

    'datatable_trad_link' => '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json',

    'name' => 'Name',

    'informations' => 'Informations',

    "put_inactive" => "Put inactive",
    "put_active" => "Put active",

    "select_tva" => "Select TVA",

    'last_maintenances' => "Last maintenance",
    "maintenance_details" => "Maintenance details",
    "maintenance_add_info_line" => "Maitenance add info line",
    "maintenance" => "Maintenance",

    "supply_warehouse" => "Supply warehouse",
    "choose_this_warehouse" => "Choose this warehouse",

    "maintenance_see_details_for_maintenance_date_truck" => "On maintenance, see details for maintenance date truck <b>%s</b>.",
    "maintenance_status" => "Maintenance status",
    "edit_maintenance_status" => "Edit maintenance status",

    "supply_my_truck" => "Supply my truck",
    "step3_quantity_products" => "Step 3 quantity products",
    "back_to_products_selection" => "Back to products selection",
    "supply_my_truck_step2_products_in_warehouse_name" => "Supply my truck step 2 products in warehouse name <b>%s</b>",
    "select_available_products_in_warehosue" => "Select available products in warehouse.",
    "choose_quentity_to_supply_each_products" => "Choose quantity to supply each products",
    "supply_do_in_3step_step1_label" => "The supply is done in three stages, first choosing the warehouse in which you want to restock.",
    "supply_notice_saved" => "Enter the information for each product, once validated, the products will be saved in the warehouses and you will be redirected to the self-generated invoice.",
    "supply_my_truck_step1_available_warehouses" => "Supply my truck - Step 1 - The available Driv'n'Cook warehouses",
    "payment_cant_success_verify_bank_info" => "Payment could not be completed, please verify your bank information.",
    "if_problem_persit_contact_us" => "If the problem persists, please contact our services.",
    "warning_supply_truck_not_payed" => "By submitting the form, you will generate an invoice. You will have to pay it within the deadlines indicated on the invoice. <br> In which case we will be able to block your access.",
    "drivncook_integrate_stripe_payment_system" => 'Driv\'N\'Cook integrates the online payment solution <a href="https://stripe.com"> Stripe </a>.',
    "if_you_want_active_online_payment_stripe_create" => "If you want to activate online payments, create an account on Stripe, follow the validation steps, and enter your public / private keys below.",
    "contact_us_if_page_not_show" => "Please contact us if this page should not be displayed.",
    "no_truck_assign_for_moment" => "It seems that you have no assigned truck at the moment.",
    "if_you_not_adjust_payed_in_section" => "If you have not yet set your entrance fees, you can set them by going to the section",
    "if_you_already_adjust_dvn_contact_soon" => "If you have already paid your entry fees, a Driv'n'Cook representative will assign you one quickly.",
    "you_really_want_delete_product" => "Are you sure you want to delete this product ?",
    "warehouses_stocks_info_linked" => " As stocks / products are linked between warehouses, the changes will be effective for all warehouses.",
    "confirm_deassign_truck" => "Are you sure you want to unassign this truck?",
    "confirm_put_truck_active" => "Voulez-vous vraiment rendre actif ce camion ?",
    "confirm_put_truck_inactive" => "Are you sure you want to make this truck active?",
    "confirm_invoice_as_payed" => "Confirm that the invoice has been paid?",
    "maintenance_in_process" => "Maintenance is in progress on this truck.",
    "maintenance_in_process_for_your_truck" => "Maintenance is in progress on your truck.",
    "put_truck_in_maintenance" => "Put the truck in maintenance",
    "put_truck_in_maintenance_confirm" => "Are you sure you want to service this truck?",
    "maintenance_date" => "Date of maintenance",
    'name_of_category_must_be_uniq' => 'The category name must be valid..',
    'do_you_really_want_delete_admin' => 'Are you sure you want to delete this administrator ?',
    'do_you_really_want_delete_franchise' => 'Are you sure you want to delete this franchisee? Warning ! This action is irreversible!',
    'do_you_really_want_to_block_franchise_account' => "Are you sure you want to block this franchisee's account?",
    'unblock_franchise_account' => "Unblock the franchisee's account?",
    'start_at' => 'Start date',
    'end_at' => 'End date',
    'begin_register_at' => 'Registration opening date',
    'description' => 'description',
    'event_list' => 'Events list',
    'add_event' => 'Add event',

    'subscribe' => "Subscribe",
    'subscribed' => 'Subscribed',

    'do_you_really_want_delete_customer' => 'Are you sure you want to delete this client?',
    'listing_customer' => 'List of clients',
    'customer' => 'Customer',
    'see_customers' => 'See customers',
    'add_customer' => 'Add customer',
    'edit_customer' => 'Edit customer',
    'invitation_drivncook' => 'Drivncook invitation',
    'read_in_browser' => 'Read in browser',
    'You_are_invited_to_our_event' => 'We invite you to our event',
    'image_event' => 'Event image',

    'titleEmailFR' => 'The Email French title field is empty',
    'textEmailFR' => 'The Email French text field is empty',
    'wysiwygFR' => 'The French text field is empty',
    'titleEmailEN' => 'The English Email title field is empty',
    'textEmailEN' => 'The English Email text field is empty',
    'wysiwygEN' => 'The English text field is empty',
    'errorImage' => 'There was an error with your file',
    'submit' => 'Submit',

    /*  FRONT  */
    /* Header */
    'event' => "Event",
    'contact' => 'Contact',
    'my_franchised_account' => 'My franchised account',
    'my_customer_account' => 'My customer account',

    /* Footer */
    'subscribe_to_the_newsletter' => 'Sign up for the newletters',
    'Soyez tenu au courant de nos dernières promotions' => 'Keep up to date with our latest promotions',
    "DRIV'N'COOK SAS, Société par Actions Simplifiés enregistrée à la chambre de commerce de Paris dont le siège social se trouve au 242 rue du Faubourg Saint Antoine, 75012, Paris." => "DRIV'N'COOK SAS, Simplified Joint Stock Company registered with the Paris Chamber of Commerce, whose registered office is at 242 rue du Faubourg Saint Antoine, 75012, Paris.",
    'SIRET_number' => "Number Siret",
    '242 rue du Faubourg Saint Antoine, 75012, Paris' => '242 rue du Faubourg Saint Antoine, 75012, Paris',
    "commands" => "Commands",

    /* ABOUT page */
    'about' => 'About',
    'getting_to_know_each_other_better_for_a_confident_future' => 'Know yourself better for a future of confidence',
    'our_story' => 'Our history',
    '2018.09.03' => '2018.09.03',
    'the_beginning' => 'The beginning',
    "Début septembre 2018, une grande histoire a commencée, une histoire où l'on apprend toutes les bases nécessaires pour construire un empire tel que Driv'N'Cook." => "In early September 2018, a great story began, a story where we learn all the basics necessary to build an empire such as Driv'N'Cook.",
    "L'infrastructure de nos services, l'aspect marketing et commercial que Driv'N'Cook, toutes ces choses qui ont été apprises et vues en classe au sein de l'ESGI." => "The infrastructure of our services, the marketing and commercial aspect that Driv'N'Cook, all these things that have been learned and seen in class within ESGI.",
    "2019.03.03" => '2019.03.03',
    "the_first_tests" => "The first tests",
    "Des premiers tests ont été effectués, chaque personne travaillant pour Driv'N'Cook a un passé et des projets, nous avons tous commencer en cette date." => "Initial tests have been carried out, each person working for Driv'N'Cook has a past and projects, we all start on this date.",
    '2020.01.16'  => "16.01.2020",
    'Things_are_getting_complicated' => 'Things get complicated',
    "Driv'N'Cook devient la franchise numéro 1 des Food Trucks en europe occidentale, ce qui fait de nous une référence, et qui dit référence, dit pas le droit à l'erreur." => "Driv'N'Cook becomes the number 1 franchise for Food Trucks in Western Europe, which makes us a benchmark, and who says benchmark, says the right to make mistakes.",
    "Nous avons près de 87.000 franchisés partout dans le monde, prêt à vous désservir leurs délicieux plats et vous faire connaître leur culture." => "We have nearly 87,000 franchisees around the world, ready to serve you their delicious dishes and let you know their culture.",
    "Les infrastructures de Driv'N'Cook sont complexes et le moindre bug peut s'avérer très impactant pour le système économique. C'est pour cela que nous avons recruté en masse des développeurs sortant de l'ESGI pour un total estimé de 5.000.000€ d'investissement." => "Driv'N'Cook's infrastructures are complex and the slightest bug can be very impacting on the economic system. This is why we recruited en masse developers leaving the ESGI for an estimated total of € 5,000,000 investment.",
    "Directeur de la section R&D" => "Director of the R&D section",
    "Le modèle économique sur lequel se repose Driv'N'Cook est unique et permet un assouplissement des charges sur le long terme, que ce soit pour nous ou pour les franchisés. Ce qui fait de nous la société de franchise la plus prolifique." => "The economic model on which Driv'N'Cook is based is unique and allows long-term cost easing, whether for us or for franchisees. What makes us the most prolific franchise company.",
    "Directeur marketing et commercial" => "Marketing and sales director",
    'dishes' => 'Dishes',
    "customers" => "Customers",
    'kitchen_hours' => 'Kitchen  hours',

    /* Contact page */
    'contact_us' => 'Contact us',
    'send' => 'Sendr',
    'our_contact_details' => 'Our contact details',
    'head_office' => 'The head office',
    'phone' => 'Phone',
    "Vous souhaitez avoir plus d'informations sur nous ou avez une question pour devenir franchisé ? Vous êtes sur la bonne page" => "Would you like more information about us or have a question to become a franchisee? You are on the right page",

    /* Index */
    'tasty' => 'Tasty',
    'delicious' => 'Delicious',
    'fast' => 'Fast',
    "discovery" => "Discovery",
    "A LA BASE C'ETAIT UN SIMPLE PROJET ANNUEL" => "AT THE BASIS IT WAS A SIMPLE ANNUAL PROJECT",
    "Ce concept assez original nous vient tout droit de l'imagination d'un immense Monsieur, dont nous tairons le noms." => " This rather original concept comes to us straight from the imagination of a huge gentleman, whose names we will not say.",
    "Suite à des mois de travail acharné et à un passage en troisième année, le projet s'est abouti sur le lancement de la société, et aujourd'hui nous sommes la franchise numéro 1 du marché des food trucks en Europe occidentale." => "After months of hard work and a move into the third year, the project resulted in the launch of the company, and today we are the number 1 franchise in the food truck market in Western Europe.",
    "our_events_and_promotions" => "Our events and promotions",
    "Ce que nous pouvons vous proposer" => "What we can offer you",
    "Des choses délicieuses et à bas prix" => "Delicious and cheap stuff",
    'Petit déjeuner' => 'Breakfast',
    'Déjeuner' => 'Lunch',
    'Dînner' => 'Dinner',
    'Dessert' => 'Dessert',
    'Omelette sur un lit de bacon grillé' => 'Omelette sur un lit de bacon grillé',
    'Boissons' => 'Drink',
    "Car on aime tous petit déjeuner à l'anglaise" => "Because we like all English breakfasts",
    "Riz en barquette, sauce champignons du soir" => "Riz en barquette, sauce champignons",
    "Riz en barquette, sauce champignons" => "Rice in a tray, mushroom sauce",
    "Car ça ne coûte pas bien plus cher de bien manger" => "Because it doesn't cost much more to eat well",
    "Glace au coulis de chocolat au napage de chocolat sur un lit de chocolat à la base de chocolat au chocolat" => "Glace au coulis de chocolat au napage de chocolat sur un lit de chocolat à la base de chocolat au chocolat",
    "Car ça ne coûte toujours pas bien plus cher de bien manger" => "Because it still doesn't cost much more to eat well",
    "Car même si ça ne coûte pas bien plus cher de bien manger, il faut savoir se faire plaisir" => "Because even if it doesn't cost much more to eat well, you have to know how to have fun",
    "Un classique qu'on ne peut oublier" => "A classic you can't forget",
    "testimonial" => "Testimony",
    "Ils parlent de nous" => "They talk about us",
    "De passage sur Paris, il me fallait un repas goûtu rapidemment, pour pas très cher sans pour autant y laisser la qualité, je me suis donc tourné vers un Food Truck de Driv'n'Cook, et j'ai été ravi." => "Passing through Paris, I needed a meal tasted quickly, for not very expensive without leaving the quality there, so I turned to a Food Truck from Driv'n'Cook, and I was delighted.",
    "Devenir un franchisé de Drinv'N'Cook a permis a mon entreprise de grandir grace a la qualité des services et la reconnaissance de la marque" => "Becoming a Drinv'N'Cook franchisee has allowed my business to grow thanks to the quality of services and brand recognition",
    "franchisee" => "Franchise",
    "C'était bon." => "It was good.",
    'Cliente' => 'Cliente',
    'our_services' => 'Our services',
    'what_we_propose' => 'What do we offer',
    'a_choice_panel' => 'A choice panel',
    "Chaque Food Truck Driv'n'Cook possède sa propre culture et cuisine ses propres repas, découvrez les variétés du monde." => "Each Food Truck Driv'n'Cook has its own culture and cooks its own meals, discover the varieties of the world.",
    'private_events' => 'Événements privés',
    "Nous organisons régulièrement des événements pour nos franchisés et nos clients, inscrivez-vous à la newletters pour ne rien louper" => "We regularly organize events for our franchisees and our customers, subscribe to the newsletters so you don't miss anything",
    'follow_up_online' => 'Suivi en ligne',
    "Nos infrastructures sont multi-supports, suivez n'importe quelle de vos actions sur nos services en ligne" => "Our infrastructures are multi-support, follow any of your actions on our online services",
    'truck_rentals' => 'Location de camions',
    "Driv'n'Cook vous prête un food trucks totalement aménagé et personnalisable." => "Driv'n'Cook lends you a fully fitted and customizable food truck.",
    "our_gallery" => "Notre gallery",
    "Photos des Food Trucks Driv'n'Cook" => "Photos of Food Trucks Driv'n'Cook",
    "Événement & Promotions" => "Events & Promotions",
    "our_future_events" => "Our next events",
    'Le projet annuel' => 'The annual project',
    "Cette fameuse étape à passer, inscrivez-vous à l'événement pour ne rien louper." => "This famous stage to pass, register for the event so as not to miss anything.",
    'more_information' => 'Find out more',
    /* Event */    "Venez au événements Driv'N'Cook" => "Come to Driv'N'Cook events",
    "Retrouvez tous les événements Driv'N'Cook à venir" => "Find out all the upcoming Driv'N'Cook events",
    /* Camion */
    "Venez Voir les camion de la franchise Driv'N'Cook" => "Come see the Driv'N'Cook franchise trucks",
    'our_food_truck' => 'Our food truck',

    "inscription_success" => "Inscription succes",
    "La date doit être superieur à la date actuelle et inférieur à 5 jours dans le futur, veuillez notez les horaires d'ouverture du food truck." => "The date must be higher than the current date and less than 5 days in the future, please note the opening hours of the food truck.",
];
