<?php

/**
 * Traduction file for english language
 **/

return [

    /* FRONT */
    /* Header */
    'home' => 'Home',
    'event' => "Event",
    'contact' => 'Contact',
    'my_franchised_account' => 'My franchised account',
    'my_customer_account' => 'My customer account',
    /* Footer */
    'subscribe_to_the_newsletter' => 'Subscribe to the newsletter',
    'Soyez tenu au courant de nos dernières promotions' => 'Keep up to date with our latest promotions',
    "DRIV'N'COOK SAS, Société par Actions Simplifiés enregistrée à la chambre de commerce de Paris dont le siège social se trouve au 242 rue du Faubourg Saint Antoine, 75012, Paris." => "DRIV'N'COOK SAS, a Société par Actions Simplifiés registered with the Paris Chamber of Commerce, having its registered office at 242 rue du Faubourg Saint Antoine, 75012, Paris.",
    'SIRET_number' => "Numéro de siret",
    '242 rue du Faubourg Saint Antoine, 75012, Paris' => '242 rue du Faubourg Saint Antoine, 75012, Paris',

    /* ABOUT page */
    'about' => 'About',
    'getting_to_know_each_other_better_for_a_confident_future' => 'Getting to know each other better for a confident future',
    'our_story' => 'Our story',
    '2018.09.03' => '2018.09.03',
    'the_beginning' => 'The Beginning',
    "Début septembre 2018, une grande histoire a commencée, une histoire où l'on apprend toutes les bases nécessaires pour construire un empire tel que Driv'N'Cook." => "At the beginning of September 2018, a great story began, a story where we learn all the basics needed to build an empire like Driv'N'Cook.",
    "L'infrastructure de nos services, l'aspect marketing et commercial que Driv'N'Cook, toutes ces choses qui ont été apprises et vues en classe au sein de l'ESGI." => "The infrastructure of our services, the marketing and sales aspect of Driv'N'Cook, all things that have been learned and seen in the classroom at ESGI.",
    "2019.03.03" => "2019.03.03",
    "the_first_tests" => "The first tests",
    "Des premiers tests ont été effectués, chaque personne travaillant pour Driv'N'Cook a un passé et des projets, nous avons tous commencer en cette date." => "First tests have been carried out, everyone working for Driv'N'Cook has a background and projects, we all started on this date.",
    '2020.01.16'  => "2020.01.16",
    'Things_are_getting_complicated' => 'Things are getting complicated',
    "Driv'N'Cook devient la franchise numéro 1 des Food Trucks en europe occidentale, ce qui fait de nous une référence, et qui dit référence, dit pas le droit à l'erreur." => "Driv'N'Cook has become the number 1 franchise of food trucks in Western Europe, which makes us a reference, and a reference means no room for error.",
    "Nous avons près de 87.000 franchisés partout dans le monde, prêt à vous désservir leurs délicieux plats et vous faire connaître leur culture." => "We have nearly 87,000 franchisees around the world, ready to serve you their delicious dishes and introduce you to their culture.",
    "Les infrastructures de Driv'N'Cook sont complexes et le moindre bug peut s'avérer très impactant pour le système économique. C'est pour cela que nous avons recruté en masse des développeurs sortant de l'ESGI pour un total estimé de 5.000.000€ d'investissement." => "Driv'N'Cook's infrastructure is complex and the slightest bug can have a major impact on the business system. That's why we've recruited a large number of developers from the ESGI for an estimated €5,000,000 in investment.",
    "Directeur de la section R&D" => "Director of the R&D section",
    "Le modèle économique sur lequel se repose Driv'N'Cook est unique et permet un assouplissement des charges sur le long terme, que ce soit pour nous ou pour les franchisés. Ce qui fait de nous la société de franchise la plus prolifique." => "The business model on which Driv'N'Cook is based is unique and allows for a long-term easing of costs, both for us and for our franchisees. This makes us the most prolific franchise company.",
    "Marketing and Sales Director" => "Marketing and Sales Director",
    'dishes' => 'dishes',
    'customers' => 'customers',
    'customer' => 'customer',
    'kitchen_hours' => 'kitchen hours',

    /* Contact page */
    'contact_us' => 'Contact Us',
    'send' => 'Send',
    'our_contact_details' => 'Our contact details',
    'head_office' => 'Head Office',
    'phone' => 'Phone',
    "Vous souhaitez avoir plus d'informations sur nous ou avez une question pour devenir franchisé ? Vous êtes sur la bonne page" => "Would you like more information about us or have a question about becoming a franchisee? You are on the good page",

    /* Index */
    'tasty' => 'Tasty',
    'delicious' => 'Delicious',
    'fast' => 'Fast',
    'discovery' => "Discovery",
    "A LA BASE C'ETAIT UN SIMPLE PROJET ANNUEL" => 'IT STARTED OUT AS A SIMPLE ANNUAL PROJECT.',
    "Ce concept assez original nous vient tout droit de l'imagination d'un immense Monsieur, dont nous tairons le noms." => "This rather original concept comes straight from the imagination of an immense gentleman, whose name we will not mention.",
    "Suite à des mois de travail acharné et à un passage en troisième année, le projet s'est abouti sur le lancement de la société, et aujourd'hui nous sommes la franchise numéro 1 du marché des food trucks en Europe occidentale." => "After months of hard work and a passage into the third year, the project culminated in the launch of the company, and today we are the number one franchise in the food truck market in Western Europe.",
    "our_events_and_promotions" => "Our events and promotions",
    "Ce que nous pouvons vous proposer" => "What we can offer to you",
    "Des choses délicieuses et à bas prix" => "Delicious, low-cost things",
    'Petit déjeuner' => 'Breakfast',
    'Déjeuner' => 'Lunch',
    'Dînner' => 'Dinner',
    'Dessert' => 'Dessert',
    'Boissons' => 'Beverages',
    'Omelette sur un lit de bacon grillé' => 'Omelet on a bed of grilled bacon',
    "Car on aime tous petit déjeuner à l'anglaise" => "Cause we all love a good English breakfast",
    "Riz en barquette, sauce champignons du soir" => "Rice in trays with mushroom sauce",
    "Riz en barquette, sauce champignons" => "Rice in trays with mushroom sauce",
    "Car ça ne coûte pas bien plus cher de bien manger" => "Cause it doesn't cost much more to eat right...",
    "Car ça ne coûte toujours pas bien plus cher de bien manger" => "Car ça ne coûte toujours pas bien plus cher de bien manger",
    "Glace au coulis de chocolatw au napage de chocolat sur un lit de chocolat à la base de chocolat au chocolat" => "Ice cream with chocolate sauce with chocolate napage on a base of chocolate",
    "Car même si ça ne coûte pas bien plus cher de bien manger, il faut savoir se faire plaisir" => "Because even if it doesn't cost much more to eat well, you have to know how to treat yourself...",
    "Un classique qu'on ne peut oublier" => "A classic that can't be forgotten",
    "testimonial" => "Testimonial",
    "Ils parlent de nous" => "They talk about us",
    "De passage sur Paris, il me fallait un repas goûtu rapidemment, pour pas très cher sans pour autant y laisser la qualité, je me suis donc tourné vers un Food Truck de Driv'n'Cook, et j'ai été ravi." => "Passing through Paris, I needed a quick and tasty meal, not very expensive but not too expensive, so I turned to a Food Truck from Driv'n'Cook, and I was delighted.",
    "Devenir un franchisé de Drinv'N'Cook a permis a mon entreprise de grandir grace a la qualité des services et la reconnaissance de la marque" => "Becoming a Drinv'N'Cook franchisee has allowed my business to grow because of the quality of service and brand recognition.",
    'franchisee' => 'Franchisee',
    "C'était bon." => "That was good.",
    'Cliente' => 'client',
    'our_services' => 'Our services',
    'what_we_propose' => "What we propose",
    'a_choice_panel' => 'A choice panel',
    "Chaque Food Truck Driv'n'Cook possède sa propre culture et cuisine ses propres repas, découvrez les variétés du monde." => "Each Food Truck Driv'n'Cook has its own culture and cooks its own meals, discover the varieties of the world.",
    'private_events' => 'Private events',
    'Nous organisons régulièrement des événements pour nos franchisés et nos clients, inscrivez-vous à la newletters pour ne rien louper' => "We regularly organize events for our franchisees and customers, sign up for our newsletter to make sure you don't miss out on anything",
    'follow_up_online' => 'Follow up online',
    "Nos infrastructures sont multi-supports, suivez n'importe quelle de vos actions sur nos services en ligne" => 'Our infrastructures are multi-support, follow any of your actions on our online services',
    "truck_rentals" => "Truck Rentals",
    "Driv'n'Cook vous prête un food trucks totalement aménagé et personnalisable." => "Driv'n'Cook lends you a fully equipped and customizable food truck.",
    "our_gallery" => "Our gallery",
    "Photos des Food Trucks Driv'n'Cook" => "Pictures of Driv'n'Cook Food Trucks",
    "Événement & Promotions" => "Events & Promotions",
    "our_future_events" => "Our future events",
    "Le projet annuel" => 'The annual project',
    "Cette fameuse étape à passer, inscrivez-vous à l'événement pour ne rien louper." => "This famous step to pass, register for the event so you don't miss anything.",
    "more_information" => "More information",
    /* Event */
    "Venez au événements Driv'N'Cook" => "Come to Driv'N'Cook events",
    "Retrouvez tous les événements Driv'N'Cook à venir" => "Find out all the upcoming Driv'N'Cook events",
    /* Camion */
    "trucks" => "Trucks",
    "Venez Voir les camion de la franchise Driv'N'Cook" => "Come see the trucks of the Driv'N'Cook franchise",
    'our_food_truck' => 'Our Food Trucks',

    "inscription_success" => "Successful registration",
    "La date doit être superieur a la date actuel et inférieure a 5 jours dans le future" => "The date must be greater than the current date and less than 5 days in the future",
];