<?php

/**
 * Fichier de traduction dans la langue française
 **/

return [

    "error" => "Erreur",
    '404_page_not_found' => '404 pas non trouvée',
    'an_error_occured' => 'Une erreur est survenue',
    'page_not_found' => 'La page demandée n\'a pas été trouvée',
    'an_internal_error_occured_back_soon' => 'Une erreur interne est survenue. <br> Veuillez renouveler votre requête ultérieurement.',


    'drivncook_home' => 'Accueil Driv\'N\'Cook',
    'home' => 'Accueil',
    'back' => 'Retour',
    "back_to_truck" => "Retour au camion",
    "back_to_warehouse" => "Retour à l'entrepôt",
    "back_to_warehouses" => "Retour aux entrepôts",

    'login' => 'Connexion',
    'logout' => 'Déconnexion',
    'login_to_my_admin_account' => 'Connexion à mon compte administrateur',
    'login_to_my_franchise_account' => 'Connexion à mon compte franchisé',

    'email' => 'Email',
    'password' => 'Mot de passe',
    'confirm_password' => 'Confirmez le mot de passe',
    'firstname' => 'Prénom',
    'lastname' => 'Nom',
    'society_name' => 'Nom de société',
    'siret' => 'Siret',
    'manager' => "Gérant",
    "status" => "Statut",
    'phone_number' => 'Numéro de téléphone',
    'address' => 'Adresse',
    'city' => 'Ville',
    'postal_code' => 'Code postal',
    'state' => 'Région',
    'country' => 'Pays',

    "franchise_space" => "Espace franchisé",

    'account_not_found' => 'Compte introuvable',
    'assign_to_truck' => 'Assigner à un camion',
    "assign_truck_immat_to_user" => "Assigner le camion %s à un utilisateur",
    'select_truck' => 'Selectionner un camion',
    'available_since' => "Disponible depuis le",
    "available" => "Disponible",

    'administration' => 'Administration',
    "sidebar_administration" => "ADMINISTRATION",
    'my_account' => 'Mon compte',
    "edit_my_account" => "Modifier mon compte",
    'my_truck' => "Mon camion",

    'sidebar_service' => 'SERVICES',
    "sidebar_supply" => "Approvisionnement",
    "promotions" => "Promotions",
    "my_promotions" => "Mes promotions",
    "add_promotion" => "Ajouter une promotion",
    "sidebar_settings" => "PARAMETRES",
    "online_payments" => "Paiements en ligne",
    "promotion" => "Promotion",
    "menu" => "Menu",
    "menus" => "Menus",
    "my_menus" => "Mes menus",
    "add_menu" => "Ajouter un menu",
    "assign_to" => "Assigné à",
    "assign" => "Assigné",
    "deassign" => "Déassigner",
    "assign_truck_to_user" => "Assigner le camion à un franchisé",

    'sidebar_franchise' => 'FRANCHISES',
    'franchises' => 'Franchises',
    'see_franchises' => 'Voir les franchisés',
    'add_franchise' => 'Ajouter un franchisé',
    'edit_franchise' => 'Editer un franchisé',
    'select_franchise' => 'Selectionner un franchisé',
    'drivncook_franchises' => 'Les franchisés Driv\'n\'Cook',

    'trucks_drivncook' => 'Les camions Driv\'n\'Cook',
    'trucks' => 'Camions',
    'truck' => 'Camion',
    'see_trucks' => 'Voir les camions',
    'add_truck' => 'Ajouter un camion',

    'immatriculation' => 'Immatriculation',
    'assign_truck_to_franchise' => 'Assigner le camion à un franchisé',

    'administrators' => 'Administrateurs',
    'see_administrators' => 'Voir les administrateurs',
    'add_administrator' => 'Ajouter un administrateur',
    'edit_administrator' => 'Editer un administrateur',
    'drivncook_administrators' => 'Les administrateurs Driv\'n\'Cook',

    'warehouses' => 'Entrepôts',
    'warehouses_drivncook' => "Les entrepôts Driv'N'Cook",
    'warehouse' => 'Entrepôt',
    'see_warehouses' => 'Voir les entrepôts',
    'add_warehouse' => 'Ajouter un entrepôt',
    "edit_warehouse_name" => "Modifier l'entrepôt de <b>%s</b>",
    'warehouse_location' => 'Localisation de l\'entrepôt',

    "edit_product_name" => "Modifier le produit <b>%s</b>",

    'location' => "Localisation",

    "warehouse_name" => "Entrepôt de %s",

    'stocks' => 'Stocks',
    "total_of_products" => "Total de produits",
    "total_of_quantity_products" => "Quantité totale",

    "view_stock_of_warehouse_name" => "Visualisation du stock de l'entrepôt de <b>%s</b>",

    'categories' => 'Catégories',
    "category" => "Catégorie",
    'the_categories' => 'Les catégories',
    'create_category' => 'Créer une catégorie',

    'category_name' => 'Nom de la catégorie',
    'link_to_parent_category' => 'Relier à une catégorie parente',
    'select_category' => 'Selectionner une catégorie',

    "edit_parent_category" => "Modifier la catégorie parente",
    "edit_category" => "Modifier la catégorie",

    "category_name_must_uniq_label" => "Nom de la catégorie (doit être unique)",

    "parents_categories" => "Catégories Parentes",

    'facturation' => 'Facturation',
    "my_invoices_received" => "Mes factures reçues",
    'invoices_received' => 'Factures reçues',
    'invoices_issued' => 'Factures émises',
    'add_invoice' => 'Ajouter une facture',
    'internal_invoice' => "Facture interne",
    'external_invoice' => "Facture externe",
    "settled" => "Réglée",

    "received_invoices_from_drivncook" => "Les factures reçues de Driv'n'Cook",
    "issued_invoices_from_drivncook" => "Les factures émises de Driv'n'Cook",

    "transmitter" => "Emetteur",

    'stats' => 'Statistiques',

    'turnover_in' => 'Chiffres d\'affaires en %s',

    "products_categories" => "Catégories de produits",
    "products_categories_drivncook" => "Les catégories de produits Driv'n'Cook",

    "product_name" => "Nom du produit",

    "quantity_to_supply" => "Quantité à approvisionner",
    "in_euros" => "(en €)",
    "in_percentage" => "(en %%)",

    "provider_name" => "Nom du fournisseur",
    "provider_address" => "Adresse du fournisseur",
    "provider_postal_code" => "Code postal du fournisseur",
    "provider_city" => "Ville du fournisseur",

    'edit' => 'Editer',
    'add' => 'Ajouter',
    'delete' => 'Supprimer',
    'see' => 'Voir',
    'save' => 'Enregistrer',
    'action' => 'Action',
    'created_at' => 'Crée le',
    'received_at' => "Reçue le",
    "adjust" => "Régler",
    'actual' => 'Actuel',
    'block' => "Bloquer",
    "supply" => "Approvisionner",
    "unblock" => "Débloquer",
    "yes" => "Oui",
    "no" => "Non",
    "product" => "Produit",
    "quantity" => "Quantité",
    "price_unit" => "Prix unitaire",
    "price_resale" => "Prix de revente",
    "tva" => "TVA",
    "subtotal" => "Sous-total",
    "total_ht" => "Total HT",
    "total_ttc" => "Total TTC",
    "longitude" => "Longitude",
    "latitude" => "Latitude",
    "step1" => "Etape 1",
    "step2" => "Etape 2",
    "step3" => "Etape 3",
    "next_step" => "Etape suivante",
    "remains" => "restants",
    "back_to_step1" => "Retour à l'étape 1",

    "print" => "Imprimer",
    "import_an_external_invoice" => "Importer une facture externe",

    "available_products" => "Produits disponibles",
    "selected_products" => "Produits selectionés",
    "products" => "Produits",
    "no_products" => "Aucun produit",
    "total_product_filter" => "Total de produit : {0}",

    "supply_warehouse_of_name" => "Approvisionnement de l'entrepôt de <b>%s</b>",
    "select_products_to_supply_or_add_it" => " Selectionner des produits à réapprovisionner ou ajoutez-en.",
    "product_are_not_onlist_add_it" => "Le produit ne figure pas sur la liste ? Ajoutez-le ici",

    "link_an_external_invoice_in_internal_invoice" => "Relier une facture externe à Driv'n'Cook à une facture interne auto-générée par le système de facturation.",
    "download" => "Télécharger",
    "download_external_invoice" => "Télécharger la facture externe",
    "delete_external_invoice" => "Supprimer la facture externe",
    "delete_external_invoice_confirm" => "Voulez-vous vraiment supprimer la facture externe liée à cette facture ?",
    "date" => "Date",
    "import" => "Importer",
    "validate" => "Valider",
    "close" => "Fermer",

    "adjust_invoice" => "Régler une facture",
    "back_to_invoice" => "Retour à la facture",
    "payed_the_amount" => "Régler le montent",
    "rest_to_adjust" => "Reste à payer",
    "adjust_invoice_id" => "Régler la facture DVN-%s",

    "public_key" => "Clé publique",
    "private_key" => "Clé privée",

    "invoice" => "Facture",
    "invoice_payed" => "Facture payée",

    "place" => "Lieu",

    "payed" => "Payée",
    "not_payed" => "Non payée",

    "replenishment" => "Réapprovisionnnement",

    'account_active' => "Compte activé",
    "account_blocked" => "Compte bloqué",
    "warning" => "Attention",
    "active" => "Actif",
    "inactif" => "Inactif",

    "waiting" => "En attente",
    "processing" => "En cours",
    "finished" => "Terminé",

    "details" => "Détails",

    'datatable_trad_link' => '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json',

    'name' => 'Nom',

    'informations' => 'Informations',

    "put_inactive" => "Rendre inactif",
    "put_active" => "Rendre actif",

    "select_tva" => "Selectionner un taux de TVA",

    'last_maintenances' => "Les dernières maintenances",
    "maintenance_details" => "Détails de maintenance",
    "maintenance_add_info_line" => "Ajouter une ligne d'information",
    "maintenance" => "Maintenance",

    "supply_warehouse" => "Approvisionner l'entrepôt",
    "choose_this_warehouse" => "Choisir cet entrepôt",

    "maintenance_see_details_for_maintenance_date_truck" => "Visionnez les détails de la maintenance N°%s du %s pour le camion <b>%s</b>.",
    "maintenance_status" => "Statut de la maintenance",
    "edit_maintenance_status" => "Modifier le statut de la maintenance",

    "supply_my_truck" => "Approvisionner mon camion",
    "step3_quantity_products" => "Etape 3 - Quantité de produit",
    "back_to_products_selection" => "Retour à la sélection des produits",
    "supply_my_truck_step2_products_in_warehouse_name" => "Approvisionner mon camion - Etape 2 - Les produits disponibles dans l'entrepôt de <b>%s</b>",
    "select_available_products_in_warehosue" => "Selectionner les produits disponible dans notre entrepôt.",
    "choose_quentity_to_supply_each_products" => "Choisissez une quantité à approvisionner pour chaque produit",
    "supply_do_in_3step_step1_label" => "L'approvisionnement se fait en trois étapes, choisissez en premier temps l'entrepôt dans lequel vous souhaitez vous réapprovisionner.",
    "supply_notice_saved" => "Saisissez les informations pour chaque produit, une fois validé, les produits seront enregistrés dans les entrepôts et vous serez redirigé vers la facture auto-générée.",
    "supply_my_truck_step1_available_warehouses" => "Approvisionner mon camion - Etape 1 - Les entrepôts disponibles Driv'n'Cook",
    "payment_cant_success_verify_bank_info" => "Le paiement n'a pas pu aboutir, veuillez vérifier vos informations bancaires.",
    "if_problem_persit_contact_us" => "Si le problème persiste, veuillez contacter nos services.",
    "warning_supply_truck_not_payed" => "En soumettant le formulaire, vous génererez une facture. Vous serez dans l'obligation de la régler dans les délais inscrits sur la facture. <br>Auxquels cas nous serons en mesure de bloquer vos accès.",
    "drivncook_integrate_stripe_payment_system" => 'Driv\'N\'Cook intègre la solution de paiement en ligne <a href="https://stripe.com">Stripe</a>.',
    "if_you_want_active_online_payment_stripe_create" => "Si vous souhaitez activer les paiements en ligne, créez-vous un compte sur Stripe, suivez les étapes de validation, et renseignez vos clés publique / privée ci-dessous.",
    "contact_us_if_page_not_show" => "Veuillez nous contactez si cette page ne devrait pas s'afficher.",
    "no_truck_assign_for_moment" => "Il semblerait que vous n'ayez aucun camion d'assigné pour le moment.",
    "if_you_not_adjust_payed_in_section" => "Si vous n'avez pas encore réglé vos droits d'entrées, vous pouvez les régler en allant dans la section",
    "if_you_already_adjust_dvn_contact_soon" => "Si vous avez déjà réglé vos droits d'entées, un représentant Driv'n'Cook vous en assignera un rapidemment.",
    "you_really_want_delete_product" => "Voulez-vous vraiment supprimer ce produit ?",
    "warehouses_stocks_info_linked" => "Les stocks / produits étant liés entre les entrepôts, les modifications seront effectives pour tous les entrepôts.",
    "confirm_deassign_truck" => "Voulez-vous vraiment déassigner ce camion ?",
    "confirm_put_truck_active" => "Voulez-vous vraiment rendre actif ce camion ?",
    "confirm_put_truck_inactive" => "Voulez-vous vraiment rendre inactif ce camion ?",
    "confirm_invoice_as_payed" => "Confirmez que la facture a été payée ?",
    "maintenance_in_process" => "Une maintenance est en cours sur ce camion.",
    "maintenance_in_process_for_your_truck" => "Une maintenance est en cours sur votre camion.",
    "put_truck_in_maintenance" => "Mettre le camion en maintenance",
    "put_truck_in_maintenance_confirm" => "Voulez-vous vraiment mettre en maintenance ce camion ?",
    "maintenance_date" => "Date de mise en maintenance",
    'name_of_category_must_be_uniq' => 'Le nom de la catégorie doit être valide.',
    'do_you_really_want_delete_admin' => 'Voulez-vous vraiment supprimer cet administrateur ?',
    'do_you_really_want_delete_franchise' => 'Voulez-vous vraiment supprimer ce franchisé ? Attention ! Cette action est irréversible !',
    'do_you_really_want_to_block_franchise_account' => "Voulez-vous vraiment bloquer le compte de ce franchisé ?",
    'unblock_franchise_account' => "Débloquer le compte du franchisé ?",
    'add_menu' => 'Ajouter un menu',
    'event' => 'Event',
    'start_at' => 'Date de début',
    'end_at' => 'Date de fin',
    'begin_register_at' => 'Date d\'ouverture des inscrpitions',
    'description' => 'description',
    'created_at' => 'Date de création',
    'event_list' => 'Listes des events',
    'add_event' => 'Ajouter un event',

    'subscribe' => "S'inscrire",
    'subscribed' => 'inscrit',

    'do_you_really_want_delete_customer' => 'Voulez-vous vraiment supprimer ce client ?',
    'listing_customer' => 'Liste des clients',
    'customer' => 'Client',
    'see_customers' => 'Voir les clients',
    'add_customer' => 'Ajouté un client',
    'edit_customer' => 'Edité un client',
    'invitation_drivncook' => 'Invitation Drivncook',
    'read_in_browser' => 'Lire dans votre navigateur',
    'You_are_invited_to_our_event' => 'Nous vous invitons a notre événement',
    'image_event' => 'Image de l\'événement',

    'titleEmailFR' => 'Le champ titre Email Français est vide',
    'textEmailFR' => 'Le champ text Email Français est vide',
    'wysiwygFR' => 'Le champ text Français est vide',
    'titleEmailEN' => 'Le champ titre Email Anglais est vide',
    'textEmailEN' => 'Le champ text Email Anglais est vide',
    'wysiwygEN' => 'Le champ text Anglais est vide',
    'errorImage' => 'Il y eu une erreur avec votre fichier',
    'submit' => 'envoyer',

    
    
    /*  FRONT  */
    /* Header */
    'home' => 'Acceuil',
    'event' => "Événement",
    'contact' => 'Contact',
    'my_franchised_account' => 'Mon espace franchisé',
    'my_customer_account' => 'Mon compte client',
    
    /* Footer */
    'subscribe_to_the_newsletter' => 'Inscrivez-vous à la newletters',
    'Soyez tenu au courant de nos dernières promotions' => 'Soyez tenu au courant de nos dernières promotions',
    "DRIV'N'COOK SAS, Société par Actions Simplifiés enregistrée à la chambre de commerce de Paris dont le siège social se trouve au 242 rue du Faubourg Saint Antoine, 75012, Paris." => "DRIV'N'COOK SAS, Société par Actions Simplifiés enregistrée à la chambre de commerce de Paris dont le siège social se trouve au 242 rue du Faubourg Saint Antoine, 75012, Paris.",
    'SIRET_number' => "Numéro de siret",
    '242 rue du Faubourg Saint Antoine, 75012, Paris' => '242 rue du Faubourg Saint Antoine, 75012, Paris',

    /* ABOUT page */
    'about' => 'A propos',
    'getting_to_know_each_other_better_for_a_confident_future' => 'Mieux se connaître pour un avenir de confiance',
    'our_story' => 'Notre histoire',
    '2018.09.03' => '03.09.2018',
    'the_beginning' => 'Le commecement',
    "Début septembre 2018, une grande histoire a commencée, une histoire où l'on apprend toutes les bases nécessaires pour construire un empire tel que Driv'N'Cook." => "Début septembre 2018, une grande histoire a commencée, une histoire où l'on apprend toutes les bases nécessaires pour construire un empire tel que Driv'N'Cook.",
    "L'infrastructure de nos services, l'aspect marketing et commercial que Driv'N'Cook, toutes ces choses qui ont été apprises et vues en classe au sein de l'ESGI." => "L'infrastructure de nos services, l'aspect marketing et commercial que Driv'N'Cook, toutes ces choses qui ont été apprises et vues en classe au sein de l'ESGI.",
    "2019.03.03" => '03.03.2019',
    "the_first_tests" => "Les premiers tests",
    "Des premiers tests ont été effectués, chaque personne travaillant pour Driv'N'Cook a un passé et des projets, nous avons tous commencer en cette date." => "Des premiers tests ont été effectués, chaque personne travaillant pour Driv'N'Cook a un passé et des projets, nous avons tous commencer en cette date.",
    '2020.01.16'  => "16.01.2020",
    'Things_are_getting_complicated' => 'Les choses se compliquent',
    "Driv'N'Cook devient la franchise numéro 1 des Food Trucks en europe occidentale, ce qui fait de nous une référence, et qui dit référence, dit pas le droit à l'erreur." => "Driv'N'Cook devient la franchise numéro 1 des Food Trucks en europe occidentale, ce qui fait de nous une référence, et qui dit référence, dit pas le droit à l'erreur.",
    "Nous avons près de 87.000 franchisés partout dans le monde, prêt à vous désservir leurs délicieux plats et vous faire connaître leur culture." => "Nous avons près de 87.000 franchisés partout dans le monde, prêt à vous désservir leurs délicieux plats et vous faire connaître leur culture.",
    "Les infrastructures de Driv'N'Cook sont complexes et le moindre bug peut s'avérer très impactant pour le système économique. C'est pour cela que nous avons recruté en masse des développeurs sortant de l'ESGI pour un total estimé de 5.000.000€ d'investissement." => "Les infrastructures de Driv'N'Cook sont complexes et le moindre bug peut s'avérer très impactant pour le système économique. C'est pour cela que nous avons recruté en masse des développeurs sortant de l'ESGI pour un total estimé de 5.000.000€ d'investissement.",
    "Directeur de la section R&D" => "Directeur de la section R&D",
    "Le modèle économique sur lequel se repose Driv'N'Cook est unique et permet un assouplissement des charges sur le long terme, que ce soit pour nous ou pour les franchisés. Ce qui fait de nous la société de franchise la plus prolifique." => "Le modèle économique sur lequel se repose Driv'N'Cook est unique et permet un assouplissement des charges sur le long terme, que ce soit pour nous ou pour les franchisés. Ce qui fait de nous la société de franchise la plus prolifique.",
    "Directeur marketing et commercial" => "Directeur marketing et commercial",
    'dishes' => 'plats',
    "customers" => "clients",
    'kitchen_hours' => 'heures en cuisine',

    /* Contact page */
    'contact_us' => 'Nous contacter',
    'send' => 'Envoyer',
    'our_contact_details' => 'Nos coordonnées',
    'head_office' => 'Siège social',
    'phone' => 'Téléphone',
    "Vous souhaitez avoir plus d'informations sur nous ou avez une question pour devenir franchisé ? Vous êtes sur la bonne page" => "Vous souhaitez avoir plus d'informations sur nous ou avez une question pour devenir franchisé ? Vous êtes sur la bonne page",
    
    /* Index */
    'tasty' => 'Savoureux',
    'delicious' => 'Délicieux',
    'fast' => 'Rapide',
    "discovery" => "Découverte",
    "A LA BASE C'ETAIT UN SIMPLE PROJET ANNUEL" => "A LA BASE C'ETAIT UN SIMPLE PROJET ANNUEL",
    "Ce concept assez original nous vient tout droit de l'imagination d'un immense Monsieur, dont nous tairons le noms." => " Ce concept assez original nous vient tout droit de l'imagination d'un immense Monsieur, dont nous tairons le noms.",
    "Suite à des mois de travail acharné et à un passage en troisième année, le projet s'est abouti sur le lancement de la société, et aujourd'hui nous sommes la franchise numéro 1 du marché des food trucks en Europe occidentale." => "Suite à des mois de travail acharné et à un passage en troisième année, le projet s'est abouti sur le lancement de la société, et aujourd'hui nous sommes la franchise numéro 1 du marché des food trucks en Europe occidentale.",
    "our_events_and_promotions" => "Nos évènements et promotions",
    "Ce que nous pouvons vous proposer" => "Ce que nous pouvons vous proposer",
    "Des choses délicieuses et à bas prix" => "Des choses délicieuses et à bas prix",
    'Petit déjeuner' => 'Breakfast',
    'Déjeuner' => 'Lunch',
    'Dînner' => 'Dinner',
    'Dessert' => 'Dessert',
    'Boissons' => 'Beverages',
    'Omelette sur un lit de bacon grillé' => 'Omelette sur un lit de bacon grillé',
    "Car on aime tous petit déjeuner à l'anglaise" => "Car on aime tous petit déjeuner à l'anglaise",
    "Riz en barquette, sauce champignons du soir" => "Riz en barquette, sauce champignons",
    "Riz en barquette, sauce champignons" => "Riz en barquette, sauce champignons",
    "Car ça ne coûte pas bien plus cher de bien manger" => "Car ça ne coûte pas bien plus cher de bien manger",
    "Car ça ne coûte toujours pas bien plus cher de bien manger" => "Car ça ne coûte toujours pas bien plus cher de bien manger",
    "Glace au coulis de chocolat au napage de chocolat sur un lit de chocolat à la base de chocolat au chocolat" => "Glace au coulis de chocolat au napage de chocolat sur un lit de chocolat à la base de chocolat au chocolat",
    "Car même si ça ne coûte pas bien plus cher de bien manger, il faut savoir se faire plaisir" => "Car même si ça ne coûte pas bien plus cher de bien manger, il faut savoir se faire plaisir",
    "Un classique qu'on ne peut oublier" => "Un classique qu'on ne peut oublier",
    "testimonial" => "Témoignage",
    "Ils parlent de nous" => "Ils parlent de nous",
    "De passage sur Paris, il me fallait un repas goûtu rapidemment, pour pas très cher sans pour autant y laisser la qualité, je me suis donc tourné vers un Food Truck de Driv'n'Cook, et j'ai été ravi." => "De passage sur Paris, il me fallait un repas goûtu rapidemment, pour pas très cher sans pour autant y laisser la qualité, je me suis donc tourné vers un Food Truck de Driv'n'Cook, et j'ai été ravi.",
    "Devenir un franchisé de Drinv'N'Cook a permis a mon entreprise de grandir grace a la qualité des services et la reconnaissance de la marque" => "Devenir un franchisé de Drinv'N'Cook a permis a mon entreprise de grandir grace a la qualité des services et la reconnaissance de la marque",
    "franchisee" => "Franchisé",
    "C'était bon." => "C'était bon.",
    'Cliente' => 'Cliente',
    'our_services' => 'Nos services',
    'what_we_propose' => 'Que proposons-nous',
    'a_choice_panel' => 'Un panel de choix',
    "Chaque Food Truck Driv'n'Cook possède sa propre culture et cuisine ses propres repas, découvrez les variétés du monde." => "Chaque Food Truck Driv'n'Cook possède sa propre culture et cuisine ses propres repas, découvrez les variétés du monde.",
    'private_events' => 'Événements privés',
    "Nous organisons régulièrement des événements pour nos franchisés et nos clients, inscrivez-vous à la newletters pour ne rien louper" => "Nous organisons régulièrement des événements pour nos franchisés et nos clients, inscrivez-vous à la newletters pour ne rien louper",
    'follow_up_online' => 'Suivi en ligne',
    "Nos infrastructures sont multi-supports, suivez n'importe quelle de vos actions sur nos services en ligne" => "Nos infrastructures sont multi-supports, suivez n'importe quelle de vos actions sur nos services en ligne",
    'truck_rentals' => 'Location de camions',
    "Driv'n'Cook vous prête un food trucks totalement aménagé et personnalisable." => "Driv'n'Cook vous prête un food trucks totalement aménagé et personnalisable.",
    "our_gallery" => "Notre gallery",
    "Photos des Food Trucks Driv'n'Cook" => "Photos des Food Trucks Driv'n'Cook",
    "Événement & Promotions" => "Événement & Promotions",
    "our_future_events" => "Nos prochains événements",
    'Le projet annuel' => 'Le projet annuel',
    "Cette fameuse étape à passer, inscrivez-vous à l'événement pour ne rien louper." => "Cette fameuse étape à passer, inscrivez-vous à l'événement pour ne rien louper.",
    'more_information' => 'En savoir plus',
];
