<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('franchise_space'); ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/dist/css/adminlte.css">
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><?= \Core\Language::get('home'); ?></li>
                            <li class="breadcrumb-item active">Commandes</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>


        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Mes commandes</h3>
                        </div>
                        <div class="card-body">

                            <nav>
                                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                    <a class="nav-item nav-link active" id="nav-status-2-tab" data-toggle="tab" href="#nav-status-2" role="tab" aria-controls="nav-status-2" aria-selected="true">En traitement</a>
                                    <a class="nav-item nav-link" id="nav-status-1-tab" data-toggle="tab" href="#nav-status-1" role="tab" aria-controls="nav-status-1" aria-selected="false">Non traîtée</a>
                                    <a class="nav-item nav-link" id="nav-status-3-tab" data-toggle="tab" href="#nav-status-3" role="tab" aria-controls="nav-status-3" aria-selected="false">Terminée</a>
                                    <a class="nav-item nav-link" id="nav-status-4-tab" data-toggle="tab" href="#nav-status-4" role="tab" aria-controls="nav-status-4" aria-selected="false">Annulée</a>
                                </div>
                            </nav>
                            <div class="tab-content p-2" id="nav-tabContent">
                                <div class="tab-pane fade show active" id="nav-status-2" role="tabpanel" aria-labelledby="nav-home-tab">
                                    <table id="commands_status_2" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Informations</th>
                                            <th>Date de récupération souhaitée</th>
                                            <th>Date de commande</th>
                                            <th>Total à facturer</th>
                                            <th>Promotion</th>
                                            <th><?= \Core\Language::get('action') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($orders['status_2'] as $order) : $total = 0; ?>
                                                <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="orderInfo<?= $order->getId(); ?>" id="orderInfo<?= $order->getId(); ?>" aria-hidden="true">
                                                    <div class="modal-dialog modal-sm">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title">Informations sur la commande DVN02<?= $order->getId() ?></h5>
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <?= nl2br($order->getDescription()); ?>
                                                                <hr>
                                                                <h5>Contenu de la commande</h5>
                                                                <ul class="list-group">
                                                                    <?php foreach ($order->lines as $line): $total += $line->getPrice(); ?>
                                                                        <li class="list-group-item"><?= $line->getText(); ?> (<?= number_format($line->getPrice(), 2); ?>€)</li>
                                                                    <?php endforeach; ?>
                                                                </ul>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <tr>
                                                    <td>DVN02<?= $order->getId() ?></td>
                                                    <td>
                                                        <?= $order->getCustomer()->getLastname() . ' ' . $order->getCustomer()->getFirstname(); ?> <br>
                                                        <small><a href="mailto:<?= $order->getCustomer()->getEmail(); ?>"><?= $order->getCustomer()->getEmail(); ?></a></small>
                                                    </td>
                                                    <td><?= date('d/m/Y H:i', $order->getRecuperationDate()); ?></td>
                                                    <td><?= $order->getCreatedAt()->format('d/m/Y H:i'); ?></td>
                                                    <td><?= number_format($total, 2) ?>€</td>
                                                    <td>
                                                        <?php if(is_null($order->getPromotion())){ ?>
                                                            /
                                                        <?php } else { ?>
                                                            <a href="/panel/promotion/edit/<?= $order->getPromotion()->getId(); ?>"><?= htmlspecialchars(trim($order->getPromotion()->getName())); ?></a>
                                                        <?php } ?>
                                                    </td>
                                                    <td>
                                                        <a href="/panel/commands/<?= $order->getId(); ?>/update/1" class="btn btn-sm btn-warning"><i class="fa fa-undo"></i> Commande non traîtée</a>
                                                        <a href="/panel/commands/<?= $order->getId(); ?>/update/3" class="btn btn-sm btn-success"><i class="fa fa-check"></i> Commande terminée</a>
                                                        <a href="#" class="btn btn-sm btn-info" data-toggle="modal" data-target="#orderInfo<?= $order->getId(); ?>"><i class="fa fa-info-circle"></i> Plus d'informations</a>
                                                    </td>
                                                </tr>


                                            <?php endforeach; ?>
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>#</th>
                                            <th>Informations</th>
                                            <th>Date de récupération souhaitée</th>
                                            <th>Date de commande</th>
                                            <th>Total à facturer</th>
                                            <th>Promotion</th>
                                            <th><?= \Core\Language::get('action') ?></th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <div class="tab-pane fade" id="nav-status-1" role="tabpanel" aria-labelledby="nav-status-1-tab">
                                    <table id="commands_status_1" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Informations</th>
                                            <th>Date de récupération souhaitée</th>
                                            <th>Date de commande</th>
                                            <th>Total à facturer</th>
                                            <th>Promotion</th>
                                            <th><?= \Core\Language::get('action') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach ($orders['status_1'] as $order) : $total = 0; ?>
                                            <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="orderInfo<?= $order->getId(); ?>" id="orderInfo<?= $order->getId(); ?>" aria-hidden="true">
                                                <div class="modal-dialog modal-sm">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Informations sur la commande DVN02<?= $order->getId() ?></h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <?= nl2br($order->getDescription()); ?>
                                                            <hr>
                                                            <h5>Contenu de la commande</h5>
                                                            <ul class="list-group">
                                                                <?php foreach ($order->lines as $line): $total += $line->getPrice(); ?>
                                                                    <li class="list-group-item"><?= $line->getText(); ?> (<?= number_format($line->getPrice(), 2); ?>€)</li>
                                                                <?php endforeach; ?>
                                                            </ul>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <tr>
                                                <td>DVN02<?= $order->getId() ?></td>
                                                <td>
                                                    <?= $order->getCustomer()->getLastname() . ' ' . $order->getCustomer()->getFirstname(); ?> <br>
                                                    <small><a href="mailto:<?= $order->getCustomer()->getEmail(); ?>"><?= $order->getCustomer()->getEmail(); ?></a></small>
                                                </td>
                                                <td><?= date('d/m/Y H:i', $order->getRecuperationDate()); ?></td>
                                                <td><?= $order->getCreatedAt()->format('d/m/Y H:i'); ?></td>
                                                <td><?= number_format($total, 2) ?>€</td>
                                                <td>
                                                    <?php if(is_null($order->getPromotion())){ ?>
                                                        /
                                                    <?php } else { ?>
                                                        <a href="/panel/promotion/edit/<?= $order->getPromotion()->getId(); ?>"><?= htmlspecialchars(trim($order->getPromotion()->getName())); ?></a>
                                                    <?php } ?>
                                                </td>
                                                <td>
                                                    <?php if(($order->getRecuperationDate() - time()) >= 3600) { ?>
                                                        <a href="/panel/commands/<?= $order->getId(); ?>/update/4" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Annuler la commande</a>
                                                    <?php } ?>
                                                    <a href="/panel/commands/<?= $order->getId(); ?>/update/2" class="btn btn-sm btn-warning"><i class="fa fa-redo"></i> Commande en traitement</a>
                                                    <a href="/panel/commands/<?= $order->getId(); ?>/update/3" class="btn btn-sm btn-success"><i class="fa fa-check"></i> Commande terminée</a>
                                                    <a href="#" class="btn btn-sm btn-info" data-toggle="modal" data-target="#orderInfo<?= $order->getId(); ?>"><i class="fa fa-info-circle"></i> Plus d'informations</a>
                                                </td>
                                            </tr>


                                        <?php endforeach; ?>
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>#</th>
                                            <th>Informations</th>
                                            <th>Date de récupération souhaitée</th>
                                            <th>Date de commande</th>
                                            <th>Total à facturer</th>
                                            <th>Promotion</th>
                                            <th><?= \Core\Language::get('action') ?></th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <div class="tab-pane fade" id="nav-status-3" role="tabpanel" aria-labelledby="nav-status-3-tab">
                                    <table id="commands_status_3" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Informations</th>
                                            <th>Date de récupération souhaitée</th>
                                            <th>Date de commande</th>
                                            <th>Total à facturer</th>
                                            <th>Promotion</th>
                                            <th><?= \Core\Language::get('action') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach ($orders['status_3'] as $order) : $total = 0; ?>
                                            <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="orderInfo<?= $order->getId(); ?>" id="orderInfo<?= $order->getId(); ?>" aria-hidden="true">
                                                <div class="modal-dialog modal-sm">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Informations sur la commande DVN02<?= $order->getId() ?></h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <?= nl2br($order->getDescription()); ?>
                                                            <hr>
                                                            <h5>Contenu de la commande</h5>
                                                            <ul class="list-group">
                                                                <?php foreach ($order->lines as $line): $total += $line->getPrice(); ?>
                                                                    <li class="list-group-item"><?= $line->getText(); ?> (<?= number_format($line->getPrice(), 2); ?>€)</li>
                                                                <?php endforeach; ?>
                                                            </ul>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <tr>
                                                <td>DVN02<?= $order->getId() ?></td>
                                                <td>
                                                    <?= $order->getCustomer()->getLastname() . ' ' . $order->getCustomer()->getFirstname(); ?> <br>
                                                    <small><a href="mailto:<?= $order->getCustomer()->getEmail(); ?>"><?= $order->getCustomer()->getEmail(); ?></a></small>
                                                </td>
                                                <td><?= date('d/m/Y H:i', $order->getRecuperationDate()); ?></td>
                                                <td><?= $order->getCreatedAt()->format('d/m/Y H:i'); ?></td>
                                                <td><?= number_format($total, 2) ?>€</td>
                                                <td>
                                                    <?php if(is_null($order->getPromotion())){ ?>
                                                        /
                                                    <?php } else { ?>
                                                        <a href="/panel/promotion/edit/<?= $order->getPromotion()->getId(); ?>"><?= htmlspecialchars(trim($order->getPromotion()->getName())); ?></a>
                                                    <?php } ?>
                                                </td>
                                                <td>
                                                    <a href="/panel/commands/<?= $order->getId(); ?>/update/2" class="btn btn-sm btn-warning"><i class="fa fa-undo"></i> Commande en traitement</a>
                                                    <a href="/panel/commands/<?= $order->getId(); ?>/update/1" class="btn btn-sm btn-success"><i class="fa fa-undo"></i> Commande non traîtée</a>
                                                    <a href="#" class="btn btn-sm btn-info" data-toggle="modal" data-target="#orderInfo<?= $order->getId(); ?>"><i class="fa fa-info-circle"></i> Plus d'informations</a>
                                                </td>
                                            </tr>


                                        <?php endforeach; ?>
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>#</th>
                                            <th>Informations</th>
                                            <th>Date de récupération souhaitée</th>
                                            <th>Date de commande</th>
                                            <th>Total à facturer</th>
                                            <th>Promotion</th>
                                            <th><?= \Core\Language::get('action') ?></th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <div class="tab-pane fade" id="nav-status-4" role="tabpanel" aria-labelledby="nav-status-4-tab">
                                    <table id="commands_status_4" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Informations</th>
                                            <th>Date de récupération souhaitée</th>
                                            <th>Date de commande</th>
                                            <th>Total à facturer</th>
                                            <th>Promotion</th>
                                            <th><?= \Core\Language::get('action') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach ($orders['status_4'] as $order) : $total = 0; ?>
                                            <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="orderInfo<?= $order->getId(); ?>" id="orderInfo<?= $order->getId(); ?>" aria-hidden="true">
                                                <div class="modal-dialog modal-sm">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Informations sur la commande DVN02<?= $order->getId() ?></h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <?= nl2br($order->getDescription()); ?>
                                                            <hr>
                                                            <h5>Contenu de la commande</h5>
                                                            <ul class="list-group">
                                                                <?php foreach ($order->lines as $line): $total += $line->getPrice(); ?>
                                                                    <li class="list-group-item"><?= $line->getText(); ?> (<?= number_format($line->getPrice(), 2); ?>€)</li>
                                                                <?php endforeach; ?>
                                                            </ul>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <tr>
                                                <td>DVN02<?= $order->getId() ?></td>
                                                <td>
                                                    <?= $order->getCustomer()->getLastname() . ' ' . $order->getCustomer()->getFirstname(); ?> <br>
                                                    <small><a href="mailto:<?= $order->getCustomer()->getEmail(); ?>"><?= $order->getCustomer()->getEmail(); ?></a></small>
                                                </td>
                                                <td><?= date('d/m/Y H:i', $order->getRecuperationDate()); ?></td>
                                                <td><?= $order->getCreatedAt()->format('d/m/Y H:i'); ?></td>
                                                <td><?= number_format($total, 2) ?>€</td>
                                                <td>
                                                    <?php if(is_null($order->getPromotion())){ ?>
                                                        /
                                                    <?php } else { ?>
                                                        <a href="/panel/promotion/edit/<?= $order->getPromotion()->getId(); ?>"><?= htmlspecialchars(trim($order->getPromotion()->getName())); ?></a>
                                                    <?php } ?>
                                                </td>
                                                <td>
                                                    <a href="#" class="btn btn-sm btn-info" data-toggle="modal" data-target="#orderInfo<?= $order->getId(); ?>"><i class="fa fa-info-circle"></i> Plus d'informations</a>
                                                </td>
                                            </tr>


                                        <?php endforeach; ?>
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>#</th>
                                            <th>Informations</th>
                                            <th>Date de récupération souhaitée</th>
                                            <th>Date de commande</th>
                                            <th>Total à facturer</th>
                                            <th>Promotion</th>
                                            <th><?= \Core\Language::get('action') ?></th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>


    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/dist/js/adminlte.js"></script>
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
    $(function () {
        $("#commands_status_1").DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json'
            }
        });

        $("#commands_status_2").DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json'
            }
        });

        $("#commands_status_3").DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json'
            }
        });

        $("#commands_status_4").DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json'
            }
        });
    });

</script>
</body>
</html>
