<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header bg-success">
                <h3 class="card-title"><?= \Core\Language::get('event_list') ?></h3>
            </div>
            <div class="card-body">
                <table id="administrators" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th><?= \Core\Language::get('start_at') ?></th>
                            <th><?= \Core\Language::get('name') ?></th>
                            <th><?= \Core\Language::get('end_at') ?></th>
                            <th><?= \Core\Language::get('begin_register_at') ?></th>
                            <th><?= \Core\Language::get('description') ?></th>
                            <th><?= \Core\Language::get('created_at') ?></th>
                            <th><?= \Core\Language::get('action') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($events as $event) : ?>
                            <tr>
                                <td><?= $event->getId(); ?></td>
                                <td><?= $event->getName(); ?></td>
                                <td><?= $event->getStartAt()->format('d/m/Y H:i:s'); ?></td>
                                <td><?= $event->getEndAt()->format('d/m/Y H:i:s'); ?></td>
                                <td><?= $event->getBeginRegisterAt()->format('d/m/Y H:i:s') ?></td>
                                <td><?= $event->getDescription(); ?></td>
                                <td><?= $event->getCreatedAt()->format('d/m/Y H:i:s'); ?></td>
                                <td>
                                    <?php if (in_array($event->getId(), $events_inscrit)) : ?>
                                        <button class="btn btn-secondary disabled" disabled><?= \Core\Language::get('subscribed') ?></button>
                                    <?php else : ?>
                                        <a href="/panel/event/subscribe/<?= $event->getId(); ?>" class="btn btn-info"><?= \Core\Language::get('subscribe') ?></a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>