<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('franchise_space'); ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/dist/css/adminlte.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item active"><?= \Core\Language::get('home'); ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>


        <section class="content">
            <div class="container-fluid">
                <div class="col-md-12">
                    <div id="map" style="height: 450px"></div>
                </div>

                <div class="col-12 pt-3">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Mes horaires</h3>
                        </div>
                        <div class="card-body">
                            <?php if($update){ ?>
                                <div class="alert alert-success">
                                    <i class="fa fa-check-circle"></i> Vos horaires ont bien été modifiées !
                                </div>
                            <?php } ?>
                            <form method="POST">
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="monday_open">Horaire d'ouverture le lundi: </label>
                                        <input type="time" name="monday_open" value="<?= $openings->getMondayOpen()->format('H:i'); ?>" id="monday_open" class="form-control">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="monday_close">Horaire de fermeture le lundi: </label>
                                        <input type="time" name="monday_close" id="monday_close" value="<?= $openings->getMondayClose()->format('H:i'); ?>" class="form-control">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="tuesday_open">Horaire d'ouverture le mardi: </label>
                                        <input type="time" name="tuesday_open" id="tuesday_open" value="<?= $openings->getTuesdayOpen()->format('H:i'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="tuesday_close">Horaire de fermeture le mardi: </label>
                                        <input type="time" name="tuesday_close" id="tuesday_close" value="<?= $openings->getTuesdayClose()->format('H:i'); ?>" class="form-control">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="wed_open">Horaire d'ouverture le mercredi: </label>
                                        <input type="time" name="wed_open" id="wed_open" value="<?= $openings->getWedOpen()->format('H:i'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="wed_close">Horaire de fermeture le mercredi: </label>
                                        <input type="time" name="wed_close" id="wed_close" value="<?= $openings->getWedClose()->format('H:i'); ?>" class="form-control">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="thursday_open">Horaire d'ouverture le jeudi: </label>
                                        <input type="time" name="thursday_open" id="thursday_open" value="<?= $openings->getThursdayOpen()->format('H:i'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="thursday_close">Horaire de fermeture le jeudi: </label>
                                        <input type="time" name="thursday_close" id="thursday_close" value="<?= $openings->getThursdayClose()->format('H:i'); ?>" class="form-control">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="friday_open">Horaire d'ouverture le vendredi: </label>
                                        <input type="time" name="friday_open" id="friday_open" value="<?= $openings->getFridayOpen()->format('H:i'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="friday_close">Horaire de fermeture le vendredi: </label>
                                        <input type="time" name="friday_close" id="friday_close" value="<?= $openings->getFridayClose()->format('H:i'); ?>" class="form-control">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="sat_open">Horaire d'ouverture le samedi: </label>
                                        <input type="time" name="sat_open" id="sat_open" value="<?= $openings->getSatOpen()->format('H:i'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="sat_close">Horaire de fermeture le samedi: </label>
                                        <input type="time" name="sat_close" id="sat_close" value="<?= $openings->getSatClose()->format('H:i'); ?>" class="form-control">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="sun_open">Horaire d'ouverture le dimanche: </label>
                                        <input type="time" name="sun_open" id="sun_open" value="<?= $openings->getSunOpen()->format('H:i'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="sun_close">Horaire de fermeture le dimanche: </label>
                                        <input type="time" name="sun_close" id="sun_close" value="<?= $openings->getSunClose()->format('H:i'); ?>" class="form-control">
                                    </div>
                                </div>

                                <div class="form-check">
                                    <input type="checkbox" value="1" <?= ($openings->getGlobalOpen() == 0) ? 'checked="checked"' : ''; ?> name="global_open" class="form-check-input" id="global_open">
                                    <label class="form-check-label" for="global_open">Fermer le camion</label>
                                </div>

                                <br>

                                <div class="form-group">
                                    <button class="btn btn-block btn-primary">Sauvegarder mes horaires</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </section>

    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/dist/js/adminlte.js"></script>
<script async type="text/javascript">
    // Centre de la carte par défaut -> Paris

    var map = null;
    var geocoder;
    var mapPopup = null;
    function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {
            zoom: 11,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            mapTypeControl: true,
            scrollwheel: false,
            mapTypeControlOptions: {
                style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR
            },
            navigationControl: true,
            navigationControlOptions: {
                style: google.maps.NavigationControlStyle.ZOOM_PAN
            }
        });

        geocoder = new google.maps.Geocoder();

        // CENTRER LA MAP PAR DEFAUT SUR LA FRANCE
        geocoder.geocode({'address': "Ile-De-France"}, function(results, status) {
            if (status === 'OK') {
                map.setCenter(results[0].geometry.location);
            } else {
                console.error('Geocode was not successful for the following reason: ' + status);
            }
        });

        <?php if(!is_null($user->getTruck()) && !empty($user->getTruck()->getLatitude()) && !empty($user->getTruck()->getLongitude())) { ?>
            new google.maps.Marker({
                position:
                    {
                        lat: <?= $user->getTruck()->getLatitude(); ?>, lng: <?= $user->getTruck()->getLongitude(); ?>
                    },
                icon: {
                    url: 'https://img.icons8.com/color/48/000000/rv-campground.png'
                },
                map: map
            });
        <?php } ?>

        mapPopup = new google.maps.InfoWindow();

        var warehousesLocates = '<?= $warehousesLocates; ?>'
        warehousesLocates = JSON.parse(warehousesLocates);
        for(let i = 0; i < warehousesLocates.length; i++) {
            codeAddress(warehousesLocates[i]['location'], geocoder, map, warehousesLocates[i]['name'], warehousesLocates[i]['id']);
        }
    }

    function codeAddress(address, geocoder, map, name, id) {
        geocoder.geocode({'address': address}, function(results, status) {
            if (status === 'OK') {
                map.setCenter(results[0].geometry.location);
                var marker = new google.maps.Marker({
                    map: map,
                    position: results[0].geometry.location,
                    icon: {
                        url: 'https://img.icons8.com/color/48/000000/warehouse.png'
                    },
                });

                google.maps.event.addListener(marker, 'click', (function (marker) {
                    return function () {
                        let content = name + "<br><br>";
                            content += '<a href="/panel/truck/supply/warehouse/'+ id +'">Approvisionner</a>';

                        mapPopup.setContent(content);
                        mapPopup.open(map, marker);
                    }
                })(marker));
            } else {
                alert('Geocode was not successful for the following reason: ' + status);
            }
        });
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<?= \App\Config::GOOGLE_API_KEY; ?>&callback=initMap&language=fr&region=idf">
</script>
</body>
</html>
