<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('franchise_space') ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
<link rel="stylesheet" href="/dist/css/adminlte.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item active"><?= \Core\Language::get('home') ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="error-page">
                <h3 class="headline text-warning" style="margin-left: -50px"> Oups</h3>
                <div class="error-content">
                    <h3><i class="fas fa-exclamation-triangle text-warning"></i> <?= \Core\Language::get('error') ?></h3>
                    <p>
                        <?= \Core\Language::get('no_truck_assign_for_moment') ?><br>
                        <?= \Core\Language::get('contact_us_if_page_not_show') ?><br><br>

                        <?= \Core\Language::get('if_you_not_adjust_payed_in_section') ?> <br>
                        <b><?= \Core\Language::get('facturation') ?></b> > <a href="/panel/invoices/received"><b><?= \Core\Language::get('my_invoices_received') ?></b></a>.
                        <br><br>
                        <?= \Core\Language::get('if_you_already_adjust_dvn_contact_soon') ?>
                    </p>

                </div>
            </div>
        </section>
    </div>



    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/dist/js/adminlte.js"></script>
</body>
</html>
