<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('franchise_space') ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
<link rel="stylesheet" href="/dist/css/adminlte.css">
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/panel"><?= \Core\Language::get('home') ?></a></li>
                            <li class="breadcrumb-item"><a href="/panel/truck"><?= \Core\Language::get('my_truck') ?></a></li>
                            <li class="breadcrumb-item active"><?= \Core\Language::get('supply') ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title"><?= \Core\Language::get('supply_my_truck_step1_available_warehouses') ?></h3>
                        </div>
                        <div class="card-body">
                            <div class="alert alert-info alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h5><i class="icon fas fa-info"></i> <?= \Core\Language::get('step1') ?></h5>
                                <?= \Core\Language::get('supply_do_in_3step_step1_label') ?>
                            </div>
                            <table id="warehouses" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th><?= \Core\Language::get('name') ?></th>
                                    <th><?= \Core\Language::get('location') ?></th>
                                    <th><?= \Core\Language::get('action') ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($warehouses as $warehouse): ?>
                                    <tr>
                                        <td><?= $warehouse->getName(); ?></td>
                                        <td>
                                            <a href="https://maps.google.com/?q=<?= $warehouse->getLocation(); ?>">
                                                <?= $warehouse->getLocation(); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a class="btn btn-sm btn-info" href="/panel/truck/supply/warehouse/<?= $warehouse->getId(); ?>"><i class="fas fa-building"></i> <?= \Core\Language::get('choose_this_warehouse') ?></a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th><?= \Core\Language::get('name') ?></th>
                                    <th><?= \Core\Language::get('location') ?></th>
                                    <th><?= \Core\Language::get('action') ?></th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>


</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="/dist/js/adminlte.min.js"></script>
<script src="/dist/js/demo.js"></script>
<script>
    $(function () {
        $("#warehouses").DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json'
            }
        });
    });
</script>
</body>
</html>
