<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('administration') ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/dist/css/adminlte.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <?php require "assets/sidebar.phtml"; ?>

        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="/administration"><?= \Core\Language::get('home') ?></a></li>
                                <li class="breadcrumb-item"><?= \Core\Language::get('franchises') ?></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-4" id="files">
                            <!-- Listes des fichiers -->
                            <?php
                            if ($handle = opendir('./dist/qrcode')) {
                                echo '<ul id="list-images" class="list-group">';

                                while (false !== ($entry = readdir($handle))) {
                                    if ($entry != "." && $entry != ".." && substr($entry, -3) == 'png') {
                                        echo '<li style="cursor:pointer" class="list-group-item">'. $entry .'</li>';
                                    }
                                }

                                closedir($handle);
                                echo '</ul>';
                            } ?>
                        </div>
                        <div class="col-md-4">
                            <!-- Action -->
                            <div class="d-flex flex-column px-5">
                                <button type="button" id="check-button" class="btn btn-primary mb-4">Check</button>
                                <button type="button" id="insert-button" class="btn btn-danger mb-4">Insert</button>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <!-- output -->
                            <img src="" alt="" class="img-fluid" id="output-image">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <pre id="qrcode-pre"></pre>
                            <pre id="text-output"></pre>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <footer class="main-footer">
            <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                Projet annuel ESGI <b>2A2</b>
            </div>
        </footer>
    </div>

    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/plugins/select2/js/select2.full.min.js"></script>
    <script src="/dist/js/adminlte.min.js"></script>

    <script>
        let filename = '';
        const checkButton = document.querySelector('#check-button');
        const insertButton = document.querySelector('#insert-button');

        checkButton.addEventListener('click', function() {
            $.ajax({
                type: 'POST',
                url: '/administration/franchises/shellCheck',
                data: {
                    filename: filename
                },
                success: output => {
                    const pre = document.querySelector('#qrcode-pre');
                    pre.innerText = output;
                }
            });
        });

        insertButton.addEventListener('click', function() {
            $.ajax({
                type: 'POST',
                url: '/administration/franchises/shellInsert',
                data: {
                    filename: filename
                },
                success: {
                    window.location = "/administration/franchises/add"
                }
            });
        });

        function loadImage(e) {
            filename = e.target.innerText;
            const img = document.querySelector('#output-image');
            img.setAttribute('src', '/dist/qrcode/' + filename);
        }

        const listItems = document.querySelectorAll('#list-images > li');
        listItems.forEach(item => {
            item.addEventListener('click', loadImage);
        });

        $("#files li").on("click", function() {
            $("#files li").removeClass("active");
            $(this).addClass("active");
        });

    </script>
</body>

</html>