<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - Administration</title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/administration">Accueil</a></li>
                            <li class="breadcrumb-item"><a href="/administration/warehouses">Entrepôts</a></li>
                            <li class="breadcrumb-item">Stocks</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-warning">
                            <div class="card-header">
                                <h3 class="card-title">Ajouter une catégorie</h3>
                            </div>
                            <form role="form" method="POST">
                                <div class="card-body">
                                    <div class="alert alert-info alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                        <h5><i class="icon fas fa-info"></i> Information !</h5>
                                            Le nom de la catégorie doit être unique.
                                    </div>
                                    <div class="form-group">
                                        <label for="nameInput">Nom de la catégorie</label>
                                        <input type="text" value="<?= (isset($params['name'])) ? htmlspecialchars(trim($params['name'])) : ''; ?>" class="form-control <?= (isset($fields['name'])) ? 'is-invalid' : ''; ?>" id="nameInput" placeholder="Nom" name="name">
                                    </div>

                                    <hr>

                                    <div class="form-group">
                                        <label for="categorieInput">Relier à une catégorie parente</label>
                                        <select id="categorieInput" class="form-control select2 <?= (isset($fields['parent'])) ? 'is-invalid' : ''; ?>" name="parent" style="width: 100%;">
                                            <option selected="selected" value="0">--- Selectionner une catégorie ---</option>
                                            <?php foreach ($parents as $parent): ?>
                                                <option value="<?= $parent->getId(); ?>">
                                                        <?php foreach ($parent->parents as $previousParent): ?>
                                                            <?= $previousParent->getName(); ?> /
                                                        <?php endforeach; ?>
                                                    <?= $parent->getName(); ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="card-footer">
                                    <?= \Core\CSRF::fields(); ?>
                                    <button type="submit" class="btn btn-warning">Enregistrer</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <aside class="control-sidebar control-sidebar-dark">
    </aside>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/plugins/select2/js/select2.full.min.js"></script>
<script src="/dist/js/adminlte.min.js"></script>
<script>
    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2({
            theme: 'bootstrap4'
        })

    })
</script>
</body>
</html>
