<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - Administration</title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/administration">Accueil</a></li>
                            <li class="breadcrumb-item active">Administrateurs</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Les administrateurs Driv'n'Cook</h3>
                        </div>
                        <div class="card-body">
                            <table id="administrators" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Prénom</th>
                                    <th>Nom</th>
                                    <th>Email</th>
                                    <th>Crée le</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($administrators as $administrator): ?>
                                    <tr>
                                        <td><?= $administrator->getId(); ?></td>
                                        <td><?= $administrator->getFirstname(); ?></td>
                                        <td><?= $administrator->getLastname(); ?></td>
                                        <td><?= $administrator->getEmail(); ?></td>
                                        <td><?= $administrator->getCreatedAt()->format('d/m/Y H:i:s'); ?></td>
                                        <td>
                                            <?php if($user->getId() != $administrator->getId()) { ?>
                                                <a class="btn btn-info btn-sm" href="/administration/administrators/<?= $administrator->getId(); ?>/edit"><i class="fas fa-pencil-alt"></i> Editer</a>
                                                <form onsubmit="return confirm('Voulez-vous vraiment supprimer cet administrateur ?');" style="display: inline" method="POST" action="/administration/administrators/<?= $administrator->getId(); ?>/delete">
                                                    <?= \Core\CSRF::fields(); ?>
                                                    <button class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Supprimer</button>
                                                </form>
                                            <?php } else { ?>
                                                <a class="btn btn-warning btn-sm" href="/administration/administrators/<?= $administrator->getId(); ?>/edit"><i class="fas fa-pencil-alt"></i> Mon compte</a>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>Prénom</th>
                                    <th>Nom</th>
                                    <th>Email</th>
                                    <th>Crée le</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>

    <aside class="control-sidebar control-sidebar-dark">
    </aside>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="/dist/js/adminlte.min.js"></script>
<script>
    $(function () {
        $("#administrators").DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json'
            }
        });
    });
</script>
</body>
</html>
