<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="general-tab" data-toggle="tab" href="#general" role="tab" aria-controls="general" aria-selected="true">
                    Géneral
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="CMS-tab" data-toggle="tab" href="#CMS" role="tab" aria-controls="CMS" aria-selected="true">CMS</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="user-tab" data-toggle="tab" href="#user" role="tab" aria-controls="user" aria-selected="true">User</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="trucks-tab" data-toggle="tab" href="#trucks" role="tab" aria-controls="trucks" aria-selected="true">Trucks</a>
            </li>
        </ul>
    </div>
    <div class="card-body tab-content">
        <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">
            <form id="form-general" method="post">
                <div class="form-group">
                    <?= \Core\CSRF::fields(); ?>
                    <label for="status"><?= \Core\Language::get("name") ?></label>
                    <input type="text" name="name" id="name" class="form-control" 
                    value="<?= $event->getName() ?>">
                </div>
                <label for="status"><?= \Core\Language::get("start_at") ?></label>
                <div class="form-row form-group">
                    <div class="col-8">
                        <input type="date" name="date_start" id="date_start" class="form-control" 
                        value="<?= $event->getBeginRegisterAt()->format('Y-m-d') ?>">
                    </div>
                    <div class="col-4">
                        <input type="time" name="time_start" id="time_start" class="form-control" 
                        value="<?= $event->getBeginRegisterAt()->format('H:i') ?>">
                    </div>
                </div>
                <label for="status"><?= \Core\Language::get("begin_register_at") ?></label>
                <div class="form-row form-group">
                    <div class="col-8">
                        <input type="date" name="date_begin_register_at" id="date_begin_register_at" class="form-control" value="<?= $event->getStartAt()->format('Y-m-d') ?>">
                    </div>
                    <div class="col-4">
                        <input type="time" name="time_begin_register_at" id="time_begin_register_at" class="form-control" value="<?= $event->getStartAt()->format('H:i') ?>">
                    </div>
                </div>
                <label for="status"><?= \Core\Language::get("end_at") ?></label>
                <div class="form-row form-group">
                    <div class="col-8">
                        <input type="date" name="date_end" id="date_end" class="form-control" 
                        value="<?= $event->getEndAt()->format('Y-m-d') ?>">
                    </div>
                    <div class="col-4">
                        <input type="time" name="time_end" id="time_end" class="form-control" 
                        value="<?= $event->getEndAt()->format('H:i') ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" id="description" cols="30" rows="4" class="form-control"><?= $event->getDescription() ?></textarea>
                </div>
                <div class="form-group">
                    <label for="type">Type</label>
                    <select class="form-control" name="type" id="type">
                        <option <?= \Core\View::set_select('type', 'invite-only') ?> value="invite-only">invite-only</option>
                        <option <?= \Core\View::set_select('type', 'public', 'default') ?> value="public">public</option>
                        <option <?= \Core\View::set_select('type', 'with-VIP') ?> value="with-VIP">with-VIP</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-block btn-warning"
                ><?= \Core\Language::get('validate') ?></button>
            </form>
        </div>
        <div class="tab-pane fade" id="CMS" role="tabpanel" aria-labelledby="CMS-tab">
            <form method="POST" action="/administration/event/<?= $event->getId() ?>/post-cms" enctype="multipart/form-data">
                <?php
                if (isset($_SESSION['errorCMS'])) {
                    $errors = $_SESSION['errorCMS'];
                    if (!empty($errors)) {
                        echo '<div class="alert alert-danger"><h3>Error : </h3><ul>';
                        foreach ($errors as $error) {
                            echo "<li>$error</li>";
                        }
                        echo '</ul></div>';
                        unset($_SESSION['errorCMS']);
                    }
                }
                ?>
                <div class="form-row">
                    <div class="col-md-6 form-group">
                        <label for="fileImg"><?= \Core\Language::get('image_event') ?></label>
                        <input type="file" id="fileImg" name="img" class="form-control-file">
                    </div>
                    <div class="col-md-6">
                        <img src="<?= '/dist/uploads/event/' . $event->getId() . '/' . $event->getImage() ?>" alt="" class="img-fluid">
                    </div>
                </div>
                <h2>Français</h2>
                <div class="form-group">
                    <label for="titleEmailFR">Titre de l'Email</label>
                    <input type="text" class="form-control" id="titleEmailFR" placeholder="Title Email" name="titleEmailFR" value="<?= \Core\View::set_values('titleEmailFR', $event->getTitleEmailFR()) ?>">
                </div>
                <div class="form-group">
                    <label for="textEmailFR">Text de l'Email</label>
                    <small class="form-text text-muted">Vous pouvez utiliser [firstname], [lastname], [email] pour utiliser les données du customer</small>
                    <textarea type="text" class="form-control" id="textEmailFR" placeholder="Text Email" name="textEmailFR"><?= \Core\View::set_values('textEmailFR', $event->getTextEmailFR()) ?></textarea>
                </div>
                <div class="form-group">
                    <textarea id="editorFR" name="wysiwygFR"><?= \Core\View::set_values('wysiwygFR', $event->getTextFR()) ?></textarea>
                </div>

                <h2>Anglais</h2>
                <div class="form-group">
                    <label for="titleEmailEN">Titre de l'Email</label>
                    <input type="text" class="form-control" id="titleEmailEN" placeholder="Title Email" name="titleEmailEN" value="<?= \Core\View::set_values('titleEmailEN', $event->getTitleEmailEN()) ?>">
                </div>
                <div class="form-group">
                    <label for="textEmailEN">Text de l'Email</label>
                    <small class="form-text text-muted">Vous pouvez utiliser [firstname], [lastname], [email] pour utiliser les données du customer</small>
                    <textarea type="text" class="form-control" id="textEmailEN" placeholder="Text Email" name="textEmailEN"><?= \Core\View::set_values('textEmailEN', $event->getTextEmailEN()) ?></textarea>
                </div>
                <div class="form-group">
                    <textarea id="editorEN" name="wysiwygEN"><?= \Core\View::set_values('wysiwygEN', $event->getTextEN()) ?></textarea>
                </div>

                <p class="text-center">
                    <button type="submit" class="btn btn-warning btn-block">Modifier L'event</button>
                </p>
            </form>
        </div>
        <div class="tab-pane fade" id="user" role="tabpanel" aria-labelledby="user-tab">
            <p>User TAb panel</p>
            <p class="text-center"><input type="text" id="autoComplete"></p>
            <hr>
            <form action="/administration/event/<?= $event->getId() ?>/send_invitation" method="POST">
                <table class="table-bordered table" id="user-table">
                    <thead>
                        <th>id</th>
                        <th>FirstName</th>
                        <th>LastName</th>
                        <th>Email</th>
                        <th>Action</th>
                    </thead>
                    <tbody>
                        <?php foreach ($eventCustomers as $eventCustomer) : ?>
                            <?php $customer = $eventCustomer->getCustomer() ?>
                            <tr>
                                <td><?= $customer->getId(); ?><input type="hidden" value="<?= $customer->getId(); ?>"></td>
                                <td><?= $customer->getFirstName() ?></td>
                                <td><?= $customer->getLastName(); ?></td>
                                <td><?= $customer->getEmail(); ?></td>
                                <td>
                                    <a class="btn btn-info"
                                    target="_blank"
                                    href="<?= '/administration/event/' . $event->getId() . '/preview/' . $customer->getId() ?>"
                                    >Preview</a>
                                    <a class="btn btn-danger" 
                                    href="<?= '/administration/event/' . $event->getId() . '/resend/' . $customer->getId() ?>"
                                    >Resend</a>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
                <p class="text-center">
                    <button type="submit" class="btn btn-primary"><?= \Core\Language::get('submit') ?></button>
                </p>
            </form>
        </div>
        <div class="tab-pane fade" id="trucks" role="tabpanel" aria-labelledby="trucks-tab">
            <h2>Listes des Camions</h2>
            <table class="table table-bordered">
                <thead>
                    <th>trucks</th>
                    <th>FirstName</th>
                    <th>LastName</th>
                    <th>city</th>
                    <th>action</th>
                </thead>
                <?php
                $users = $event->getUser();
                foreach ($users as $user) : ?>
                    <tr>
                        <?php if (!empty($user->getTruck())) : ?>
                            <td class="text-center">
                                <a href="<?= "/administration/trucks/" . $user->getTruck()->getId() . "/information" ?>" class="btn btn-info btn-sm"><i class="fas fa-truck"></i></a>
                            </td>
                        <?php else : ?>
                            <td class="text-danger">No trucks</td>
                        <?php endif ?>
                        <td><?= $user->getFirstName(); ?></td>
                        <td><?= $user->getLastName(); ?></td>
                        <td><?= $user->getAddressCity(); ?></td>
                        <td class="text-center">
                            <a href="<?= "/administration/franchises/" . $user->getId() . "/edit" ?>" class="btn btn-info btn-sm"><i class="fas fa-edit"></i></a>
                            <a href="<?= '/administration/event/' . $event->getId() . '/remove/' . $user->getId() ?>" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
<script defer src="/dist/js/trumbowyg.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@7.2.0/dist/js/autoComplete.min.js"></script>
<script>
    new autoComplete({
        data: {
            src: async () => {
                const query = document.querySelector("#autoComplete").value;
                const source = await fetch(`/administration/customer/search?q=${query}`);
                return await source.json();
            },
            key: ["firstName", "lastName"],
            cache: false
        },
        placeHolder: "Firstname & Lastname",
        selector: "#autoComplete",
        threshold: 2,
        debounce: 300,
        searchEngine: "strict",
        resultsList: {
            render: true,
            destination: document.querySelector("#autoComplete_list"),
            position: "afterend",
            element: "ul"
        },
        maxResults: 5,
        highlight: true,
        resultItem: {
            content: (data, source) => {
                source.innerHTML = `${data.value.firstName} ${data.value.lastName}`;
            },
            element: "li"
        },
        onSelection: feed => {
            const customer = feed.selection.value;

            const idsAlreadyInSelection = Array.from(document.querySelectorAll('#user-table > tbody > tr > td:first-child > input'));
            if (idsAlreadyInSelection.filter(id => id.value == customer.id).length !== 0) {
                return;
            }

            const tbody = document.querySelector("#user-table > tbody");
            const tr = document.createElement("tr");
            Object.keys(customer).map(key => {
                const td = document.createElement("td");
                const text = document.createTextNode(customer[key]);
                if (key  === "id") {
                    const input = document.createElement('input');
                    input.setAttribute('type', 'hidden');
                    input.setAttribute('name', 'id[]');
                    input.value = customer[key];
                    td.appendChild(input);
                }

                td.appendChild(text);
                tr.appendChild(td);
            });
            const td = document.createElement("td");
            const a = document.createElement("a");
            const text = document.createTextNode('Preview');
            a.setAttribute("class", "btn btn-info");
            a.setAttribute("href", "/administration/event/" + <?= $event->getId() ?> +"/preview/" +
                customer.id);
            a.setAttribute("target", '_blank');
            a.appendChild(text);
            td.appendChild(a);
            tr.appendChild(td);
            tbody.appendChild(tr);
        }
    });
    document.addEventListener('DOMContentLoaded', () => {
        $('#editorFR').trumbowyg();
        $('#editorEN').trumbowyg();
        if (localStorage.getItem('tabEvent') !== null) {
            $("#" + localStorage.getItem('tabEvent')).tab('show');
        }

        $('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
            localStorage.setItem('tabEvent', e.target.attributes.id.value);
        });
    });
</script>