<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('administration') ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
<link rel="stylesheet" href="/dist/css/adminlte.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/administration"><?= \Core\Language::get('home') ?></a></li>
                            <li class="breadcrumb-item"><?= \Core\Language::get('franchises') ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-warning">
                            <div class="card-header">
                                <h3 class="card-title"><?= \Core\Language::get('edit_franchise') ?></h3>
                            </div>
                            <form role="form" method="POST">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="emailInput"><?= \Core\Language::get('email') ?></label>
                                        <input type="email" value="<?= $franchise->getEmail(); ?>" class="form-control <?= (isset($fields['email'])) ? (!$fields['email']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="emailInput" placeholder="<?= \Core\Language::get("email") ?>" name="email">
                                    </div>

                                    <div class="form-group">
                                        <label for="societyInput"><?= \Core\Language::get('society_name') ?></label>
                                        <input type="text" value="<?= $franchise->getSocietyName(); ?>" class="form-control <?= (isset($fields['society'])) ? (!$fields['society']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="societyInput" placeholder="<?= \Core\Language::get('society_name') ?>" name="society">
                                    </div>

                                    <div class="form-group">
                                        <label for="siretInput"><?= \Core\Language::get('siret') ?></label>
                                        <input type="text" value="<?= $franchise->getSiret(); ?>" class="form-control <?= (isset($fields['siret'])) ? (!$fields['siret']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="siretInput" placeholder="<?= \Core\Language::get('siret') ?>" name="siret">
                                    </div>

                                    <div class="form-group">
                                        <label for="firstnameInput"><?= \Core\Language::get('firstname') ?></label>
                                        <input type="text" value="<?= $franchise->getFirstname(); ?>" class="form-control <?= (isset($fields['firstname'])) ? (!$fields['firstname']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="firstnameInput" placeholder="<?= \Core\Language::get('firstname') ?>" name="firstname">
                                    </div>

                                    <div class="form-group">
                                        <label for="lastnameInput"><?= \Core\Language::get('lastname') ?></label>
                                        <input type="text" value="<?= $franchise->getLastname(); ?>" class="form-control <?= (isset($fields['lastname'])) ? (!$fields['lastname']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="lastnameInput" placeholder="<?= \Core\Language::get('lastname') ?>" name="lastname">
                                    </div>

                                    <div class="form-group">
                                        <label for="phoneNumberInput"><?= \Core\Language::get('phone_number') ?></label>
                                        <input type="text" value="<?= $franchise->getPhoneNumber(); ?>" class="form-control <?= (isset($fields['phone_number'])) ? (!$fields['phone_number']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="phoneNumberInput" placeholder="<?= \Core\Language::get('phone_number') ?>" name="phone_number">
                                    </div>

                                    <hr>

                                    <div class="form-group">
                                        <label for="addressLineInput"><?= \Core\Language::get('address') ?></label>
                                        <input type="text" value="<?= $franchise->getAddressLine(); ?>" class="form-control <?= (isset($fields['address_line'])) ? (!$fields['address_line']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="addressLineInput" placeholder="<?= \Core\Language::get('address') ?>" name="address_line">
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="cityInput"><?= \Core\Language::get('city') ?></label>
                                                <input type="text" value="<?= $franchise->getAddressCity(); ?>" class="form-control <?= (isset($fields['city'])) ? (!$fields['city']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="cityInput" placeholder="<?= \Core\Language::get('city') ?>" name="city">
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="postalCodeInput"><?= \Core\Language::get('postal_code') ?></label>
                                                <input type="text" value="<?= $franchise->getPostalCode(); ?>" class="form-control <?= (isset($fields['postal_code'])) ? (!$fields['postal_code']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="postalCodeInput" placeholder="<?= \Core\Language::get('postal_code') ?>" name="postal_code">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="stateInput"><?= \Core\Language::get('state') ?></label>
                                                <input type="text" value="<?= $franchise->getAddressState(); ?>" class="form-control <?= (isset($fields['state'])) ? (!$fields['state']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="stateInput" placeholder="<?= \Core\Language::get('state') ?>" name="state">
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="countryInput"><?= \Core\Language::get('country') ?></label>
                                                <input type="text" value="<?= $franchise->getCountry(); ?>" class="form-control <?= (isset($fields['country'])) ? (!$fields['country']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="countryInput" placeholder="<?= \Core\Language::get('country') ?>" name="country">
                                            </div>
                                        </div>
                                    </div>

                                    <hr>
                                    <div class="form-group">
                                        <label for="assignToInput"><?= \Core\Language::get('truck') ?></label>
                                        <select id="assignToInput" class="form-control select2 <?= (isset($fields['assign'])) ? (!$fields['assign']) ? 'is-invalid' : 'is-valid' : ''; ?>" name="assign" style="width: 100%;">
                                            <option selected="selected" value="0">--- <?= \Core\Language::get('select_truck') ?> ---</option>
                                            <?php foreach ($trucks as $truck): ?>
                                            <?php $actual = (!is_null($franchise->getTruck()) && $franchise->getTruck()->getId() == $truck->getId()) ? true : false; ?>
                                                <option <?= ($actual) ? 'selected' : ''; ?> value="<?= $truck->getId(); ?>"><?= $truck->getMatriculation(); ?> <?= ($actual) ? '('. \Core\Language::get('actual') .')' : ''; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <hr>

                                    <div class="form-group">
                                        <label for="passwordInput"><?= \Core\Language::get('password') ?></label>
                                        <input type="password" autocomplete="autocomplete" class="form-control <?= (isset($fields['password'])) ? (!$fields['password']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="passwordInput" name="password" placeholder="<?= \Core\Language::get('password') ?>">
                                    </div>

                                    <div class="form-group">
                                        <label for="passwordConfirmInput"><?= \Core\Language::get('confirm_password') ?></label>
                                        <input type="password" autocomplete="autocomplete" class="form-control <?= (isset($fields['password'])) ? (!$fields['password']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="passwordConfirmInput" name="passwordConfirm" placeholder="<?= \Core\Language::get('confirm_password') ?>">
                                    </div>
                                </div>

                                <div class="card-footer">
                                    <?= \Core\CSRF::fields(); ?>
                                    <button type="submit" class="btn btn-warning"><?= \Core\Language::get('save') ?></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/plugins/select2/js/select2.full.min.js"></script>
<script src="/dist/js/adminlte.min.js"></script>
<script>
    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2({
            theme: 'bootstrap4'
        })

    })
</script>
</body>
</html>
