<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - Administration</title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/administration">Accueil</a></li>
                            <li class="breadcrumb-item"><a href="/administration/administrators">Administrateurs</a></li>
                            <li class="breadcrumb-item">Editer</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-warning">
                            <div class="card-header">
                                <h3 class="card-title">Editer un administrateur</h3>
                            </div>
                            <form role="form" method="POST">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="emailInput">Email</label>
                                        <input type="email" class="form-control <?= (isset($fields['email'])) ? (!$fields['email']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="emailInput" placeholder="Adresse e-mail" name="email" value="<?= $admin->getEmail(); ?>">
                                    </div>

                                    <div class="form-group">
                                        <label for="firstnameInput">Prénom</label>
                                        <input type="text" class="form-control <?= (isset($fields['firstname'])) ? (!$fields['firstname']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="firstnameInput" placeholder="Prénom" name="firstname" value="<?= $admin->getFirstname(); ?>">
                                    </div>

                                    <div class="form-group">
                                        <label for="lastnameInput">Nom</label>
                                        <input type="text" class="form-control <?= (isset($fields['lastname'])) ? (!$fields['lastname']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="lastnameInput" placeholder="Nom" name="lastname" value="<?= $admin->getLastname(); ?>">
                                    </div>

                                    <hr>

                                    <div class="form-group">
                                        <label for="passwordInput">Mot de passe</label>
                                        <input type="password" class="form-control <?= (isset($fields['password'])) ? (!$fields['password']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="passwordInput" name="password" placeholder="Mot de passe">
                                    </div>

                                    <div class="form-group">
                                        <label for="passwordConfirmInput">Confirmez le mot de passe</label>
                                        <input type="password" class="form-control <?= (isset($fields['password'])) ? (!$fields['password']) ? 'is-invalid' : 'is-valid' : ''; ?>" id="passwordConfirmInput" name="passwordConfirm" placeholder="Confirmez le mot de passe">
                                    </div>
                                </div>

                                <div class="card-footer">
                                    <?= \Core\CSRF::fields(); ?>
                                    <button type="submit" class="btn btn-warning">Valider</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <aside class="control-sidebar control-sidebar-dark">
    </aside>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/dist/js/adminlte.js"></script>
</body>
</html>
