<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - Administration</title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/administration">Accueil</a></li>
                            <li class="breadcrumb-item">Facturation</li>
                            <li class="breadcrumb-item active">Factures reçues</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>


        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Les factures reçues de Driv'n'Cook</h3>
                        </div>
                        <div class="card-body">
                            <table id="invoices" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Entrepôt</th>
                                    <th>Statut</th>
                                    <th>Reçue le</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($invoices as $invoice): ?>
                                    <tr>
                                        <td>DVN-<?= $invoice->getId(); ?></td>
                                        <td>
                                            <a href="<?= (!is_null($invoice->getWarehouse())) ? '/administration/stocks/warehouses/' . $invoice->getWarehouse()->getId() : '#' ?>">
                                                <?= (!is_null($invoice->getWarehouse())) ? $invoice->getWarehouse()->getName() : '/'; ?>
                                            </a>
                                        </td>
                                        <td>
                                            <?php if($invoice->getStatus()){ ?>
                                                <span class="badge bg-success">Payée</span>
                                            <?php } else { ?>
                                                <span class="badge bg-danger">Non payée</span>
                                            <?php } ?>
                                        </td>
                                        <td><?= $invoice->getCreatedAt()->format('d/m/Y H:i:s'); ?></td>
                                        <td>
                                            <a href="/administration/invoices/<?= $invoice->getId(); ?>" class="btn btn-sm btn-info"><i class="fa fa-eye"></i> Facture interne</a>

                                            <?php if(!$invoice->getStatus()) { ?>
                                                <form method="POST" style="display: inline" action="/administration/invoices/<?= $invoice->getId(); ?>/pay">
                                                    <button onclick="return confirm('Confirmez que la facture a été payée ?');" class="btn btn-sm btn-warning"><i class="fas fa-dollar-sign"></i> Facture payée</button>
                                                </form>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>Entrepôt</th>
                                    <th>Statut</th>
                                    <th>Reçue le</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <aside class="control-sidebar control-sidebar-dark">
    </aside>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/dist/js/adminlte.js"></script>
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
    $(function () {
        $("#invoices").DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json'
            }
        });
    });
</script>
</body>
</html>
