<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('administration') ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
<link rel="stylesheet" href="/dist/css/adminlte.css">
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/administration"><?= \Core\Language::get('home') ?></a></li>
                            <li class="breadcrumb-item"><?= \Core\Language::get('facturation') ?></li>
                            <li class="breadcrumb-item active"><?= \Core\Language::get('invoices_received') ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>


        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title"><?= \Core\Language::get('received_invoices_from_drivncook') ?></h3>
                        </div>
                        <div class="card-body">
                            <table id="invoices" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th><?= \Core\Language::get('transmitter') ?></th>
                                    <th><?= \Core\Language::get('warehouse') ?></th>
                                    <th><?= \Core\Language::get("status") ?></th>
                                    <th><?= \Core\Language::get('received_at') ?></th>
                                    <th><?= \Core\Language::get('action') ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($invoices as $invoice): ?>
                                        <tr>
                                            <td>DVN-<?= $invoice->getId(); ?></td>
                                            <td><?= $invoice->getOwner(); ?></td>
                                            <td>
                                                <a href="<?= (!is_null($invoice->getWarehouse())) ? '/administration/stocks/warehouses/' . $invoice->getWarehouse()->getId() : '#' ?>">
                                                    <?= (!is_null($invoice->getWarehouse())) ? $invoice->getWarehouse()->getName() : '/'; ?>
                                                </a>
                                            </td>
                                            <td>
                                                <?php if($invoice->getStatus()){ ?>
                                                    <span class="badge bg-success"><?= \Core\Language::get('payed') ?></span>
                                                <?php } else { ?>
                                                    <span class="badge bg-danger"><?= \Core\Language::get('not_payed') ?></span>
                                                <?php } ?>
                                            </td>
                                            <td><?= $invoice->getCreatedAt()->format('d/m/Y H:i:s'); ?></td>
                                            <td>

                                                <?php if(!$invoice->getStatus()) { ?>
                                                    <form method="POST" style="display: inline" action="/administration/invoices/<?= $invoice->getId(); ?>/pay">
                                                        <button onclick="return confirm('<?= \Core\Language::get("confirm_invoice_as_payed") ?>');" class="btn btn-sm btn-success"><i class="fas fa-dollar-sign"></i> <?= \Core\Language::get('settled') ?></button>
                                                    </form>
                                                <?php } ?>

                                                <a href="/administration/invoices/<?= $invoice->getId(); ?>" class="btn btn-sm btn-info"><i class="fa fa-eye"></i> <?= \Core\Language::get('internal_invoice') ?></a>

                                                <?php if($invoice->externalInvoice) { ?>
                                                    <a class="btn btn-warning btn-sm" href="/administration/invoices/real/<?= $invoice->getId(); ?>"><i class="fa fa-file-contract"></i> <?= \Core\Language::get('external_invoice') ?></a>
                                                    <form onclick="return confirm('<?= \Core\Language::get("import_an_external_invoice") ?>')" method="POST" style="display: inline" action="/administration/invoices/<?= $invoice->getId() ?>/delete">
                                                        <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> <?= \Core\Language::get('delete_external_invoice') ?></button>
                                                    </form>
                                                <?php } else { ?>
                                                    <button class="btn btn-warning btn-sm" data-toggle="modal" data-target="#modal<?= $invoice->getId(); ?>"><i class="fa fa-file-contract"></i> <?= \Core\Language::get('import_an_external_invoice') ?></button>
                                                    <div class="modal fade" id="modal<?= $invoice->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="modal<?= $invoice->getId(); ?>Title" aria-hidden="true">
                                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title" id="exampleModalLongTitle"><?= \Core\Language::get('import_an_external_invoice') ?></h5>
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?= \Core\Language::get('close') ?>">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <div class="alert alert-info alert-dismissible">
                                                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                                                        <h5><i class="icon fas fa-info"></i> <?= \Core\Language::get('informations') ?></h5>
                                                                        <?= \Core\Language::get('link_an_external_invoice_in_internal_invoice'); ?>
                                                                    </div>

                                                                    <form action="/administration/invoices/add/<?= $invoice->getId(); ?>" method="POST" enctype="multipart/form-data">
                                                                        <div class="form-group">
                                                                            <label for="invoice<?= $invoice->getId(); ?>"><?= \Core\Language::get('invoice') ?></label>
                                                                            <input type="file" id="invoice<?= $invoice->getId(); ?>" name="invoice" class="form-control-file">
                                                                        </div>
                                                                        <div class="form-group">
                                                                            <?= \Core\CSRF::fields(); ?>
                                                                            <button class="btn btn-block btn-warning"><?= \Core\Language::get('import') ?></button>
                                                                        </div>
                                                                    </form>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= \Core\Language::get('close') ?></button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th><?= \Core\Language::get('transmitter') ?></th>
                                    <th><?= \Core\Language::get('warehouse') ?></th>
                                    <th><?= \Core\Language::get("status") ?></th>
                                    <th><?= \Core\Language::get('received_at') ?></th>
                                    <th><?= \Core\Language::get('action') ?></th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/dist/js/adminlte.js"></script>
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
    $(function () {
        $("#invoices").DataTable({
            language: {
                url: '<?= \Core\Language::get("datatable_trad_link") ?>'
            }
        });
    });
</script>
</body>
</html>
