<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('administration') ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
<link rel="stylesheet" href="/dist/css/adminlte.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item active"><a href="/administration"><?= \Core\Language::get("home") ?></a></li>
                            <li class="breadcrumb-item active"><a href="/administration/trucks/<?= $truck->getId() ?>/informations"><?= \Core\Language::get("truck") ?></a></li>
                            <li class="breadcrumb-item active"><?= \Core\Language::get("maintenance_details") ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">

                        <div class="alert alert-warning alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <h5><i class="icon fas fa-info"></i> <?= \Core\Language::get('informations') ?></h5>
                            <?= \Core\Language::get('maintenance_see_details_for_maintenance_date_truck', [$maintenance->getId(), $maintenance->getCreatedAt()->format('d/m/Y'), $truck->getMatriculation()]); ?><br>
                            <?= \Core\Language::get("maintenance_status") ?> : <b><?= ($maintenance->getStatus() == "waiting") ? \Core\Language::get("waiting")  : (($maintenance->getStatus() == 'processing') ? \Core\Language::get("processing") : \Core\Language::get("finished")); ?></b>
                        </div>
                        <a href="/administration/trucks/<?= $truck->getId() ?>/informations" class="btn btn-sm btn-info float-right mb-3"><i class="fa fa-arrow-left"></i> <?= \Core\Language::get("back_to_truck") ?></a>
                        <button data-toggle="modal" data-target="#updateStatus" class="btn btn-sm btn-warning float-right mr-1"><i class="fa fa-pencil-alt"></i> <?= \Core\Language::get("edit_maintenance_status") ?></button>
                        <form action="/administration/trucks/<?= $truck->getId(); ?>/maintenance/<?= $maintenance->getId(); ?>" method="POST">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <button class="btn btn-outline-info"><?= \Core\Language::get("validate") ?></button>
                                </div>
                                <input type="text" class="form-control" name="info" placeholder="<?= \Core\Language::get("maintenance_add_info_line") ?>">
                            </div>
                        </form>

                        <div class="timeline">
                            <?php foreach ($infos as $date => $logs): ?>
                                <div class="time-label">
                                    <span class="bg-warning"><?= $date ?></span>
                                </div>
                                <?php foreach ($logs as $log): ?>
                                    <div>
                                        <i class="fas fa-info bg-info"></i>
                                        <div class="timeline-item">
                                            <span class="time"><i class="fas fa-clock"></i> <?= $log->getCreatedAt()->format('d/m/Y H:i:s'); ?></span>
                                            <h3 class="timeline-header no-border">
                                                <?= $log->getInfo(); ?>
                                            </h3>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="modal fade" id="updateStatus" tabindex="-1" role="dialog" aria-labelledby="updateStatusTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle"><?= \Core\Language::get('edit_maintenance_status') ?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="<?= \Core\Language::get('close') ?>">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="/administration/trucks/<?= $truck->getId(); ?>/maintenance/<?= $maintenance->getId(); ?>/status">
                        <div class="form-group">
                            <label for="status"><?= \Core\Language::get("status") ?></label>
                            <select name="status" id="status" class="form-control">
                                <option <?= ($maintenance->getStatus() == "waiting") ? 'selected' : ''; ?> value="waiting"><?= \Core\Language::get('waiting') ?></option>
                                <option <?= ($maintenance->getStatus() == "processing") ? 'selected' : ''; ?> value="processing"><?= \Core\Language::get('processing') ?></option>
                                <option <?= ($maintenance->getStatus() == "finished") ? 'selected' : ''; ?> value="finished"><?= \Core\Language::get('finished') ?></option>
                            </select>
                        </div>

                        <div class="form-group">
                            <?= \Core\CSRF::fields(); ?>
                            <button class="btn btn-block btn-warning"><?= \Core\Language::get('validate') ?></button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= \Core\Language::get('close') ?></button>
                </div>
            </div>
        </div>
    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/dist/js/adminlte.js"></script>
</body>
</html>
