<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('administration') ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
<link rel="stylesheet" href="/dist/css/adminlte.css">
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/administration"><?= \Core\Language::get('home') ?></a></li>
                            <li class="breadcrumb-item"><a href="/administration/warehouses"><?= \Core\Language::get('warehouses') ?></a></li>
                            <li class="breadcrumb-item active"><?= \Core\Language::get('products_categories') ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title"><?= \Core\Language::get('products_categories_drivncook') ?></h3>
                        </div>
                        <div class="card-body">
                            <table id="categories" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th><?= \Core\Language::get('name') ?></th>
                                    <th><?= \Core\Language::get('parents_categories') ?></th>
                                    <th><?= \Core\Language::get('action') ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($categories as $category): ?>
                                    <tr>
                                        <td><?= $category->getName(); ?></td>
                                        <td>
                                            <?= (empty($category->parents)) ? '/' : ''; ?>
                                            <?php foreach ($category->parents as $parent): ?>
                                                <?= $parent->getName(); ?> /
                                            <?php endforeach; ?>
                                        </td>
                                        <td>
                                            <a href="#" class="btn btn-sm btn-info" data-toggle="modal" data-target="#renameModal<?= $category->getId(); ?>">
                                                <i class="fas fa-pencil-alt"></i> Modifier
                                            </a>
                                            <a href="#" class="btn btn-sm btn-danger">
                                                <i class="fas fa-trash"></i> <?= \Core\Language::get("delete") ?>
                                            </a>
                                        </td>
                                    </tr>

                                    <div class="modal fade" id="renameModal<?= $category->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="renameModal<?= $category->getId(); ?>Title" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle"><?= \Core\Language::get('edit_category') ?> <b><?= $category->getName(); ?></b></h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?= \Core\Language::get('close') ?>">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <form role="form" action="/administration/stocks/category/<?= $category->getId(); ?>/edit" method="POST">

                                                        <div class="form-group">
                                                            <label for="nameInput<?= $category->getId(); ?>"><?= \Core\Language::get('category_name_must_uniq_label') ?></label>
                                                            <input type="text" value="<?= $category->getName(); ?>" class="form-control" id="nameInput<?= $category->getId(); ?>" placeholder="<?= \Core\Language::get('name') ?>" name="name">
                                                        </div>

                                                        <div class="form-group">
                                                            <label for="parentCategory<?= $category->getId(); ?>"><?= \Core\Language::get('edit_parent_category') ?></label>
                                                            <select id="parentCategory<?= $category->getId(); ?>" class="form-control select2 <?= (isset($fields['parent'])) ? 'is-invalid' : ''; ?>" name="parent" style="width: 100%;">
                                                                <option selected="selected" value="0">--- <?= \Core\Language::get('select_category') ?> ---</option>
                                                                <?php foreach ($categories as $cat): ?>
                                                                    <?php if($cat->getId() != $category->getId()) {  ?>
                                                                        <option <?= (!is_null($category->getParent()) && $cat->getId() == $category->getParent()->getId()) ? 'selected="selected"' : ''; ?> value="<?= $cat->getId(); ?>">
                                                                            <?php foreach ($cat->parents as $par): ?>
                                                                                <?= $par->getName(); ?> /
                                                                            <?php endforeach; ?>

                                                                            <?= $cat->getName(); ?>

                                                                        </option>
                                                                    <?php } ?>
                                                                <?php endforeach; ?>
                                                            </select>
                                                        </div>

                                                        <div class="form-group">
                                                            <?= \Core\CSRF::fields(); ?>
                                                            <button class="btn btn-warning btn-block"><?= \Core\Language::get('save') ?></button>
                                                        </div>
                                                    </form>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= \Core\Language::get('close') ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th><?= \Core\Language::get('name') ?></th>
                                    <th><?= \Core\Language::get('parents_categories') ?></th>
                                    <th><?= \Core\Language::get('action') ?></th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>


</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/plugins/select2/js/select2.full.min.js"></script>
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="/dist/js/adminlte.min.js"></script>
<script src="/dist/js/demo.js"></script>
<script>

    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2({
            theme: 'bootstrap4'
        })

        $("#categories").DataTable({
            language: {
                url: '<?= \Core\Language::get("datatable_trad_link") ?>'
            }
        });
    });
</script>
</body>
</html>
