<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - <?= \Core\Language::get('administration') ?></title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
<link rel="stylesheet" href="/dist/css/adminlte.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/administration"><?= \Core\Language::get('home') ?></a></li>
                            <li class="breadcrumb-item active"><?= \Core\Language::get('trucks') ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title"><?= \Core\Language::get('trucks_drivncook') ?></h3>
                        </div>
                        <div class="card-body">
                            <table id="trucks" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th><?= \Core\Language::get('truck') ?></th>
                                    <th><?= \Core\Language::get('longitude') ?></th>
                                    <th><?= \Core\Language::get('latitude') ?></th>
                                    <th><?= \Core\Language::get('created_at') ?></th>
                                    <th><?= \Core\Language::get("status") ?></th>
                                    <th><?= \Core\Language::get('action') ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($trucks)) {
                                        foreach ($trucks as $truck): ?>
                                            <tr>
                                                <td><?= $truck->getId(); ?></td>
                                                <td>
                                                    <?= $truck->getMatriculation(); ?>
                                                    <?php if(isset($truck->user)) {?>
                                                        <br>
                                                        <small>
                                                            <a href="/administration/franchises/<?= $truck->user->getId(); ?>/edit">
                                                                <b><?= $truck->user->getSocietyName() . '</b> ( ' . $truck->user->getFirstname() . ' ' . $truck->user->getLastname() . ' )'; ?>
                                                            </a>
                                                        </small>
                                                    <?php } ?>
                                                </td>
                                                <td><?= $truck->getLongitude(); ?></td>
                                                <td><?= $truck->getLatitude(); ?></td>
                                                <td><?= $truck->getCreatedAt()->format('d/m/Y H:i:s'); ?></td>
                                                <td>
                                                    <!-- BADGE -->
                                                    <?php if(isset($truck->user)) { ?>
                                                        <span class="badge bg-info"><?= \Core\Language::get('assign') ?></span>
                                                    <?php } else if(isset($truck->maintenance)) { ?>
                                                        <span class="badge bg-danger"><?= \Core\Language::get('maintenance') ?></span>
                                                    <?php } else if(!$truck->getActive()) { ?>
                                                        <span class="badge bg-danger"><?= \Core\Language::get('inactif') ?></span>
                                                    <?php } else { ?>
                                                        <span class="badge bg-success"><?= \Core\Language::get('available') ?></span>
                                                    <?php } ?>
                                                </td>
                                                <td>
                                                    <!-- Redirige vers la page d'informations du camion -->
                                                    <a class="btn btn-info btn-sm" href="/administration/trucks/<?= $truck->getId(); ?>/informations"><i class="fas fa-info-circle"></i> <?= \Core\Language::get('informations') ?></a>

                                                    <!-- Si coordonnées invalides -->
                                                    <?php if(is_float($truck->getLatitude()) && is_float($truck->getLongitude())){ ?>
                                                        <!-- Lien vers l'API Google Map -->
                                                        <a class="btn btn-success btn-sm" target="_blank" href="https://www.google.com/maps/search/?api=1&query=<?= $truck->getLatitude(); ?>,<?= $truck->getLongitude(); ?>"><i class="fas fa-map"></i> <?= \Core\Language::get('location') ?></a>
                                                    <?php } ?>

                                                    <!-- Si pas d'utilisateur lié au camion -->
                                                    <?php if(!isset($truck->user) && $truck->getActive()) { ?>
                                                        <!-- PARTIE PERMETTANT L'ASSIGNATION DU CAMION A UN USER -->
                                                        <button data-toggle="modal" data-target="#assignModal<?= $truck->getId(); ?>" class="btn btn-warning btn-sm">
                                                            <i class="fas fa-users"></i> Assigner
                                                        </button>
                                                        <div class="modal fade" id="assignModal<?= $truck->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="assignModal<?= $truck->getId(); ?>Title" aria-hidden="true">
                                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                                <div class="modal-content">
                                                                    <div class="modal-header">
                                                                        <h5 class="modal-title" id="exampleModalLongTitle"><?= \Core\Language::get('assign_truck_immat_to_user', [$truck->getMatriculation()]) ?></h5>
                                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?= \Core\Language::get('close') ?>">
                                                                            <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                                    </div>
                                                                    <div class="modal-body">
                                                                        <form role="form" action="/administration/trucks/assign/<?= $truck->getId(); ?>" method="POST">
                                                                            <div class="form-group">
                                                                                <label for="assignToInput<?= $truck->getId(); ?>"><?= \Core\Language::get('assign_truck_to_user') ?></label>
                                                                                <select id="assignToInput<?= $truck->getId(); ?>" class="form-control select2 <?= (isset($fields['assign'])) ? 'is-invalid' : ''; ?>" name="assign" style="width: 100%;">
                                                                                    <option selected="selected" disabled="disabled">--- <?= \Core\Language::get('select_franchise') ?> ---</option>
                                                                                    <?php if(isset($availableFranchise)) { ?>
                                                                                        <?php foreach ($availableFranchise as $franchise): ?>
                                                                                            <option value="<?= $franchise->getId(); ?>"><?= $franchise->getFirstname(); ?> <?= $franchise->getLastname(); ?></option>
                                                                                        <?php endforeach; ?>
                                                                                    <?php } ?>
                                                                                </select>
                                                                            </div>

                                                                            <div class="form-group">
                                                                                <?= \Core\CSRF::fields(); ?>
                                                                                <button class="btn btn-warning btn-block"><?= \Core\Language::get('save') ?></button>
                                                                            </div>
                                                                        </form>
                                                                    </div>
                                                                    <div class="modal-footer">
                                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= \Core\Language::get('close') ?></button>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <!-- BOUTON RENDRE INACTIF LE CAMION -->
                                                        <form method="POST" onclick="return confirm('<?= \Core\Language::get("confirm_put_truck_inactive") ?>')" style="display: inline" action="/administration/trucks/inactive/<?= $truck->getId(); ?>">
                                                            <?= \Core\CSRF::fields(); ?>
                                                            <button class="btn btn-danger btn-sm">
                                                                <i class="fas fa-ban"></i> <?= \Core\Language::get("put_inactive") ?>
                                                            </button>
                                                        </form>
                                                    <?php } ?>

                                                    <?php if(isset($truck->user)) { ?>
                                                        <form method="POST" onclick="return confirm('<?= \Core\Language::get("confirm_put_truck_inactive") ?>')" style="display: inline" action="/administration/trucks/assign/remove/<?= $truck->getId(); ?>">
                                                            <?= \Core\CSRF::fields(); ?>
                                                            <button class="btn btn-warning btn-sm">
                                                                <i class="fas fa-users"></i> <?= \Core\Language::get("deassign") ?>
                                                            </button>
                                                        </form>
                                                    <?php } ?>

                                                    <?php if(!$truck->getActive()) { ?>
                                                        <form method="POST" onclick="return confirm('<?= \Core\Language::get("confirm_put_truck_active") ?>')" style="display: inline" action="/administration/trucks/active/<?= $truck->getId(); ?>">
                                                            <?= \Core\CSRF::fields(); ?>
                                                            <button class="btn btn-danger btn-sm">
                                                                <i class="fas fa-plus"></i> <?= \Core\Language::get("put_active") ?>
                                                            </button>
                                                        </form>
                                                    <?php } ?>
                                                </td>
                                            </tr>
                                        <?php endforeach;
                                    } ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th><?= \Core\Language::get('truck') ?></th>
                                    <th><?= \Core\Language::get('longitude') ?></th>
                                    <th><?= \Core\Language::get('latitude') ?></th>
                                    <th><?= \Core\Language::get('created_at') ?></th>
                                    <th><?= \Core\Language::get("status") ?></th>
                                    <th><?= \Core\Language::get('action') ?></th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>


</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/plugins/select2/js/select2.full.min.js"></script>
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="/dist/js/adminlte.min.js"></script>
<script>
    $(function () {
        $('.select2').select2({
            theme: 'bootstrap4'
        })

    });

    $("#trucks").DataTable({
        language: {
            url: '<?= \Core\Language::get("datatable_trad_link") ?>'
        }
    });
</script>
</body>
</html>
