<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - Administration</title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/administration">Accueil</a></li>
                            <li class="breadcrumb-item active">Entrepôts</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Les entrepôts Driv'n'Cook</h3>
                        </div>
                        <div class="card-body">
                            <table id="warehouses" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>Nom</th>
                                    <th>Localisation</th>
                                    <th>Total de produits</th>
                                    <th>Quantité totale</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($warehouses as $warehouse): ?>
                                        <tr>
                                            <td><?= $warehouse->getName(); ?></td>
                                            <td>
                                                <a href="https://maps.google.com/?q=<?= $warehouse->getLocation(); ?>">
                                                    <?= $warehouse->getLocation(); ?>
                                                </a>
                                            </td>
                                            <td><?= $warehouse->total; ?></td>
                                            <td><?= $warehouse->quantityTotal; ?></td>
                                            <td>
                                                <a class="btn btn-sm btn-success" href="/administration/stocks/warehouses/<?= $warehouse->getId(); ?>"><i class="fas fa-eye"></i> Voir</a>

                                                <a class="btn btn-sm btn-info" href="/administration/warehouses/<?= $warehouse->getId(); ?>/supply"><i class="fas fa-plus"></i> Approvisionner</a>

                                                <a href="#" data-toggle="modal" data-target="#modalEdit<?= $warehouse->getId(); ?>" class="btn btn-warning btn-sm"><i class="fa fa-pencil-alt"></i> Editer</a>

                                                <a class="btn btn-sm btn-danger" href="/administration/warehouses/<?= $warehouse->getId(); ?>/delete"><i class="fas fa-trash"></i> Supprimer</a>
                                            </td>
                                        </tr>

                                        <div class="modal fade" id="modalEdit<?= $warehouse->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="modalEdit<?= $warehouse->getId(); ?>Title" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLongTitle">Modifier l'entrepôt de <b><?= $warehouse->getName(); ?></b></h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <form method="POST" action="/administration/warehouses/<?= $warehouse->getId(); ?>/edit">
                                                            <div class="form-group">
                                                                <label for="name<?= $warehouse->getId(); ?>">Nom de l'entrepôt</label>
                                                                <input type="text" class="form-control" id="name<?= $warehouse->getId(); ?>" name="name" value="<?= $warehouse->getName(); ?>">
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="locate<?= $warehouse->getId(); ?>">Localisation</label>
                                                                <input type="text" class="form-control" id="locate<?= $warehouse->getId(); ?>" name="location" value="<?= $warehouse->getLocation(); ?>">
                                                            </div>
                                                            <div class="form-group">
                                                                <?= \Core\CSRF::fields(); ?>
                                                                <button class="btn btn-block btn-warning">Sauvegarder</button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>Nom</th>
                                    <th>Localisation</th>
                                    <th>Quantité de stocks</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020 Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>

    <aside class="control-sidebar control-sidebar-dark">
    </aside>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="/dist/js/adminlte.min.js"></script>
<script src="/dist/js/demo.js"></script>
<script>
    $(function () {
        $("#warehouses").DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json'
            }
        });
    });
</script>
</body>
</html>
