<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <?php if(!$invoice->getStatus() && ($user == $invoice->getUser())) { ?>
                    <div class="alert alert-info alert-dismissible no-print">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-info"></i> Rappel</h5>
                        Cette facture n'a pas encore été réglée.
                        Rendez-vous sur <a href="/panel/invoices/pay/<?= $invoice->getId(); ?>">cette page</a> pour régler la somme dûe.
                    </div>
                <?php } ?>
                <div class="invoice p-3 mb-3">
                    <div class="row">
                        <div class="col-12">
                            <h4>
                                <i class="fas fa-globe"></i> Driv'n'Cook
                                <small class="float-right"><?= \Core\Language::get('date') ?>: <?= $invoice->getCreatedAt()->format('d/m/Y'); ?></small>
                            </h4>
                        </div>
                    </div>
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            De
                            <?php if($invoice->getOwner() == $user->getSocietyName()) { ?>
                                <address>
                                    <strong><?= $user->getSocietyName(); ?></strong><br>
                                    <?= $user->getAddressLine(); ?><br>
                                    <?= $user->getAddressCity(); ?>, <?= $user->getPostalCode(); ?><br>
                                    <?= $user->getCountry(); ?>, <?= $user->getAddressState(); ?>
                                </address>
                            <?php } ?>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            A
                            <?php if($invoice->getOwner() == $user->getSocietyName()) { ?>
                                <address>
                                    <strong><?= $invoice->getCustomer()->getLastName() . ' ' . $invoice->getCustomer()->getFirstName(); ?></strong>
                                </address>
                            <?php } ?>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <b><?= \Core\Language::get('invoice') ?> DVN-<?= $invoice->getId(); ?></b><br>
                            <br>
                            <?php if(!is_null($invoice->getWarehouse())) { ?>
                                <b><?= \Core\Language::get('warehouse') ?></b> : <?= $invoice->getWarehouse()->getName(); ?>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th><?= \Core\Language::get('product') ?></th>
                                    <th><?= \Core\Language::get('quantity') ?></th>
                                    <th><?= \Core\Language::get('price_unit') ?></th>
                                    <th><?= \Core\Language::get('tva') ?></th>
                                    <th><?= \Core\Language::get('subtotal') ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $total = [];
                                $totalHt = 0;
                                ?>
                                <?php foreach ($lines as $line): ?>
                                    <?php $subtotal = $line->getPrice() * $line->getQuantity(); ?>
                                    <tr>
                                        <td><?= $line->getText(); ?></td>
                                        <td><?= $line->getQuantity(); ?></td>
                                        <td><?= number_format($line->getPrice(), 2); ?>€</td>
                                        <td><?= number_format($line->getTva(), 2); ?>%</td>
                                        <td>
                                            <?= $subtotal; ?>€
                                        </td>
                                    </tr>

                                    <?php
                                    if(!isset($total[$line->getTva()])) $total[$line->getTva()] = 0;
                                    $total[$line->getTva()] += $subtotal;
                                    $totalHt += $subtotal;
                                    ?>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6"></div>
                        <div class="col-md-6">

                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th style="width:50%"><?= \Core\Language::get('total_ht') ?>:</th>
                                        <td><?= number_format($totalHt, 2); ?>€</td>
                                    </tr>
                                    <?php $totalTva = 0; ?>
                                    <?php foreach ($total as $key => $value): if($key == 5) $key = 5.5; ?>
                                        <?php $tva = $value * ($key / 100); $totalTva += $tva; ?>
                                        <tr>
                                            <th style="width:50%"><?= \Core\Language::get('tva') ?> (<?= number_format($key, 1); ?>%):</th>
                                            <td><?= number_format($tva, 2); ?>€</td>
                                        </tr>
                                    <?php endforeach; ?>
                                    <tr>
                                        <th><?= \Core\Language::get('total_ttc') ?>:</th>
                                        <td><?= number_format($totalHt + $totalTva, 2); ?>€</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="row no-print">
                        <div class="col-12">
                            <button onclick="window.addEventListener('load', window.print())" class="btn btn-info"><i class="fas fa-print"></i> <?= \Core\Language::get('print') ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
