<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/panel" class="nav-link <?= (isset($page) && $page == "index") ? 'active' : ''; ?>"><?= \Core\Language::get('home') ?></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/panel/my-account" class="nav-link <?= (isset($page) && $page == "my_account") ? 'active' : ''; ?>"><?= \Core\Language::get('my_account') ?></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/panel/logout" class="nav-link"><?= \Core\Language::get('logout') ?></a>
        </li>
        <li class="nav-item dropdown">
            <?php if (!empty($_COOKIE['language']) && $_COOKIE['language'] == "fr_FR") { ?>
                <a href="#" class="nav-link dropdown-toggle" id="droplangdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="flag-icon flag-icon-fr"> </span> Français</a>
            <?php } else { ?>
                <a href="#" class="nav-link dropdown-toggle" id="droplangdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="flag-icon flag-icon-us"> </span> English</a>
            <?php } ?>
            <div class="dropdown-menu" aria-labelledby="droplangdown">
                <?php if (!empty($_COOKIE['language']) && $_COOKIE['language'] == "fr_FR") { ?>
                    <a class="dropdown-item" href="/lang/pref/en"><span class="flag-icon flag-icon-us"> </span> English</a>
                <?php } else { ?>
                    <a class="dropdown-item" href="/lang/pref/fr"><span class="flag-icon flag-icon-fr"> </span> Français</a>
                <?php } ?>
            </div>
        </li>
    </ul>
</nav>

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="/panel" class="brand-link">
        <img src="/dist/img/drivncook.png" alt="Driv'n'Cook Logo" class="brand-image img-circle elevation-3">
        <span class="brand-text font-weight-light">Driv'n'Cook</span>
    </a>

    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="/panel/my-account" class="d-block"><?= $user->getSocietyName(); ?></a>
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="/panel" class="nav-link <?= (isset($page) && $page == "index") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-home"></i>
                        <p>
                            <?= \Core\Language::get('home') ?>
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/panel/commands" class="nav-link <?= (isset($page) && $page == "commands") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-shopping-basket"></i>
                        <p>
                            Commandes
                        </p>
                    </a>
                </li>

                <li class="nav-header"><?= \Core\Language::get('sidebar_service') ?></li>

                <li class="nav-item">
                    <a href="/panel/truck" class="nav-link <?= (isset($page) && $page == "truck") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-truck"></i>
                        <p>
                            <?= \Core\Language::get('my_truck') ?>
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/panel/truck/supply" class="nav-link <?= (isset($page) && $page == "truck_supply") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-warehouse"></i>
                        <p>
                            <?= \Core\Language::get('sidebar_supply') ?>
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/panel/card" class="nav-link <?= (isset($page) && in_array($page, ['card/edit', 'card'])) ? 'active' : '' ?>">
                        <i class="nav-icon fas fa-hamburger"></i>
                        <p>
                            <?= \Core\Language::get('menus') ?>
                        </p>
                    </a>
                </li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['franchises'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['franchises'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-dollar-sign"></i>
                        <p>
                            <?= \Core\Language::get('promotions') ?>
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link <?= (isset($page) && $page == "franchises") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('my_promotions') ?>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link <?= (isset($page) && $page == "franchises") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('add_promotion') ?>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="/panel/event" class="nav-link">
                        <i class="nav-icon fas fa-calendar-week"></i>
                        <p>
                            <?= \Core\Language::get('event'); ?>
                        </p>
                    </a>
                </li>

                <li class="nav-header"><?= \Core\Language::get('sidebar_settings') ?></li>

                <li class="nav-item">
                    <a href="/panel/my-account" class="nav-link <?= (isset($page) && $page == "my_account") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-user"></i>
                        <p>
                            <?= \Core\Language::get('my_account') ?>
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/panel/online-payment" class="nav-link <?= (isset($page) && $page == "online_payment") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-dollar-sign"></i>
                        <p>
                            <?= \Core\Language::get('online_payments') ?>
                        </p>
                    </a>
                </li>

                <li class="nav-header"><?= \Core\Language::get('sidebar_administration') ?></li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['invoices', 'invoices_received', 'invoices_issued'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['invoices', 'invoices_received', 'invoices_issued'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-file-contract"></i>
                        <p>
                            <?= \Core\Language::get('facturation') ?>
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/panel/invoices/received" class="nav-link <?= (isset($page) && $page == "invoices_received") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('invoices_received') ?>
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link <?= (isset($page) && $page == "invoices_issued") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>
                                    <?= \Core\Language::get('invoices_issued') ?>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</aside>