<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/panel" class="nav-link <?= (isset($page) && $page == "index") ? 'active' : ''; ?>">Accueil</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/panel/my-account" class="nav-link <?= (isset($page) && $page == "my_account") ? 'active' : ''; ?>">Mon compte</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/panel/logout" class="nav-link">Déconnexion</a>
        </li>
    </ul>
</nav>

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="/panel" class="brand-link">
        <img src="/dist/img/drivncook.png" alt="Driv'n'Cook Logo" class="brand-image img-circle elevation-3">
        <span class="brand-text font-weight-light">Driv'n'Cook</span>
    </a>

    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="/panel/my-account" class="d-block"><?= $user->getSocietyName(); ?></a>
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="/panel" class="nav-link <?= (isset($page) && $page == "index") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-home"></i>
                        <p>
                            Accueil
                        </p>
                    </a>
                </li>

                <li class="nav-header">SERVICES</li>

                <li class="nav-item">
                    <a href="/panel/truck" class="nav-link <?= (isset($page) && $page == "truck") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-truck"></i>
                        <p>
                            Mon camion
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/panel/truck/supply" class="nav-link <?= (isset($page) && $page == "truck_supply") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-warehouse"></i>
                        <p>
                            Approvisionnement
                        </p>
                    </a>
                </li>

                <!--<li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['truck', 'truck_supply'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['truck', 'truck_supply'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-truck"></i>
                        <p>
                            Camion
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/panel/truck" class="nav-link <?= (isset($page) && $page == "truck") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Mon camion</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/panel/truck/supply" class="nav-link <?= (isset($page) && $page == "truck_supply") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Approvisionnement</p>
                            </a>
                        </li>
                    </ul>
                </li>-->

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['franchises'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['franchises'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-hamburger"></i>
                        <p>
                            Menus
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link <?= (isset($page) && $page == "franchises") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Mes menus</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link <?= (isset($page) && $page == "franchises") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Ajouter un menu</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['franchises'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['franchises'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-dollar-sign"></i>
                        <p>
                            Promotions
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link <?= (isset($page) && $page == "franchises") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Mes promotions</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link <?= (isset($page) && $page == "franchises") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Ajouter une promotion</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-header">PARAMETRES</li>

                <li class="nav-item">
                    <a href="/panel/my-account" class="nav-link <?= (isset($page) && $page == "my_account") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-user"></i>
                        <p>
                            Mon compte
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/panel/online-payment" class="nav-link <?= (isset($page) && $page == "online_payment") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-dollar-sign"></i>
                        <p>
                            Paiements en ligne
                        </p>
                    </a>
                </li>

                <li class="nav-header">ADMINISTRATION</li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['invoices', 'invoices_received', 'invoices_issued'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['invoices', 'invoices_received', 'invoices_issued'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-file-contract"></i>
                        <p>
                            Facturation
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/panel/invoices/received" class="nav-link <?= (isset($page) && $page == "invoices_received") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Factures reçues</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link <?= (isset($page) && $page == "invoices_issued") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Factures émises</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview <?= (isset($page) && in_array($page, ['franchises'])) ? 'menu-open' : ''; ?>">
                    <a href="#" class="nav-link <?= (isset($page) && in_array($page, ['franchises'])) ? 'active' : ''; ?>">
                        <i class="nav-icon fas fa-chart-area"></i>
                        <p>
                            Ventes
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link <?= (isset($page) && $page == "franchises") ? 'active' : ''; ?>">
                                <i class="far fa-circle nav-icon"></i>
                                <p>TODO</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</aside>
