<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-about">
                <div class="container">
                    <div class="title-wrapper">
                        <div data-top="transform: translateY(0px);opacity:1;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title">A propos</div>
                        <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                        <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle">Mieux se connaître pour un avenir de confiance</div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="ab-timeline-section padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="swin-sc swin-sc-title style-2">
                            <h3 class="title"><span>Notre histoire</span></h3>
                        </div>
                        <div data-item="3" class="swin-sc swin-sc-timeline-2">
                            <div class="main-slider">
                                <div class="slides">
                                    <div class="timeline-item item swin-transition">
                                        <div class="timeline-item-wrap"><span class="timeline-year swin-transition">2018</span></div><img src="assets/images/timeline/timeline-1.jpg" alt="drivncook" class="img img-responsive">
                                    </div>
                                    <div class="timeline-item item swin-transition">
                                        <div class="timeline-item-wrap"><span class="timeline-year swin-transition">2019</span></div><img src="assets/images/timeline/timeline-2.jpg" alt="drivncook" class="img img-responsive">
                                    </div>
                                    <div class="timeline-item item swin-transition">
                                        <div class="timeline-item-wrap"><span class="timeline-year swin-transition">2020</span></div><img src="assets/images/timeline/timeline-3.jpg" alt="drivncook" class="img img-responsive">
                                    </div>
                                </div>
                            </div>
                            <div class="nav-slider">
                                <div class="slides">
                                    <div class="timeline-content-item">
                                        <p class="timeline-heading"><strong>03.09.2018:</strong>Le commencement</p>
                                        <div class="timeline-content-detail">
                                            <p>Début septembre 2018, une grande histoire a commencée, une histoire où l'on apprend toutes les bases nécessaires pour construire un empire tel que Driv'N'Cook.</p>
                                            <p>L'infrastructure de nos services, l'aspect marketing et commercial que Driv'N'Cook, toutes ces choses qui ont été apprises et vues en classe au sein de l'ESGI.</p>
                                        </div>
                                    </div>
                                    <div class="timeline-content-item">
                                        <p class="timeline-heading"><strong>03.03.2019:</strong>Les premiers tests</p>
                                        <div class="timeline-content-detail">
                                            <p>Des premiers tests ont été effectués, chaque personne travaillant pour Driv'N'Cook a un passé et des projets, nous avons tous commencer en cette date.</p>
                                        </div>
                                    </div>
                                    <div class="timeline-content-item">
                                        <p class="timeline-heading"><strong>16.01.2020:</strong>Les choses se compliquent</p>
                                        <div class="timeline-content-detail">
                                            <p>Driv'N'Cook devient la franchise numéro 1 des Food Trucks en europe occidentale, ce qui fait de nous une référence, et qui dit référence, dit pas le droit à l'erreur.</p>
                                            <p>Nous avons près de 87.000 franchisés partout dans le monde, prêt à vous désservir leurs délicieux plats et vous faire connaître leur culture.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -150px;" class="ab-testimonial-section padding-top-100 padding-bottom-100">
                    <div class="container"><img src="assets/images/background/ab_team_01.png" alt="" class="img-left img-bg img-deco img-responsive">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-4">
                                <div class="swin-sc swin-sc-testimonial style-2 option-2">
                                    <div class="main-slider flexslider">
                                        <div class="slides">
                                            <div class="testi-item item"><i class="testi-icon fa fa-quote-left"></i>
                                                <div class="testi-content">
                                                    <p>Les infrastructures de Driv'N'Cook sont complexes et le moindre bug peut s'avérer très impactant pour le système économique. C'est pour cela que nous avons recruté en masse des développeurs sortant de l'ESGI pour un total estimé de 5.000.000€ d'investissement.</p>
                                                </div><img src="assets/images/testi/testi-signal.png" alt="" class="testi-signal">
                                                <div class="testi-info"><span class="name">Maxime LE HENAFF</span> <span class="position">Directeur de la section R&D</span></div>
                                            </div>
                                            <div class="testi-item item"><i class="testi-icon fa fa-quote-left"></i>
                                                <div class="testi-content">
                                                    <p>Le modèle économique sur lequel se repose Driv'N'Cook est unique et permet un assouplissement des charges sur le long terme, que ce soit pour nous ou pour les franchisés. Ce qui fait de nous la société de franchise la plus prolifique. </p>
                                                </div><img src="assets/images/testi/testi-signal.png" alt="" class="testi-signal">
                                                <div class="testi-info"><span class="name">Swann HERRERA</span> <span class="position">Directeur marketing et commercial</span></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="counter-section-03 padding-top-100 padding-bottom-100">
                    <div class="container"><img src="assets/images/background/vegetable_01.png" alt="" class="img-left img-bg img-responsive"><img src="assets/images/background/vegetable_02.png" alt="" class="img-right img-bg img-responsive">
                        <div class="swin-sc swin-sc-counter">
                            <div class="row">
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div class="counter-info item"><span data-from="600000" data-to="698544" data-speed="1500" data-refresh-interval="5" class="number timer">0</span><span class="caption">/plats</span></div>
                                    <div class="counter-avatar"><img src="assets/images/counter-1.png" alt="drivncook" class="img img-responsive"></div>
                                </div>
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div class="counter-info item"><span data-from="3874000" data-to="3874598" data-speed="3000" data-refresh-interval="5" class="number timer">0</span><span class="caption">/clients</span></div>
                                    <div class="counter-avatar"><img src="assets/images/counter-2.png" alt="drivncook" class="img img-responsive"></div>
                                </div>
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div class="counter-info item"><span data-from="8000" data-to="9000" data-speed="3000" data-refresh-interval="5" class="number timer">0</span><span class="caption">/heures en cuisine</span></div>
                                    <div class="counter-avatar"><img src="assets/images/counter-3.png" alt="drivncook" class="img img-responsive"></div>
                                </div>
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div class="counter-info item"><span data-from="87000" data-to="87545" data-speed="3000" data-refresh-interval="5" class="number timer">0</span><span class="caption">/food trucks</span></div>
                                    <div class="counter-avatar"><img src="assets/images/counter-4.png" alt="drivncook" class="img img-responsive"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <?php require "assets/footer.phtml"; ?>
    </div>
    <?php require "assets/loader.phtml"; ?>
</div>
<?php require "assets/dependancies.phtml"; ?>

</body>
</html>