<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>
<link rel="stylesheet" href="/dist/css/jquery.datetimepicker.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
        crossorigin="anonymous"></script>
<script defer src="/dist/js/jquery.datetimepicker.full.min.js"></script>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-blog">
                <div class="container">
                    <div class="title-wrapper">
                        <div data-top="transform: translateY(0px);opacity:1;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title"><?= \Core\Language::get('trucks') ?></div>
                        <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                        <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle"><?= \Core\Language::get("Venez Voir les camion de la franchise Driv'N'Cook") ?></div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="swin-sc swin-sc-title style-2">
                            <h1 class="title"><span>Passer commande chez <b><?= htmlspecialchars(trim($truck->user->getSocietyName())); ?></b></span></h1>
                        </div>

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Catégorie</th>
                                    <th>Produit</th>
                                    <th>Prix (en €)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $total = 0; foreach ($items as $item): $total += $item['card_item_price']; ?>
                                    <tr>
                                        <td><?= $item['card_category_name']; ?></td>
                                        <td><?= $item['card_item_name']; ?></td>
                                        <td><?= number_format($item['card_item_price'], 2); ?>€</td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>Catégorie</th>
                                <th>Produit</th>
                                <th>Prix (en €)</th>
                            </tr>
                            </tfoot>
                        </table>

                        <h4 class="pull-right" style="font-weight: bold">Prix total : <?= number_format($total, 2) ?>€</h4>

                        <br><br>

                        <form method="POST">
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <input type="text" value="<?= $customer->getLastname(); ?>" disabled placeholder="Votre nom" class="form-control">
                                </div>
                                <div class="form-group col-md-6">
                                    <input type="text" value="<?= $customer->getFirstname(); ?>" disabled placeholder="Votre prénom" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" value="<?= $customer->getEmail(); ?>" disabled placeholder="Votre email" class="form-control">
                            </div>
                            <div class="form-group">
                                <div>
                                    <label for="datetime_input" style="<?= (isset($datetime_error) && !is_null($datetime_error)) ? 'color:red' : ''; ?>">Récupérer ma commande le :</label>
                                    <input type="datetime-local" id="datetime_input" value="<?= (isset($datetime_error) && !is_null($datetime_error)) ? $params['datetime'] : ''; ?>" name="datetime" class="form-control is-invalid">
                                </div>
                                <small class="form-text text-muted"><?= \Core\Language::get('La date doit être superieur a la date actuel et inférieure a 5 jours dans le future') ?></small>
                            </div>
                            <div class="form-group">
                                <textarea name="description" placeholder="Ajouter une description pour votre commande (allergies, préférence, changement dans le menu)" class="form-control" cols="30" rows="10"><?= (isset($datetime_error) && !is_null($datetime_error)) ? htmlspecialchars(trim($params['description'])) : ''; ?></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-block btn-primary">
                            </div>
                        </form>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
<?php require "assets/footer.phtml"; ?>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        $('#datetime_input').datetimepicker({
            format: 'Y-m-d H:m',
            inline: true
        });
    });
</script>
</body>
</html>