<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>

<link rel="stylesheet" href="/dist/css/picker.min.css">
<script defer src="/dist/js/picker.min.js"></script>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-blog">
                <div class="container">
                    <div class="title-wrapper">
                        <div data-top="transform: translateY(0px);opacity:1;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title"><?= \Core\Language::get('trucks') ?></div>
                        <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                        <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle"><?= \Core\Language::get("Venez Voir les camion de la franchise Driv'N'Cook") ?></div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="swin-sc swin-sc-title style-2">
                            <p class="top-title"><span><?= $card->getName(); ?></span></p>
                            <h1 class="title"><span>Passer commande chez <b><?= htmlspecialchars(trim($truck->user->getSocietyName())); ?></b></span></h1>
                        </div>

                        <?php if(!$isOpen) { ?>
                            <div class="alert alert-warning">
                                <strong><?= $user->getSocietyName(); ?></strong> est actuellement fermé, vous pouvez tout de même passer commande et réceptionner votre commande quand le camion sera de nouveau ouvert.
                            </div>
                        <?php } ?>

                        <h4>Horaires d'ouvertures</h4>
                        <ul class="list-group">
                            <?php foreach ($functions as $key => $day): ?>
                                <li class="list-group-item" style="<?= ($key == date('N')) ? 'font-weight:bold;' : ''; ?>">
                                    <?php switch ($key) {
                                        case 1:
                                            echo 'Lundi';
                                            break;
                                        case 2:
                                            echo 'Mardi';
                                            break;
                                        case 3:
                                            echo 'Mercredi';
                                            break;
                                        case 4:
                                            echo 'Jeudi';
                                            break;
                                        case 5:
                                            echo 'Vendredi';
                                            break;
                                        case 6:
                                            echo 'Samedi';
                                            break;
                                        default:
                                            echo 'Dimanche';
                                            break;
                                    } ?>
                                    : <?= call_user_func([$openings, $day['open']])->format('H:i'); ?>
                                    - <?= call_user_func([$openings, $day['close']])->format('H:i'); ?>
                                    <?php if(!$isOpen && $key == date('N')) { ?>
                                        (fermé)
                                    <?php } ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Catégorie</th>
                                    <th>Produit</th>
                                    <th>Prix (en €)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $total = 0; foreach ($items as $item): $total += $item['card_item_price']; ?>
                                    <tr>
                                        <td><?= $item['card_category_name']; ?></td>
                                        <td><?= $item['card_item_name']; ?></td>
                                        <td><?= number_format($item['card_item_price'], 2); ?>€</td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>Catégorie</th>
                                <th>Produit</th>
                                <th>Prix (en €)</th>
                            </tr>
                            </tfoot>
                        </table>

                        <h4 class="pull-right" style="font-weight: bold">Prix total : <?= number_format($total, 2) ?>€</h4>

                        <br><br>

                        <form method="POST">

                            <?php if(!empty($promotions)) { ?>

                                <div class="alert alert-info">
                                    <strong>Promotions en cours !</strong><br>
                                    Bonjour <?= $customer->getLastname(); ?> <?= $customer->getFirstname(); ?>, votre commande est eligible à certaines promotions. Vous pouvez en bénéficier ou non en selectionnant la promotion que vous souhaitez.<br>
                                    Celle-ci sera automatiquement appliquée à votre commande.
                                </div>

                                <label for="promotions" style="<?= (isset($promotion_error) && !is_null($promotion_error)) ? 'color:red' : ''; ?>">Selectionner une promotion :</label>
                                <select onchange="updateTotalAfterPromo()" name="promotions" class="form-control" id="promotions">
                                    <?php foreach ($promotions as $promotion): ?>
                                        <option data-value="0" value="0">--- Je ne souhaite pas bénéficier de promotions pour ma commande ---</option>
                                        <option data-value="<?= $promotion->getReducPercentage(); ?>" value="<?= $promotion->getId(); ?>">
                                            <?= $promotion->getName(); ?> - <?= number_format($promotion->getReducPercentage(), 2) . '%'; ?> de réduction sur votre commande (eligible pour les commandes dont le prix varie entre <?= number_format($promotion->getMinPrice(), 2) . '€'; ?> et <?= number_format($promotion->getMaxPrice(), 2) . '€'; ?>)
                                        </option>
                                    <?php endforeach; ?>
                                </select>

                                <br>
                                <h4 class="pull-right" style="font-weight: bold">Prix total après remise: <span id="new_price_reduc" data-total="<?= $total; ?>"><?= number_format($total, 2) ?>€</span></h4>

                                <br><hr><br>
                            <?php } ?>

                            <div class="row">
                                <div class="form-group col-md-6">
                                    <input type="text" value="<?= $customer->getLastname(); ?>" disabled placeholder="Votre nom" class="form-control">
                                </div>
                                <div class="form-group col-md-6">
                                    <input type="text" value="<?= $customer->getFirstname(); ?>" disabled placeholder="Votre prénom" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" value="<?= $customer->getEmail(); ?>" disabled placeholder="Votre email" class="form-control">
                            </div>
                            <div class="form-group">
                                <div>
                                    <label for="datetime_input" style="<?= (isset($datetime_error) && !is_null($datetime_error)) ? 'color:red' : ''; ?>">Récupérer ma commande le :</label>
                                    <input type="text" id="datetime_input" value="<?= date('Y-m-d H:i', strtotime('+ 2 hours')) ?>" name="datetime" class="form-control is-invalid">
                                </div>
                                <small style="<?= (isset($datetime_error) && !is_null($datetime_error)) ? 'color:red' : ''; ?>" class="form-text text-muted"><?= \Core\Language::get("La date doit être superieur à la date actuelle et inférieur à 5 jours dans le futur, veuillez notez les horaires d'ouverture du food truck.") ?></small>
                            </div>
                            <div class="form-group">
                                <textarea name="description" placeholder="Ajouter une description pour votre commande (allergies, préférence, changement dans le menu)" class="form-control" cols="30" rows="10"><?= (isset($datetime_error) && !is_null($datetime_error)) ? htmlspecialchars(trim($params['description'])) : ''; ?></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-block btn-primary">
                            </div>
                        </form>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
<?php require "assets/footer.phtml"; ?>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const datetimepicker = document.getElementById('datetime_input');
        let now = new Date();
        var picker = new Picker(datetimepicker, {
            format: 'YYYY-MM-DD HH:mm',
            text: {
                title: "Selectionnez une date de récupération (année / mois / jour / heure / minute)",
                cancel: 'Fermer',
                confirm: 'Ok',
                year: 'Année',
                month: 'Mois',
                day: 'Jour',
                hour: 'Heure',
                minute: 'Minute',
                second: 'Seconde',
                millisecond: 'Milliseconde',
            }
        });
    });

    <?php if(!empty($promotions)){ ?>
    function updateTotalAfterPromo() {
        let select = document.getElementById('promotions');
        let reduc = select.options[select.selectedIndex].getAttribute('data-value');

        let new_price_dom = document.getElementById('new_price_reduc');
        let priceBeforePromo = new_price_dom.getAttribute('data-total');

        let newPrice = priceBeforePromo - ((priceBeforePromo * reduc) / 100);

        new_price_dom.innerHTML = newPrice.toFixed(2) + "€";
    }

    updateTotalAfterPromo();
    <?php } ?>
</script>
</body>
</html>