<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-contact">
                <div class="container">
                    <div class="title-wrapper">
                        <div data-top="transform: translateY(0px);opacity:1;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title">Contact</div>
                        <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                        <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle"><?= \Core\Language::get("Vous souhaitez avoir plus d'informations sur nous ou avez une question pour devenir franchisé ? Vous êtes sur la bonne page") ?></div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="ct-info-section padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 col-sm-12">
                                <div class="swin-sc swin-sc-title style-2 text-left">
                                    <p class="title"><span><?= \Core\Language::get('contact_us') ?></span></p>
                                </div>
                                <div class="reservation-form style-02">
                                    <div class="swin-sc swin-sc-contact-form light mtl style-full">
                                        <?php if(isset($error)) { ?>
                                            <div class="alert alert-danger">
                                                <strong>Erreur</strong> ! Veuillez vérifier vos informations et réessayer.
                                            </div>
                                        <?php } ?>
                                        <?php if(isset($success)) { ?>
                                            <div class="alert alert-success">
                                                <strong>Succès</strong> ! Votre message a été envoyé, nous vous répondrons sous peu.
                                            </div>
                                        <?php } ?>
                                        <form method="POST">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-addon"><i class="fa fa-user"></i></div>
                                                    <input type="text" name="name" value="<?= (isset($params['name'])) ? htmlspecialchars(trim($params['name'])) : ''; ?>" placeholder="Nom Prénom" class="form-control">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                                                    <input type="text" name="email" value="<?= (isset($params['email'])) ? htmlspecialchars(trim($params['email'])) : ''; ?>" placeholder="Email" class="form-control">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <div class="fa fa-phone"></div>
                                                    </div>
                                                    <input type="text" name="phone" value="<?= (isset($params['phone'])) ? htmlspecialchars(trim($params['phone'])) : ''; ?>" placeholder="Téléphone" class="form-control">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <textarea placeholder="Message" name="message" class="form-control"><?= (isset($params['message'])) ? htmlspecialchars(trim($params['message'])) : ''; ?></textarea>
                                            </div>
                                            <div class="form-group">
                                                <div class="swin-btn-wrap">
                                                    <button class="swin-btn center form-submit"><span><?= \Core\Language::get('send') ?></span></button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="swin-sc swin-sc-title style-2 text-left">
                                    <p class="title"><span><?= \Core\Language::get('our_contact_details') ?></span></p>
                                </div>
                                <div class="swin-sc swin-sc-contact">
                                    <div class="media item">
                                        <div class="media-left">
                                            <div class="wrapper-icon"><i class="icons fa fa-map-marker"></i></div>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading title"><?= \Core\Language::get('head_office') ?></h4>
                                            <div class="description"><?= \Core\Language::get('242 rue du Faubourg Saint Antoine, 75012, Paris') ?></div>
                                        </div>
                                    </div>
                                    <div class="media item">
                                        <div class="media-left">
                                            <div class="wrapper-icon"><i class="icons fa fa-phone"></i></div>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading title"><?= \Core\Language::get('phone') ?></h4>
                                            <div class="description">(+33) 1 56 06 90 4</div>
                                        </div>
                                    </div>
                                    <div class="media item">
                                        <div class="media-left">
                                            <div class="wrapper-icon"><i class="icons fa fa-envelope"></i></div>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading title">Email</h4>
                                            <div class="description">
                                                <p>contact@drivncook.store</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <?php require "assets/footer.phtml"; ?>
    </div>
    <?php require "assets/loader.phtml"; ?>
</div>
<?php require "assets/dependancies.phtml"; ?>
</body>
</html>