<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-blog">
                <div class="container">
                    <div class="title-wrapper">
                        <div data-top="transform: translateY(0px);opacity:1;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title">Événements</div>
                        <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                        <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle">Retrouvez tous les événements Driv'N'Cook à venir</div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="row">
                            <div class="page-main col-md-8">
                                
                                <div class="blog-wrapper swin-sc-blog-list">
                                    <div class="swin-sc-blog-slider style-02">
                                        <div class="main-slider">
                                            <div class="slides">
                                                <?php foreach ($events as $event) : ?>
                                                    <?php if ($event->getType() == 'invite-only') continue; ?>
                                                    <div class="blog-item swin-transition" data-event="<?= $event->getId() ?>" id="event-<?= $event->getId() ?>">
                                                        <div class="blog-featured-img">
                                                            <div class="quote-format"><img src="<?= '/dist/uploads/event/' . $event->getId() . '/' . $event->getImage() ?>" alt="Image event <?= $event->getId() ?>" class="img img-responsive">
                                                                <div class="quote-text"><i class="fa fa-quote-left quote-icon"></i><?= $event->getType() ?></div>
                                                            </div>
                                                        </div>
                                                        <div class="blog-content">
                                                            <div class="blog-date"><span class="day"><?= $event->getStartAt()->format("d") ?></span><span class="month"><?= $event->getStartAt()->format("M") ?></span></div>
                                                            <h3 class="blog-title"><a href="#" class="swin-transition"><?= $event->getName() ?></a></h3>
                                                            <p class="blog-description"><?= \Core\Language::lang() == 'fr_FR' ? $event->getTextFr() : $event->getTextEn() ?></p>

                                                            <div class="blog-readmore"><a href="#" class="swin-transition"><?= \Core\Language::get("more_information") ?> <i class="fa fa-angle-double-right"></i></a></div>
                                                        </div>
                                                    </div>
                                                <?php endforeach ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="page-sidebar col-md-4">
                                <!-- search-->
                                <div class="swin-widget widget-search">
                                    <div class="title-widget">
                                        <form accept-charset="utf-8" id="search-form-event" class="search-form">
                                            <input type="search" placeholder="Rechercher" id="search-event" value="" class="search-input"><span class="search-submit"><i class="fa fa-search"></i></span>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <?php require "assets/footer.phtml"; ?>
    </div>
    <?php require "assets/loader.phtml"; ?>
</div>
<script>
    const eventNames = {<?php foreach($events as $event) {echo '"' .  $event->getName() . '":"' . $event->getId() . '",';} ?>};
    const form = document.getElementById("search-form-event");
    form.addEventListener('submit', e => e.preventDefault());
    const search = document.getElementById('search-event');
    search.addEventListener('keyup', e => {
        const result = Object.keys(eventNames).map(name => {
            lowerCaseName = name.toLowerCase();
            event = document.querySelector(`[data-event="${eventNames[name]}"]`)
            if (!event) return;
            if (lowerCaseName.indexOf(e.target.value.toLowerCase()) > -1) {
                event.style.display = 'block';
            } else {
                event.style.display = 'none';
            }
        });
    });
</script>
<?php require "assets/dependancies.phtml"; ?>
</body>
</html>