<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-blog">
                <div class="container">
                    <div class="title-wrapper">
                        <div data-top="transform: translateY(0px);opacity:1;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title">Événements</div>
                        <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                        <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle">Retrouvez tous les événements Driv'N'Cook à venir</div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="row">
                            <div class="page-main col-md-8">
                                <div class="blog-wrapper swin-sc-blog-list">
                                    <div class="swin-sc-blog-slider style-02">
                                        <div class="main-slider">
                                            <div class="slides">
                                                <div class="blog-item swin-transition">
                                                    <div class="blog-featured-img">
                                                        <div class="quote-format"><img src="assets/images/blog/blog-slider-6.jpg" alt="drivncook" class="img img-responsive">
                                                            <div class="quote-text"><i class="fa fa-quote-left quote-icon"></i>Le projet annuel, meilleur projet de l'année.</div>
                                                        </div>
                                                    </div>
                                                    <div class="blog-content">
                                                        <div class="blog-date"><span class="day">09</span><span class="month">Jui</span></div>
                                                        <h3 class="blog-title"><a href="#" class="swin-transition">Projet annuel.</a></h3>
                                                        <p class="blog-description">Cette fameuse étape à passer, inscrivez-vous à l'événement pour ne rien louper.</p>

                                                        <div class="blog-readmore"><a href="#" class="swin-transition">En savoir plus <i class="fa fa-angle-double-right"></i></a></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="page-sidebar col-md-4">
                                <!-- search-->
                                <div class="swin-widget widget-search">
                                    <div class="title-widget">
                                        <form accept-charset="utf-8" method="POST" class="search-form">
                                            <input type="search" placeholder="Rechercher" name="s" value="" class="search-input"><span class="search-submit"><i class="fa fa-search"></i></span>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <?php require "assets/footer.phtml"; ?>
    </div>
    <?php require "assets/loader.phtml"; ?>
</div>
<?php require "assets/dependancies.phtml"; ?>
</body>
</html>