<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>
<style>
    body {
        font-family: Helvetica, Arial, sans-serif;
    }

    table {
        width: 90%;
        margin: 0 auto;
        table-layout:fixed;
        border-collapse: collapse;
    }

    td {
        padding:1em 0 0 0;
        vertical-align:bottom;
        background-image:radial-gradient(black 1px, white 0px);
        background-size: 8px 8px;
        background-repeat:repeat-x;
        background-position: left bottom;
    }

    td:first-child {
        text-align: left;
        font-weight: 700;
    }

    td:first-child span {
        padding-right:.25em;
    }

    td:last-child {
        text-align:right;
        width:3em;
    }

    td:last-child span {
        padding-left:.25em;
    }

    .blog-item {
        margin-top: 15px
    }
</style>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-blog">
                <div class="container">
                    <div class="title-wrapper">
                        <div data-top="transform: translateY(0px);opacity:1;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title">Les menus</div>
                        <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                        <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle">Passez commande en avance en ligne</div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="swin-sc swin-sc-title style-2">
                            <h1 class="title"><span>Voir la carte de <?= $user->getSocietyName(); ?></span></h1>
                        </div>


                        <?php if($customer == false) { ?>

                            <div class="alert alert-info">
                                Vous devez être connecté pour passer commande. <br>
                                <a href="/customers/login">Cliquez-ici pour vous connecter.</a>
                            </div>

                        <?php } else { ?>
                            <div class="alert alert-warning">
                                <strong><?= $user->getSocietyName() ?></strong> est susceptible de proposer des promotions sur ses menus, toutefois vous vous apprêtez à commander des produits à l'unité. <br>
                                Veuillez vous rendre dans la page des menus pour éventuellement bénéficier d'une promotion.
                            </div>

                            <div class="alert alert-info">
                                Vous souhaitez commander un menu directement ? <a href="/trucks/menu/<?= $truck->getId(); ?>">Cliquez-ici</a>.
                            </div>
                        <?php } ?>

                        <form method="POST">
                            <div class="form-group">
                                <label for="items">Selectionnez des produits à commander : </label>
                                <select name="items[]" id="items" multiple class="form-control">
                                    <?php foreach ($items as $item): ?>
                                        <option data-price="<?= $item['card_item_price']; ?>" value="<?= $item['card_item_id']; ?>"><?= $item['card_name'] ?> \ <?= $item['card_item_name']; ?> (<?= number_format($item['card_item_price'], 2) ?>€)</option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="row">
                                <div class="form-group col-md-6">
                                    <input type="text" value="<?= $customer->getLastname(); ?>" disabled placeholder="Votre nom" class="form-control">
                                </div>
                                <div class="form-group col-md-6">
                                    <input type="text" value="<?= $customer->getFirstname(); ?>" disabled placeholder="Votre prénom" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" value="<?= $customer->getEmail(); ?>" disabled placeholder="Votre email" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="datetime_input" style="<?= (isset($datetime_error) && !is_null($datetime_error)) ? 'color:red' : ''; ?>">Récupérer ma commande le :</label>
                                <input type="datetime-local" id="datetime_input" value="<?= (isset($datetime_error) && !is_null($datetime_error)) ? $params['datetime'] : ''; ?>" name="datetime" class="form-control is-invalid">
                            </div>
                            <div class="form-group">
                                <textarea name="description" placeholder="Ajouter une description pour votre commande (allergies, préférence, changement dans le menu)" class="form-control" cols="30" rows="10"><?= (isset($datetime_error) && !is_null($datetime_error)) ? htmlspecialchars(trim($params['description'])) : ''; ?></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-block btn-primary">
                            </div>
                        </form>
                    </div>
                </section>
            </div>
        </div>
        <?php require "assets/footer.phtml"; ?>
    </div>
    <?php require "assets/loader.phtml"; ?>
</div>
<?php require "assets/dependancies.phtml"; ?>
</body>
</html>