<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Driv'n'Cook - Food Trucks Restaurant</title>
        <meta NAME="description" CONTENT="Driv'n'Cook - Franchise de Food Trucks Restaurant Projet annuel ESGI2A">
        <meta NAME="keywords" CONTENT="esgi, drivncook, driv'n'cook, trucks, food, foods, truck, food truck restaurant">
        <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    </head>
    <body>
        <h1>Driv'n'Cook</h1>
        <h3>Driv'n'Cook est une franchise de Food Trucks restaurant</h3>
    </body>
</html>