<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div class="top-header top-bg-parallax">
                <div data-parallax="scroll" data-image-src="/assets/images/slider/slider2-bg1.jpg" class="slides parallax-window">
                    <div class="slide-content slide-layout-02">
                        <div class="container">
                            <div class="slide-content-inner"><img src="/assets/images/slider/slider2-icon.png" data-ani-in="fadeInUp" data-ani-out="fadeOutDown" data-ani-delay="500" alt="drivncook" class="slide-icon img img-responsive animated">
                                <h3 data-ani-in="fadeInUp" data-ani-out="fadeOutDown" data-ani-delay="1000" class="slide-title animated">FOOD TRUCKS</h3>
                                <p data-ani-in="fadeInUp" data-ani-out="fadeOutDown" data-ani-delay="1500" class="slide-sub-title animated"><span class="line-before"></span><span class="line-after"></span><span class="text"><span><?= \Core\Language::get('tasty') ?></span><span><?= \Core\Language::get('delicious') ?></span><span><?= \Core\Language::get('fast') ?></span></span></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="about-us-session padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6 colsm-12"><img src="/assets/images/pages/home1-about.jpg" alt="" class="img img-responsive wow zoomIn"></div>
                            <div class="col-md-6 col-sm-12">
                                <div class="swin-sc swin-sc-title style-4 margin-bottom-20 margin-top-50">
                                    <p class="top-title"><span><?= \Core\Language::get('discovery') ?></span></p>
                                    <h3 class="title"><?= \Core\Language::get('our_story') ?></h3>
                                </div>
                                <p class="des font-bold text-center"><?= \Core\Language::get("A LA BASE C'ETAIT UN SIMPLE PROJET ANNUEL") ?></p>
                                <p class="des margin-bottom-20 text-center">
                                    <?= \Core\Language::get("Ce concept assez original nous vient tout droit de l'imagination d'un immense Monsieur, dont nous tairons le noms.") ?> <span style="color: #f7f7f7; display: block;">(Fréderic Sananes)</span>
                                    <?= \Core\Language::get("Suite à des mois de travail acharné et à un passage en troisième année, le projet s'est abouti sur le lancement de la société, et aujourd'hui nous sommes la franchise numéro 1 du marché des food trucks en Europe occidentale.") ?>
                                </p>
                                <div class="swin-btn-wrap center"><a href="#" class="swin-btn center form-submit btn-transparent"> <span>	<?= \Core\Language::get('our_events_and_promotions') ?></span></a></div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="product-sesction-01 padding-bottom-100 padding-top-100">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="swin-sc swin-sc-title">
                                    <p class="top-title"><span><?= \Core\Language::get('Ce que nous pouvons vous proposer') ?></span></p>
                                    <h3 class="title"><?= \Core\Language::get('Des choses délicieuses et à bas prix') ?></h3>
                                </div>
                                <div class="swin-sc swin-sc-product products-01 style-02 woocommerce">
                                    <div class="row">
                                        <div class="col-md-2"></div>
                                        <div data-slide-toshow="5" class="cat-wrapper-02 main-slider col-md-8">
                                            <div class="item">
                                                <div class="cat-icons"><i class="icons swin-icon-pasta"></i>
                                                    <h5 class="cat-title"><?= \Core\Language::get('Petit déjeuner') ?></h5>
                                                </div>
                                            </div>
                                            <div class="item">
                                                <div class="cat-icons"><i class="icons swin-icon-fish"></i>
                                                    <h5 class="cat-title"><?= \Core\Language::get('Déjeuner') ?></h5>
                                                </div>
                                            </div>
                                            <div class="item">
                                                <div class="cat-icons"><i class="icons swin-icon-meat"></i></div>
                                                <h5 class="cat-title"><?= \Core\Language::get('Dînner') ?></h5>
                                            </div>
                                            <div class="item">
                                                <div class="cat-icons"><i class="icons swin-icon-ice-cream"></i></div>
                                                <h5 class="cat-title"><?= \Core\Language::get('Dessert') ?></h5>
                                            </div>
                                            <div class="item">
                                                <div class="cat-icons"><i class="icons swin-icon-dinner"></i></div>
                                                <h5 class="cat-title"><?= \Core\Language::get('Boissons') ?></h5>
                                            </div>
                                        </div>
                                        <div class="col-md-2"></div>
                                    </div>
                                    <div class="row">
                                        <div class="nav-slider">
                                            <div class="tab-content">
                                                <div class="col-md-5 col-sm-12">
                                                    <div class="cat-wrapper">
                                                        <div class="item"><img src="/assets/images/product/breakfast.jpg" alt="" class="img img-responsive img-full"></div>
                                                    </div>
                                                </div>
                                                <div class="col-md-7 col-sm-12">
                                                    <div class="products">
                                                        <div class="item product-01">
                                                            <div class="item-left">
                                                                <h5 class="title"><?= \Core\Language::get('Omelette sur un lit de bacon grillé') ?></h5>
                                                                <div class="des"><?= \Core\Language::get("Car on aime tous petit déjeuner à l'anglaise") ?> </div>
                                                            </div>
                                                            <div class="item-right"><span class="price woocommerce-Price-amount amount"><span class="price-symbol">€</span>10.0</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-content">
                                                <div class="col-md-5 col-sm-12">
                                                    <div class="cat-wrapper">
                                                        <div class="item"><img src="/assets/images/product/pd-cat-lunch.png" alt="" class="img img-responsive img-full"></div>
                                                    </div>
                                                </div>
                                                <div class="col-md-7 col-sm-12">
                                                    <div class="products">
                                                        <div class="item product-01">
                                                            <div class="item-left">
                                                                <h5 class="title"><?= \Core\Language::get('Riz en barquette, sauce champignons') ?></h5>
                                                                <div class="des"><?= \Core\Language::get('Car ça ne coûte pas bien plus cher de bien manger') ?> </div>
                                                            </div>
                                                            <div class="item-right"><span class="price woocommerce-Price-amount amount"><span class="price-symbol">€</span>10.0</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-content">
                                                <div class="col-md-5 col-sm-12">
                                                    <div class="cat-wrapper">
                                                        <div class="item"><img src="/assets/images/product/pd-cat-dinner.png" alt="" class="img img-responsive img-full"></div>
                                                    </div>
                                                </div>
                                                <div class="col-md-7 col-sm-12">
                                                    <div class="products">
                                                        <div class="item product-01">
                                                            <div class="item-left">
                                                                <h5 class="title"><?= \Core\Language::get('Riz en barquette, sauce champignons du soir') ?></h5>
                                                                <div class="des"><?= \Core\Language::get('Car ça ne coûte toujours pas bien plus cher de bien manger') ?> </div>
                                                            </div>
                                                            <div class="item-right"><span class="price woocommerce-Price-amount amount"><span class="price-symbol">€</span>10.0</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-content">
                                                <div class="col-md-5 col-sm-12">
                                                    <div class="cat-wrapper">
                                                        <div class="item"><img src="/assets/images/product/pd-cat-dessert.png" alt="" class="img img-responsive img-full"></div>
                                                    </div>
                                                </div>
                                                <div class="col-md-7 col-sm-12">
                                                    <div class="products">
                                                        <div class="item product-01">
                                                            <div class="item-left">
                                                                <h5 class="title"><?= \Core\Language::get("Glace au coulis de chocolat au napage de chocolat sur un lit de chocolat à la base de chocolat au chocolat") ?></h5>
                                                                <div class="des"><?= \Core\Language::get('Car même si ça ne coûte pas bien plus cher de bien manger, il faut savoir se faire plaisir') ?> </div>
                                                            </div>
                                                            <div class="item-right"><span class="price woocommerce-Price-amount amount"><span class="price-symbol">€</span>7.0</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-content">
                                                <div class="col-md-5 col-sm-12">
                                                    <div class="cat-wrapper">
                                                        <div class="item"><img src="/assets/images/product/drinks.jpg" alt="" class="img img-responsive img-full"></div>
                                                    </div>
                                                </div>
                                                <div class="col-md-7 col-sm-12">
                                                    <div class="products">
                                                        <div class="item product-01">
                                                            <div class="item-left">
                                                                <h5 class="title">Coca-Cola</h5>
                                                                <div class="des"><?= \Core\Language::get("Un classique qu'on ne peut oublier") ?></div>
                                                            </div>
                                                            <div class="item-right"><span class="price woocommerce-Price-amount amount"><span class="price-symbol">€</span>4.0</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div> <!-- ROW -->
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -150px;" class="testimonial-section-01 padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="swin-sc swin-sc-title">
                                    <p class="top-title"><span><?= \Core\Language::get('testimonial') ?></span></p>
                                    <h3 class="title white-color"><?= \Core\Language::get('Ils parlent de nous') ?></h3>
                                </div>
                                <div class="row">
                                    <div class="col-md-10 col-md-offset-1">
                                        <div class="swin-sc swin-sc-testimonial style-1">
                                            <div class="main-slider flexslider">
                                                <div class="slides">
                                                    <div class="testi-item item"><i class="testi-icon fa fa-quote-left"></i>
                                                        <div class="testi-content">
                                                            <p><?= \Core\Language::get("De passage sur Paris, il me fallait un repas goûtu rapidemment, pour pas très cher sans pour autant y laisser la qualité, je me suis donc tourné vers un Food Truck de Driv'n'Cook, et j'ai été ravi.") ?></p>
                                                        </div>
                                                        <div class="testi-info"><span class="name">Kamal Hennou</span> <span class="position"><?= \Core\Language::get('customer') ?></span></div>
                                                    </div>
                                                    <div class="testi-item item"><i class="testi-icon fa fa-quote-left"></i>
                                                        <div class="testi-content">
                                                            <p><?= \Core\Language::get("Devenir un franchisé de Drinv'N'Cook a permis a mon entreprise de grandir grace a la qualité des services et la reconnaissance de la marque") ?></p>
                                                        </div>
                                                        <div class="testi-info"><span class="name">Frédéric Sananes</span> <span class="position"><?= \Core\Language::get('franchisee') ?></span></div>
                                                    </div>
                                                    <div class="testi-item item"><i class="testi-icon fa fa-quote-left"></i>
                                                        <div class="testi-content">
                                                            <p><?= \Core\Language::get("C'était bon.") ?></p>
                                                        </div>
                                                        <div class="testi-info"><span class="name">Dora SAADAN</span> <span class="position"><?= \Core\Language::get('Cliente') ?></span></div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div data-width="150" class="nav-slider">
                                                <ul class="slides list-inline">
                                                    <li class="swin-transition"><a href="javascript:void(0)" class="testimonial-nav-item"><img src="/assets/images/testi/testi-1.jpg" alt="drivncook" class="img img-responsive swin-transition"></a></li>
                                                    <li class="swin-transition"><a href="javascript:void(0)" class="testimonial-nav-item"><img src="/assets/images/testi/testi-2.jpg" alt="drivncook" class="img img-responsive swin-transition"></a></li>
                                                    <li class="swin-transition"><a href="javascript:void(0)" class="testimonial-nav-item"><img src="/assets/images/testi/testi-3.jpg" alt="drivncook" class="img img-responsive swin-transition"></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="service-section-02 padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="swin-sc swin-sc-title">
                            <p class="top-title"><span><?= \Core\Language::get('our_services') ?></span></p>
                            <h3 class="title"><?= \Core\Language::get('what_we_propose') ?></h3>
                        </div>
                        <div class="swin-sc swin-sc-iconbox">
                            <div class="row">
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div class="item icon-box-02 wow fadeInUpShort">
                                        <div class="wrapper-icon"><i class="icons swin-icon-dish"></i><span class="number">1</span></div>
                                        <h4 class="title"><?= \Core\Language::get('a_choice_panel') ?></h4>
                                        <div class="description"><?= \Core\Language::get("Chaque Food Truck Driv'n'Cook possède sa propre culture et cuisine ses propres repas, découvrez les variétés du monde.") ?></div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div data-wow-delay="0.5s" class="item icon-box-02 wow fadeInUpShort">
                                        <div class="wrapper-icon"><i class="icons swin-icon-dinner-2"></i><span class="number">2</span></div>
                                        <h4 class="title"><?= \Core\Language::get('private_events') ?></h4>
                                        <div class="description"><?= \Core\Language::get('Nous organisons régulièrement des événements pour nos franchisés et nos clients, inscrivez-vous à la newletters pour ne rien louper') ?></div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div data-wow-delay="1s" class="item icon-box-02 wow fadeInUpShort">
                                        <div class="wrapper-icon"><i class="icons swin-icon-browser"></i><span class="number">3</span></div>
                                        <h4 class="title"><?= \Core\Language::get('follow_up_online') ?></h4>
                                        <div class="description"><?= \Core\Language::get("Nos infrastructures sont multi-supports, suivez n'importe quelle de vos actions sur nos services en ligne") ?></div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div data-wow-delay="1.5s" class="item icon-box-02 wow fadeInUpShort">
                                        <div class="wrapper-icon"><i class="icons swin-icon-delivery"></i><span class="number">4</span></div>
                                        <h4 class="title"><?= \Core\Language::get('truck_rentals') ?></h4>
                                        <div class="description"><?= \Core\Language::get("Driv'n'Cook vous prête un food trucks totalement aménagé et personnalisable.") ?></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="gallery-section-01 padding-top-100">
                    <div class="swin-sc swin-sc-title">
                        <p class="top-title"><span><?= \Core\Language::get('our_gallery') ?></span></p>
                        <h3 class="title white-color"><?= \Core\Language::get("Photos des Food Trucks Driv'n'Cook") ?></h3>
                    </div>
                    <div class="swin-sc swin-sc-isotope">
                        <div class="grid">
                            <div class="grid-sizer col-sm-1"></div>
                            <div class="grid-item col-sm-3 grid-item-h2">
                                <div class="grid-wrap-item"><a href="#" class="gallery-title title">Repas au food truck de dammary</a><a href="/assets/images/gallery/gallery-1.jpg" data-lightbox="image" class="view-lightbox swipebox"><i class="fa fa-search-plus"></i></a>
                                    <div class="img-wrap"><img src="/assets/images/gallery/gallery-1.jpg" alt="" class="img img-responsive"></div>
                                </div>
                            </div>
                            <div class="grid-item col-sm-4 grid-item-h1">
                                <div class="grid-wrap-item"><a href="#" class="gallery-title title">Event a Melun</a><a href="/assets/images/gallery/gallery-2.jpg" data-lightbox="image" class="view-lightbox swipebox"><i class="fa fa-search-plus"></i></a>
                                    <div class="img-wrap"><img src="/assets/images/gallery/gallery-2.jpg" alt="" class="img img-responsive"></div>
                                </div>
                            </div>
                            <div class="grid-item col-sm-2 grid-item-h1">
                                <div class="grid-wrap-item"><a href="#" class="gallery-title title">Repas à la Chicago</a><a href="/assets/images/gallery/gallery-3.jpg" data-lightbox="image" class="view-lightbox swipebox"><i class="fa fa-search-plus"></i></a>
                                    <div class="img-wrap"><img src="/assets/images/gallery/gallery-3.jpg" alt="" class="img img-responsive"></div>
                                </div>
                            </div>
                            <div class="grid-item col-sm-3 grid-item-h2">
                                <div class="grid-wrap-item"><a href="#" class="gallery-title title">Repas à Monpellier</a><a href="/assets/images/gallery/gallery-4.jpg" data-lightbox="image" class="view-lightbox swipebox"><i class="fa fa-search-plus"></i></a>
                                    <div class="img-wrap"><img src="/assets/images/gallery/gallery-4.jpg" alt="" class="img img-responsive"></div>
                                </div>
                            </div>
                            <div class="grid-item col-sm-2 grid-item-h1">
                                <div class="grid-wrap-item"><a href="#" class="gallery-title title">Repas à Strasbourg</a><a href="/assets/images/gallery/gallery-5.jpg" data-lightbox="image" class="view-lightbox swipebox"><i class="fa fa-search-plus"></i></a>
                                    <div class="img-wrap"><img src="/assets/images/gallery/gallery-5.jpg" alt="" class="img img-responsive"></div>
                                </div>
                            </div>
                            <div class="grid-item col-sm-4 grid-item-h1">
                                <div class="grid-wrap-item"><a href="#" class="gallery-title title">Repas au food truck de Nantes</a><a href="/assets/images/gallery/gallery-6.jpg" data-lightbox="image" class="view-lightbox swipebox"><i class="fa fa-search-plus"></i></a>
                                    <div class="img-wrap"><img src="/assets/images/gallery/gallery-6.jpg" alt="" class="img img-responsive"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="blog-section padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="swin-sc swin-sc-title">
                                    <p class="top-title"><span><?= \Core\Language::get('Événement & Promotions') ?></span></p>
                                    <h3 class="title"><?= \Core\Language::get('our_future_events') ?></h3>
                                </div>
                                <div class="swin-sc swin-sc-blog-grid"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="swin-sc swin-sc-blog-grid">
                                    <div class="row">
                                        <?php foreach ($events as $event) : ?>
                                            <div class="col-md-4 col-sm-6 col-xs-12">
                                                <div data-wow-delay="0s" class="blog-item swin-transition item wow fadeInUpShort">
                                                    <div class="blog-featured-img"><img src="<?= '/dist/uploads/event/' . $event['id'] . '/' . $event['image'] ?>" alt="drivncook" class="img img-responsive"></div>
                                                    <div class="blog-content">
                                                        <div class="blog-date">
                                                            <span class="day"><?= date_format($event['startAt'], "d") ?></span>
                                                            <span class="month"><?= date_format($event['startAt'], "M") ?></span>
                                                        </div>
                                                        <h3 class="blog-title"><a href="/events/detail/<?= $event['id'] ?>" class="swin-transition"><?= $event['name'] ?></a></h3>
                                                        <p class="blog-description"><?= \Core\Language::lang() == 'fr_FR' ? $event['textFr'] : $event['textEn'] ?></p>
                                                        <div class="blog-readmore"><a href="/events/detail/<?= $event['id'] ?>" class="swin-transition"><?= \Core\Language::get('more_information') ?> <i class="fa fa-angle-double-right"></i></a></div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endforeach ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <?php require "assets/footer.phtml"; ?>
    </div>
    <?php require "assets/loader.phtml"; ?>
</div>
<?php require "assets/dependancies.phtml"; ?>
</body>

</html>