<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>
<style>
    body {
	    font-family: Helvetica, Arial, sans-serif;
	}

	table {
        width: 90%;
        margin: 0 auto;
        table-layout:fixed;
        border-collapse: collapse;
	}

	td {
        padding:1em 0 0 0;
        vertical-align:bottom;
        background-image:radial-gradient(black 1px, white 0px);
        background-size: 8px 8px;
        background-repeat:repeat-x;
        background-position: left bottom;
	}
	
	td:first-child {
        text-align: left;
        font-weight: 700;
	}
	
	td:first-child span {
	    padding-right:.25em;
	}

  	td:last-child {
        text-align:right;
        width:3em;
  	}
  	
  	td:last-child span {
	    padding-left:.25em;
	}

    .blog-item {
        margin-top: 15px
    }
</style>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-blog">
                <div class="container">
                    <div class="title-wrapper">
                        <div data-top="transform: translateY(0px);opacity:1;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title">Les menus</div>
                        <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                        <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle">Passez commande en avance en ligne</div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="swin-sc swin-sc-title style-2">
                            <h1 class="title"><span>Voir la carte de <?= $user->getSocietyName(); ?></span></h1>
                        </div>

                        <?php if($customer == false) { ?>

                            <div class="alert alert-info">
                                Vous devez être connecté pour passer commande. <br>
                                <a href="/customers/login">Cliquez-ici pour vous connecter.</a>
                            </div>

                        <?php } ?>

                        <div class="row">
                            <?php foreach($cards as $card) : $total = 0; ?>
                                <div class="col-md-4">
                                    <div class="blog-item swin-transition">
                                        <div class="blog-content">
                                            <h3 class="title">
                                                <?= $card->getName(); ?>
                                            </h3>
                                            <hr>
                                            <?php foreach ($cardCategories[$card->getId()] as $category) : ?>
                                                <h4 style="margin-bottom: -6px;"><?= $category->getName(); ?></h4>
                                                <?php if (!empty($cardItems)): ?>
                                                    <table>
                                                        <?php foreach ($cardItems[$card->getId()] as $item) : ?>
                                                            <tr>
                                                                <?php if ($item['card_category_name'] === $category->getName()) : ?>
                                                                    <td>
                                                                        <?= htmlspecialchars(trim($item['card_item_name'])) ?>
                                                                    </td>
                                                                    <td>
                                                                        <?= number_format($item['card_item_price'], 2) ?>€
                                                                    </td>
                                                                <?php $total += $item['card_item_price']; ?>
                                                                <?php endif ?>
                                                            </tr>
                                                        <?php endforeach ?>
                                                    </table>
                                                <?php endif ?>
                                            <?php endforeach ?>
                                        </div>
                                        <?php if($customer != false) { ?>
                                            <td><a href="/trucks/menu/<?= $truck->getId(); ?>/commands/<?= $card->getId(); ?>" class="btn  btn-block btn-primary" style="background-color: #f15f2a; border-color: #f15f2a">Commander (Total: <?= number_format($total, 2) ?>€)</a></td>
                                        <?php } else { ?>
                                            <td><a disabled="" href="/customers/login" class="btn btn-block btn-primary" style="background-color: #f15f2a; border-color: #f15f2a">Connectez-vous pour commander</a></td>
                                        <?php } ?>
                                    </div>
                                </div>
                            <?php endforeach ?>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <?php require "assets/footer.phtml"; ?>
    </div>
    <?php require "assets/loader.phtml"; ?>
</div>
<?php require "assets/dependancies.phtml"; ?>
</body>
</html>