<!DOCTYPE html>
<html lang="fr">
<?php require "assets/head.phtml"; ?>
<body>
<div id="pagewrap" class="pagewrap">
    <div id="html-content" class="wrapper-content">
        <?php require "assets/header.phtml"; ?>
        <div class="page-container">
            <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-blog">
                <div class="container">
                    <div class="title-wrapper">
                        <div data-top="transform: translateY(0px);opacity:1;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title"><?= \Core\Language::get('trucks') ?></div>
                        <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                        <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle"><?= \Core\Language::get("Venez Voir les camion de la franchise Driv'N'Cook") ?></div>
                    </div>
                </div>
            </div>
            <div class="page-content-wrapper">
                <section class="padding-top-100 padding-bottom-100">
                    <div class="container">
                        <div class="swin-sc swin-sc-title style-2">
                            <h1 class="title"><span><?= \Core\Language::get('our_food_truck') ?></span></h1>
                        </div>
                      <div id="map" style="height: 450px"></div>
                        <br>

                        <div class="row">
                            <?php foreach ($trucks as $truck): ?>
                                <div class="main-slider col-md-6" style="text-align: center">
                                    <div class="slides">
                                        <div class="blog-item swin-transition">
                                            <div class="blog-content" style="padding: 10px 20px 0; margin-bottom: 20px">
                                                <h3 class="blog-title">
                                                    <a href="/trucks/menu/<?= $truck->getId(); ?>" class="swin-transition">
                                                        <?= $truck->user->getSocietyName(); ?>
                                                    </a>
                                                </h3>

                                                <ul class="list-group">
                                                    <?php foreach ($functions as $key => $day): ?>
                                                        <li class="list-group-item" style="<?= ($key == date('N')) ? 'font-weight:bold;' : ''; ?>">
                                                            <?php switch ($key) {
                                                                case 1:
                                                                    echo 'Lundi';
                                                                    break;
                                                                case 2:
                                                                    echo 'Mardi';
                                                                    break;
                                                                case 3:
                                                                    echo 'Mercredi';
                                                                    break;
                                                                case 4:
                                                                    echo 'Jeudi';
                                                                    break;
                                                                case 5:
                                                                    echo 'Vendredi';
                                                                    break;
                                                                case 6:
                                                                    echo 'Samedi';
                                                                    break;
                                                                default:
                                                                    echo 'Dimanche';
                                                                    break;
                                                            } ?>
                                                            : <?= call_user_func([$truck->openings, $day['open']])->format('H:i'); ?>
                                                            - <?= call_user_func([$truck->openings, $day['close']])->format('H:i'); ?>
                                                            <?php if(!$truck->isOpen && $key == date('N')) { ?>
                                                                (fermé)
                                                            <?php } ?>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>

                                                <!-- Si coordonnées valides -->
                                                <?php if(is_float($truck->getLatitude()) && is_float($truck->getLongitude())){ ?>
                                                    <!-- Lien vers l'API Google Map -->
                                                    <div class="blog-readmore pull-left"><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=<?= $truck->getLatitude(); ?>,<?= $truck->getLongitude(); ?>" class="swin-transition">Localiser <i class="fa fa-location-arrow"></i></a></div>
                                                <?php } ?>
                                                <div class="blog-readmore"><a href="/trucks/menu/<?= $truck->getId(); ?>" class="swin-transition">Voir le menu <i class="fa fa-shopping-basket"></i></a></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>

                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
<script async type="text/javascript">
    // Centre de la carte par défaut -> Paris

    var map = null;
    var geocoder;
    function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {
            zoom: 11,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            mapTypeControl: true,
            scrollwheel: false,
            mapTypeControlOptions: {
                style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR
            },
            navigationControl: true,
            navigationControlOptions: {
                style: google.maps.NavigationControlStyle.ZOOM_PAN
            }
        });

        geocoder = new google.maps.Geocoder();

        // CENTRER LA MAP PAR DEFAUT SUR LA FRANCE
        geocoder.geocode({'address': "Ile-De-France"}, function(results, status) {
            if (status === 'OK') {
                map.setCenter(results[0].geometry.location);
            } else {
                console.error('Geocode was not successful for the following reason: ' + status);
            }
        });

        var mapPopup = new google.maps.InfoWindow();
        var trucksLocates = '<?= $trucksLocates; ?>'
        trucksLocates = JSON.parse(trucksLocates);
        for(let i = 0; i < trucksLocates.length; i++) {
            marker = new google.maps.Marker({
                position:
                {
                    lat: trucksLocates[i]['lat'], lng: trucksLocates[i]['lon']
                },
                icon: {
                    url: 'https://img.icons8.com/color/48/000000/rv-campground.png'
                },
                map: map
            });

            google.maps.event.addListener(marker, 'click', (function (marker, i) {
                return function () {
                    let content = trucksLocates[i]['name'] +
                                    '<br><br><a href="/trucks/menu/'+ trucksLocates[i]['id'] +'">Voir le menu</a>';

                    mapPopup.setContent(content);
                    mapPopup.open(map, marker);
                }
            })(marker, i));
        }
    }
    markerClicked = () => {console.log('Clicked')}
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<?= \App\Config::GOOGLE_API_KEY; ?>&callback=initMap&language=fr&region=idf"></script>

</body>
</html>