<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Driv'n'Cook - Espace client</title>
    <link rel="icon" type="image/png" href="/dist/img/drivncook.png" />
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/dist/css/adminlte.css">
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php require "assets/sidebar.phtml"; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Driv'n'Cook</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item active"><?= \Core\Language::get('home'); ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>


        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">

                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Mes commandes Driv'N'Cook</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                <table id="orders" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Numéro de commande</th>
                                        <th>Date</th>
                                        <th>Food Truck</th>
                                        <th>Récupération le</th>
                                        <th>Status</th>
                                        <th>Prix TTC</th>
                                        <th>Message</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($orders as $order): ?>
                                        <tr>
                                            <td>DVN02<?= $order->getId() ?></td>
                                            <td>
                                                <?= $order->getCreatedAt()->format('d/m/Y H:i'); ?>
                                            </td>
                                            <td><?= $order->getUser()->getSocietyName() ?></td>
                                            <td><?= date('d/m/Y H:i', $order->getRecuperationDate()); ?></td>
                                            <td>
                                                <?php
                                                    switch ($order->getStatus()){
                                                        case 2:
                                                            echo '<span class="badge badge-warning">En traitement</span>';
                                                            break;
                                                        case 3:
                                                            echo '<span class="badge badge-info">Terminée</span>';
                                                            break;
                                                        case 4:
                                                            echo '<span class="badge badge-success">Récupérée</span>';
                                                            break;
                                                        default:
                                                            echo '<span class="badge badge-danger">Non traîtée</span>';
                                                            break;
                                                    }
                                                ?>
                                            </td>
                                            <td><?= number_format($order->priceTotal, 2); ?>€</td>
                                            <td>
                                                <a href="#" data-toggle="modal" data-target="#labelMessage<?= $order->getId(); ?>" class="btn btn-sm btn-info">Votre message</a>
                                            </td>
                                        </tr>

                                        <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="labelMessage<?= $order->getId(); ?>" id="labelMessage<?= $order->getId(); ?>" aria-hidden="true">
                                            <div class="modal-dialog modal-sm">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title">Mon message</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <?= nl2br($order->getDescription()); ?>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>Numéro de commande</th>
                                        <th>Date</th>
                                        <th>Food Truck</th>
                                        <th>Récupération le</th>
                                        <th>Status</th>
                                        <th>Prix TTC</th>
                                        <th>Message</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <div class="card-footer clearfix">
                                <a href="/trucks" class="btn btn-sm btn-info float-left">Passer une nouvelle commande</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>

    </div>

    <aside class="control-sidebar control-sidebar-dark">
    </aside>

    <footer class="main-footer">
        <strong>Copyright &copy; <?= date('Y'); ?> Driv'n'Cook.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            Projet annuel ESGI <b>2A2</b>
        </div>
    </footer>
</div>

<script src="/plugins/jquery/jquery.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="/dist/js/adminlte.js"></script>
<script>
    $(function() {
        $("#orders").DataTable({
            language: {
                url: '<?= \Core\Language::get("datatable_trad_link") ?>'
            }
        });
    });
</script>
</body>
</html>
