<!-- jQuery-->
<script src="/assets/vendors/jquery-1.10.2.min.js"></script>
<!-- Bootstrap JavaScript-->
<script src="/assets/vendors/bootstrap/js/bootstrap.min.js"></script>
<!-- Vendors-->
<script src="/assets/vendors/flexslider/jquery.flexslider-min.js"></script>
<script src="/assets/vendors/swipebox/js/jquery.swipebox.min.js"></script>
<script src="/assets/vendors/slick/slick.min.js"></script>
<script src="/assets/vendors/isotope/isotope.pkgd.min.js"></script>
<script src="/assets/vendors/jquery-countTo/jquery.countTo.min.js"></script>
<script src="/assets/vendors/jquery-appear/jquery.appear.min.js"></script>
<script src="/assets/vendors/parallax/parallax.min.js"></script>
<script src="/assets/vendors/gmaps/gmaps.min.js"></script>
<script src="/assets/vendors/audiojs/audio.min.js"></script>
<script src="/assets/vendors/vide/jquery.vide.min.js"></script>
<script src="/assets/vendors/pageloading/js/svgLoader.min.js"></script>
<script src="/assets/vendors/pageloading/js/classie.min.js"></script>
<script src="/assets/vendors/pageloading/sidebartransition/js/sidebarEffects.min.js"></script>
<script src="/assets/vendors/nicescroll/jquery.nicescroll.min.js"></script>
<script src="/assets/vendors/wowjs/wow.min.js"></script>
<script src="/assets/vendors/skrollr.min.js"></script>
<script src="/assets/vendors/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<script src="/assets/vendors/jquery-cookie/js.cookie.js"></script>
<script src="/assets/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<!-- Own script-->
<script src="/assets/js/layout.js"></script>
<script src="/assets/js/elements.js"></script>
<script src="/assets/js/widget.js"></script>