<footer>
    <div class="subscribe-section"><img src="/assets/images/background/bg5.png" alt="" class="img-subscribe">
        <div class="container">
            <div class="subscribe-wrapper">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="subscribe-heading">
                            <h3 class="title">Inscrivez-vous à la newletters</h3>
                            <div class="des">Soyez tenu au courant de nos dernières promotions</div>
                        </div>
                        <form method="POST" class="widget-newsletter">
                            <input placeholder="Email" name="email" class="form-control">
                            <span class="submit">
                                        <i class="fa fa-paper-plane"></i>
                                    </span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-top"></div>
    <div class="footer-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="ft-widget-area">
                        <div class="ft-area1">
                            <div class="swin-wget swin-wget-about">
                                <div class="clearfix"><a class="wget-logo"><img src="/assets/images/logo.png" alt="" class="img img-responsive"></a>
                                    <ul class="socials socials-about list-unstyled list-inline">
                                        <li><a href="https://facebook.com/ESGIParis"><i class="fa fa-facebook"></i></a></li>
                                    </ul>
                                </div>
                                <div class="wget-about-content">
                                    <p>DRIV'N'COOK SAS, Société par Actions Simplifiés enregistrée à la chambre de commerce de Paris dont le siège social se trouve au 242 rue du Faubourg Saint Antoine, 75012, Paris.<br> Numéro de SIRET : PROJETANNUEL20SUR20.<br>
                                    </p>
                                </div>
                                <div class="about-contact-info clearfix">
                                    <div class="address-info">
                                        <div class="info-icon"><i class="fa fa-map-marker"></i></div>
                                        <div class="info-content">
                                            <p>242 rue du Faubourg Saint Antoine, 75012, Paris</p>
                                        </div>
                                    </div>
                                    <div class="phone-info">
                                        <div class="info-icon"><i class="fa fa-mobile-phone"></i></div>
                                        <div class="info-content">
                                            <p>(+33) 1 56 06 90 41</p>
                                        </div>
                                    </div>
                                    <div class="email-info">
                                        <div class="info-icon"><i class="fa fa-envelope"></i></div>
                                        <div class="info-content">
                                            <p>contact@drivncook.store</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="ft-fixed-area">
                        <div class="reservation-box">
                            <div class="reservation-wrap">
                                <h3 class="res-title">Ouvertures</h3>
                                <div class="res-date-time">
                                    <div class="res-date-time-item">
                                        <div class="res-date">
                                            <div class="res-date-item">
                                                <div class="res-date-text">
                                                    <p>Lundi:</p>
                                                </div>
                                                <div class="res-date-dot">.......................................</div>
                                            </div>
                                        </div>
                                        <div class="res-time">
                                            <div class="res-time-item">
                                                <p>24h / 24h</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="res-date-time-item">
                                        <div class="res-date">
                                            <div class="res-date-item">
                                                <div class="res-date-text">
                                                    <p>Mardi:</p>
                                                </div>
                                                <div class="res-date-dot">.......................................</div>
                                            </div>
                                        </div>
                                        <div class="res-time">
                                            <div class="res-time-item">
                                                <p>24h / 24h</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="res-date-time-item">
                                        <div class="res-date">
                                            <div class="res-date-item">
                                                <div class="res-date-text">
                                                    <p>Mercredi:</p>
                                                </div>
                                                <div class="res-date-dot">.......................................</div>
                                            </div>
                                        </div>
                                        <div class="res-time">
                                            <div class="res-time-item">
                                                <p>24h / 24h</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="res-date-time-item">
                                        <div class="res-date">
                                            <div class="res-date-item">
                                                <div class="res-date-text">
                                                    <p>Jeudi:</p>
                                                </div>
                                                <div class="res-date-dot">.......................................</div>
                                            </div>
                                        </div>
                                        <div class="res-time">
                                            <div class="res-time-item">
                                                <p>24h / 24h</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="res-date-time-item">
                                        <div class="res-date">
                                            <div class="res-date-item">
                                                <div class="res-date-text">
                                                    <p>Vendredi:</p>
                                                </div>
                                                <div class="res-date-dot">.......................................</div>
                                            </div>
                                        </div>
                                        <div class="res-time">
                                            <div class="res-time-item">
                                                <p>24h / 24h</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="res-date-time-item">
                                        <div class="res-date">
                                            <div class="res-date-item">
                                                <div class="res-date-text">
                                                    <p>Samedi:</p>
                                                </div>
                                                <div class="res-date-dot">.......................................</div>
                                            </div>
                                        </div>
                                        <div class="res-time">
                                            <div class="res-time-item">
                                                <p>24h / 24h</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="res-date-time-item">
                                        <div class="res-date">
                                            <div class="res-date-item">
                                                <div class="res-date-text">
                                                    <p>Dimanche:</p>
                                                </div>
                                                <div class="res-date-dot">.......................................</div>
                                            </div>
                                        </div>
                                        <div class="res-time">
                                            <div class="res-time-item">
                                                <p>24h / 24h</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer><a id="totop" href="#" class="animated"><i class="fa fa-angle-double-up"></i></a>
