<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/customers" class="nav-link <?= (isset($page) && $page == "commands") ? 'active' : ''; ?>">Espace client</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/customers/my-account" class="nav-link <?= (isset($page) && $page == "account") ? 'active' : ''; ?>"><?= \Core\Language::get('my_account'); ?></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/customers/logout" class="nav-link"><?= \Core\Language::get('logout'); ?></a>
        </li>
        <li class="nav-item dropdown">
            <?php if (!empty($_COOKIE['language']) && $_COOKIE['language'] == "fr_FR") { ?>
                <a href="#" class="nav-link dropdown-toggle" id="droplangdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="flag-icon flag-icon-fr"> </span> Français</a>
            <?php } else { ?>
                <a href="#" class="nav-link dropdown-toggle" id="droplangdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="flag-icon flag-icon-us"> </span> English</a>
            <?php } ?>
            <div class="dropdown-menu" aria-labelledby="droplangdown">
                <?php if (!empty($_COOKIE['language']) && $_COOKIE['language'] == "fr_FR") { ?>
                    <a class="dropdown-item" href="/lang/pref/en"><span class="flag-icon flag-icon-us"> </span> English</a>
                <?php } else { ?>
                    <a class="dropdown-item" href="/lang/pref/fr"><span class="flag-icon flag-icon-fr"> </span> Français</a>
                <?php } ?>
            </div>
        </li>
    </ul>
</nav>

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="/customers" class="brand-link">
        <img src="/dist/img/drivncook.png" alt="Driv'n'Cook Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Driv'n'Cook</span>
    </a>

    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="/customers/my-account" class="d-block"><?= $customer->getFirstname() . ' ' . $customer->getLastname(); ?></a>
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="/" class="nav-link">
                        <i class="nav-icon fa fa-home"></i>
                        <p>
                            <?= \Core\Language::get('home'); ?>
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/trucks" class="nav-link">
                        <i class="nav-icon fa fa-shopping-basket"></i>
                        <p>
                            Passer commande
                        </p>
                    </a>
                </li>

                <li class="nav-header">MON ESPACE CLIENT</li>

                <li class="nav-item">
                    <a href="/customers/commands" class="nav-link <?= (isset($page) && $page == "commands") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-shopping-bag"></i>
                        <p>
                            Mes commandes
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/customers/invoices" class="nav-link <?= (isset($page) && $page == "invoice") ? 'active' : ''; ?>">
                        <i class="nav-icon fa fa-file-invoice"></i>
                        <p>
                            Mes factures
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>