<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-warning">
                    <div class="card-header">
                        <h3 class="card-title"><?= \Core\Language::get($page) ?></h3>
                    </div>
                    <form role="form" method="POST">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="emailInput"><?= \Core\Language::get('email') ?></label>
                                <input type="email" class="form-control <?= (isset($fields['email'])) ? 'is-invalid' : ''; ?>" id="emailInput" placeholder="<?= \Core\Language::get("email") ?>" name="email" value="<?= \Core\View::set_values('email', isset($customer) ? $customer->getEmail() : NULL) ?>">
                            </div>

                            <div class="form-group">
                                <label for="firstnameInput"><?= \Core\Language::get('firstname') ?></label>
                                <input type="text" class="form-control <?= (isset($fields['firstname'])) ? 'is-invalid' : ''; ?>" id="firstnameInput" placeholder="<?= \Core\Language::get('firstname') ?>" name="firstname" value="<?= \Core\View::set_values('firstname',isset($customer) ? $customer->getFirstname() : NULL) ?>">
                            </div>

                            <div class="form-group">
                                <label for="lastnameInput"><?= \Core\Language::get('lastname') ?></label>
                                <input type="text" class="form-control <?= (isset($fields['lastname'])) ? 'is-invalid' : ''; ?>" id="lastnameInput" placeholder="<?= \Core\Language::get('lastname') ?>" name="lastname" value="<?= \Core\View::set_values('lastname', isset($customer) ? $customer->getLastname() : NULL) ?>">
                            </div>

                            <hr>

                            <div class="form-group">
                                <label for="passwordInput"><?= \Core\Language::get('password') ?></label>
                                <input type="password" class="form-control <?= (isset($fields['password'])) ? 'is-invalid' : ''; ?>" id="passwordInput" name="password" placeholder="<?= \Core\Language::get('password') ?>">
                            </div>

                            <div class="form-group">
                                <label for="passwordConfirmInput"><?= \Core\Language::get('confirm_password') ?></label>
                                <input type="password" class="form-control <?= (isset($fields['password'])) ? 'is-invalid' : ''; ?>" id="passwordConfirmInput" name="passwordConfirm" placeholder="<?= \Core\Language::get('confirm_password') ?>">
                            </div>
                        </div>

                        <div class="card-footer">
                            <?= \Core\CSRF::fields(); ?>
                            <button type="submit" class="btn btn-warning"><?= \Core\Language::get('save') ?></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>